- LEAF_Nexus/sources/Employee.php
- LEAF_Nexus/sources/Login.php
- LEAF_Request_Portal/Email.php
- LEAF_Request_Portal/Login.php
- LEAF_Request_Portal/sources/FormEditor.php
Updated instances of mt_rand() in php files to use random_int() instead.
mt_rand() can "randomly" generate predictable numbers.
> Update insecure random numbers in php.

- LEAF_Request_Portal/js/formSearch.js
- libs/js/LEAF/formSearch.js
In the portal, under advanced options: the "remove" option for added criteria was not reachable or actionable with the keyboard.
> Updated remove button from advanced search for keyboard navigation

- LEAF_Request_Portal/form.php
Fixed requirement of adding unnecessary step to workflow in order to
enable collaborator group read access.
`form.php:checkReadAccess()` now checks the `category_privs` database
table for groups that have read access to the form.
> Form Collaborator Group Read Access fix

- LEAF_Request_Portal/templates/reports/LEAF_TEST_timeline.tpl
Added option to include any "Send Back" time in the request timeline.
Enabling this option will add an extra bar segment for the average time
elapsed between a step being sent back to the requestor and when the
request is re-submitted.
> Show "Send Back" time in request timeline

- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/api/controllers/FormEditorController.php
- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/sources/FormEditor.php
- test/LEAF_Request_Portal_Tests/db/seeds/BaseTestSeed.php
- test/LEAF_Request_Portal_Tests/tests/api/FormControllerTest.php
- test/LEAF_Request_Portal_Tests/tests/api/FormEditorControllerTest.php
added "sensitive" attribute to form editor and implemented persistency.  In addition, updated the test files the "sensitive" attribute added in.
> Leaf494 and 495 sensitive indicators

- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
- libs/php-commons/XSSHelpers.php
Content copy/pasted from rich text documents sometimes leads to the addition of XML tags that the user did not intend on including
> Workaround to cleanup copy/pasted content

- LEAF_Request_Portal/templates/subindicators.tpl
If a user selects an Employee from the employee selector for a form
indicator value, previously they were not allowed to set that indicator
as "Unassigned". The selector would persist the previous value. Now a
user can clear out that indicator data.
> Allow "Unassigned" employee selector

- LEAF_Request_Portal/sources/System.php
This caused problems before, but scrubFilename has been updated to a blacklist instead of a whitelist. Now it just scrubs characters that windows disallows. /:*?"<>|\
> LEAF759 ATO Cross Site Scripting

- LEAF_Request_Portal/sources/System.php
Initially, $_FILES['file']['tmp_name'] was being scrubbed, but this is a filepath defined by the server, so can't be tainted by user input. The filename given by the user is scrubbed for illegal characters. 
Can be tested at portal/admin/?a=mod_file_manager
> LEA774_ATO_scrub_file_name

- libs/dynicons/index.php
The file name scrubber used to use a whitelist, but is now a blacklist for illegal characters. This is for the icons that show up throughout the application.
> LEAF778 ATO path manipulation

- LEAF_Request_Portal/js/formGrid.js
Generating CSV for the Report Builder export was switched to a Javascript
implementation from a "converter" endpoint.
Some versions of IE need to handle the download of that CSV a little
differently.
> Internet Explorer specific fix for formGrid.js

- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
- LEAF_Request_Portal/templates/subindicators.tpl
Regardless of toggle, unmasked indicator data appears in the edit box.
> LEAF769 editing masked indicators

- libs/php-commons/XSSHelpers.php
There are tons of warnings clogging up the error logs, but nothing is functionally broken. We're just turning the warnings off.
> supress warnings in sanitizer

- LEAF_Request_Portal/js/gridInput.js
when selecting the saved option from a dropdown that contained special characters or spaces, it would fail and throw a javascript error.  Changing how it is selected fixes it.
> hotfix for gridInput dropdown

- LEAF_Nexus/sources/Employee.php
- LEAF_Request_Portal/templates/subindicators.tpl
Allowed unassigning of employee via clearing input box.  To test, answer an org chart employee indicator question and save. Finally, open the question again and clear the field.   Employee should now show up as unassigned on the printview page.
> LEAF964 orgchart employee fix

- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/templates/view_inbox.tpl
Included missing scripts in inbox page.  In addition to it missing the `gridInput.js` file, it was missing the `sensitiveIndicator.js` file, causing sensitive data to not toggle.
> LEAF979 grid input inbox fix

- servlets/digital-signing/build.gradle
- servlets/digital-signing/src/main/java/leaf/Application.java
- servlets/digital-signing/src/main/java/leaf/JsonSerializer.java
- servlets/digital-signing/src/main/java/leaf/SignEngine.java
Added closing quote to public key field for valid json response, syntax tested with jsonlint.com
Certificate is encoded as hex string in response.  Method verify() in SignEngine.java creates a certificate from that hex string and verifies the validity of the signature
> Fix bug with json response from websocket

- LEAF_Request_Portal/js/formPrint.js
Inner for-loop was using ```i``` as a variable when the outer for-loop was also using ```i```
> [LEAF-1051] Change variable name to fix variable reassignment

- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/sources/FormEditor.php
users should only be able to associate forms with their own workflows
> set up guardrails

- LEAF_Request_Portal/js/formPrint.js
**First case**
Create an indicator with multiple checkboxes. Set the options to:
```
Concur with decision.
Do not Concur with decision.
```
This should make the text overflow.
**Second case**
Create an indicator with a very long title and make sure the box lands at the bottom of a PDF page, so that it continues onto the next page. The title will repeat and should overflow. Set title to:
```
Travel to a particular site in order to perform operational or managerial activities. Travel to attend a meeting to discuss general agency operations, review status reports or discuss topics of general interest. Examples: Employee's day-to-day operational or managerial activities, as defined by the agency, to include, but not be limited to: hearings, site visit, information meeting, inspections, …
```
> Leaf1207 textwrap in pdf

- docker/docker-compose.yml
- docker/php/Dockerfile
- docker/php/ssmtp/ssmtp.conf
- test/LEAF_Request_Portal_Tests/tests/api/MailTest.php
LEAF-1301 Adding FakeSMTP to docker stack
Adds FakeSMTP and configures php for use.
FakeSMTP web portal: http://localhost:5080/email
user: tester
pass: tester
> LEAF-1301 Adding FakeSMTP to docker stack

- CODEOWNERS
CODEOWNERS file is used by github when Pull Requests are created to:
1) email owners with link to PR
2) automatically request reviewers
> Commiting CODEOWNERS file to repo

- Jenkinsfile.dev
- fort_report/FortifyReportGen.sh
LEAF-1571: merged fpr
Adding support for merging annotations during pipeline execution of fortify.
Fortify annnotations are a cumbersome process required by the developer to mark
findings that are in dispute, such as false findings.
Uploaded annotated FPR file to the pipeline bucket/annotated/ folder.
Ensure only a single FPR is in that directory, the pipeline script will use the first one found.
> LEAF-1571: merged fpr

- LEAF_Request_Portal/admin/css/mod_form.css
- LEAF_Request_Portal/admin/css/style.css
Testing discovered that long workflow titles go outside the borders of the form container. Added CSS props to hide overflow text in Form Editor homescreen.
- added props to .formPreviewWorkflow in mod_form.css
Before: 
After:
> Bugfix/LEAF-1633: Form Editor Workflow Titles Overflow Containers

- LEAF_Request_Portal/admin/templates/mod_system.tpl
The 'Start Certification Process' button and it's sibling were not working because they were put in button tags with an href. This PR puts them back as they currently exist in master branch.
> bugfix/LEAF-1763: Put Site Settings Buttons Back As Links

- LEAF_Request_Portal/admin/templates/view_form_library.tpl
The Forms Library page results container is being pushed below the left side nav because it does not have enough margin to clear the left menu. No screenshot because there is no form library data in local environment.
- Added margin to main left container so forms table is not pushed down.
> bugfix/LEAF-1758: LEAF Library Forms Table Pushed Below Left Nav

- LEAF_Request_Portal/admin/templates/menu.tpl
- Added email template editor link to global nav for Admin UI
- Tested locally and link is correct
> bugfix/LEAF-1762: Email Template Editor Link Missing from Admin UI Global Nav

- LEAF_Request_Portal/admin/templates/mod_templates.tpl
Restored misplace classes and IDs from older branch. Tested locally and buttons are behaving as expected.
No changes made yet:
Changes made:
> bugfix/LEAF-1786: Template Editor Save/Restore Original Button Behavior

- LEAF_Request_Portal/admin/index.php
**From Jira:**
- _Subordinate sites: Even though the form and workflow editor buttons don’t show up in the Admin Panel, users can still get to them via the Admin dropdown – Form Editor and Workflow Editor are still visible._
- _If the portal type is nationally standardized subordinate, workflow and form editor should not show up in the NAV menu_
- _For subordinate sites: The Form Editor and Workflow editor should not be visible in the admin panel and menu._
**AC:**
- _Workflow and Form editor should not show up in NAV menu if the portal type is set to " nationally standardized subordinate" under site settings_
- _Definition of done: Nationally standardized subordinate should not show Workflow and Form editor under NAV menu_
**In This PR:**
-  **Added 'siteType' variable to t_menu template …
> bugfix/LEAF-1809: Subordinate Sites - Editor Visibility

- LEAF_Request_Portal/templates/reports/LEAF_sitemaps_template.tpl
**Testers found:**
- Bug-When the user is in IE and clicks on the View Sitemap button, the expected behavior is another tab opens and the user can view the sitemap.  Nothing happens when the user clicks on this button.
- Potential issue-The order of the cards in the sitemaps template is not reflected in the sitemap when viewed.  Is this intended behavior? Cameron Chilton call me when you can so we can discuss.
**Fixes in PR:**
- Added save function to refreshButtons
- Changed 'View Sitemap' button to a tag so link works in IE11
> bugfix/LEAF-1795-2: Sitemap Fixes from Preprod Testing

- LEAF_Request_Portal/admin/templates/view_disabled_fields.tpl
Restore Fields table in IE11 preprod does not have text breaks, causing table data to stretch off to the right. 
PR change is css class of disabled field table so that content will wrap. 
_Tested in local VMbox IE11 and in local dev on developer's machine and testers._
**Before:**
**After:**
> bugfix/LEAF-1811: Fix Restore Fields Table Display Bug in IE

- LEAF_Request_Portal/admin/templates/mod_groups.tpl
- LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
- LEAF_Request_Portal/templates/email/LEAF_main_email_template.tpl
Default email template had unreadable line numbers because of overlap of content and line numbers. Added 2 line breaks to main email template to get around line number overlap.
**Before:**
**After:**
> bugfix/LEAF-1796: Email Template Editor Line Numbers Overlap

- gulpfile.js
Hotfix: The configuration of the gulpfile on LEAF was different from the version found on uswds github gulp repo.
- Update to gulpfile.js to match current config found on uswds gulp. 
- Removed autoPrefixerOptions and changed plugins config.
> hotfix/LEAF: Update gulpfile.js to Match Current Config Used in USWDS

- LEAF_Request_Portal/templates/reports/LEAF_sitemaps_template.tpl
**Previous solution to click/drag used ES2015 js code. New implementation using no ES2015.**
- Added edit links back to card titles
- Updated title/tooltip text to distinguish between edit link and click/drag cards
> hotfix/LEAF-1833: Sitemap Editor - Changed Implementation of Click/Drag for IE11

- docker/php/Dockerfile
LEAF-1802: Enable UTF-8 locale for LEAF pod
LEAF pod is currently unable to resolve filename characters that are encoded in UTF-8.
Such files have been saved to the ./UPLOADS directory as user provided strings. Users have
been able to upload files in UTF-8, however, system commands such as ls and cd have not been able
to decode the text names of these filenames.  This PR defaults the operating system environment
to en_US.UTF-8 to support these files.
Further testing will be needed to ensure files are accessible after this change is inplace, and that this change
is compatible with both how filenames are encoded in the database; currently both latin1_swedish_ci and utf8_general_ci.
Also resolves following errors from `aws s3 sync` commands:
> LEAF-1802: Enable UTF-8 locale for LEAF pod

- LEAF_Request_Portal/FormWorkflow.php
Fix for accessing workflow custom scripts by adding ```_``` to filename
> [Bugfix][LEAF-1876] make launchpad scripts work in stateless

- LEAF_Request_Portal/templates/print_form.tpl
Modifies client-code to contain trailing slash for endpoint /progress/
Eliminates 301 redirect sent under Stateless, reducing needless requests-response cycle from browser
> Modify updateProgress to contain trailing slash in stateless API

- docker/php/etc/www.conf
Bump FPM process limits and enable status page
Bumping FPM max children to 32 to resolve bad gateway errors
> Bump FPM process limits and enable status page

- error_404.php
IE11 is opening the new 404 page in Compatibility Mode which does not display the page's styling correctly. Added a meta tag to the page intended to force IE11 to display in the most up to date version of IE.
https://stackoverflow.com/questions/52775004/forcing-ies-compatibility-mode-off
> hotfix/LEAF-1930: IE11 Fix for Custom 404 Page

- LEAF_Request_Portal/templates/reports/LEAF_sitemaps_template.tpl
- libs/sass/0-leaf.scss
In addition to capping max URL length at 2048 characters , noticed that the move cursor was showing when viewing the sitemap.  Fixed the CSS to only show that during edit.
> Removing max length

- LEAF_Request_Portal/templates/subindicators.tpl
Removed the reopening of the Datepicker widget after the date is selected in IE by adding a hidden field to transfer focus to after date selected.
> LEAF-1486 - Removed Datepicker Reopening

- LEAF_Request_Portal/FormWorkflow.php
Determined in testing, not from the initial request, that when a step is rejected, the requestor and rejector, as well as their backups, should be notified.
> LEAF-1458 - Adding sendback email backups to list upon rejection

- LEAF_Request_Portal/form.php
This resolves an issue where users querying for non-empty strings incorrectly get empty strings as results.
> Remove condition when querying non-empty string

- LEAF_Request_Portal/js/parallelProcessing.js
Changed variable name back to indicatorObject, as it is used globally.
Might need an additional change if the response can also come back as an empty array.
> hotfix LEAF 2455: revert variable name

- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/js/form.js
- LEAF_Request_Portal/templates/print_form.tpl
Adding styling, and some JS, for Edit Form page view and edit form dialog box to sticky the progress / save / cancel menu. 
Also added some minor styling to fix current issues with content overflow.
> LEAF-2479 sticky menus, overflow fix

- LEAF_Request_Portal/templates/view_reports.tpl
Some fixes for report builder dropdowns.  Some selection field widths were inheriting the width of the currently selected item, making them difficult to read, and long fields were also restricting the widths of other fields.  Added a reasonable min-width for fields, and a width fix for the main box that will allow it to expand to accommodate longer items.
> LEAF 2468-css for report builder display

- LEAF_Request_Portal/js/formQuery.js
- LEAF_Request_Portal/templates/view_search.tpl
Usernames with apostrophes (') cause issues when the ' is turned into an
html entity, preventing search on userID field because the & symbol
would truncate the rest of the query in the URL.
> [NOT TESTED] Attempt to improve handling of usernames

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
When a workflow has multiple steps, each with a Form Field set, it generates multiple "workflowIndicator" IDs and prevents the UI from populating correctly.
This fix appends the stepID to avoid collisions.
> Resolve DOM ID collision issue

- LEAF_Request_Portal/form.php
This avoids ~5 queries for each unique employee since the full orgchart data isn't needed within this context.
> Reduce queries

- LEAF_Request_Portal/form.php
This introduces a parameter &debugQuery, which has the same effect as adding &debug to any form/query call, except it also shows information about the actual SQL query.
This simplifies debugging of form/query by returning EXPLAIN output. The EXPLAIN output is restricted to admins as it can contain information about of the size of the database. Non-admins will only be able to see the query and standard &debug output.
> Simplify query debugging process

- LEAF_Request_Portal/sources/Telemetry.php
Rewrite a method to accurately compute user uploads directory size.
A permissions modification is required to fully enable this feature. The following command must be run:
`chmod u+r vaccination_data_reporting/` to allow the script to read files in that directory.
> Rewrite method to compute user upload directory size using only PHP.

- LEAF_Nexus/sources/Employee.php
- LEAF_Nexus/sources/NationalEmployee.php
Fixes a condition that causes an orgchart employee search to fail if the username contains a space (rare circumstance).
> LEAF-2698 update logic to handle usernames with spaces

- LEAF_Request_Portal/Inbox.php
Adds a regexp to 'person designated' cases in Inbox.php so that non-numeric data will not be returned. 
Covers an edge case scenario where an indicator with prior format and data is updated to an orgchart format, and methods in the front end template cannot correctly handle the value.  In this case, user would see that there was a request, but not be able to expand/view it because the resulting error would break that functionality.  
These requests will still go to the inbox after this update, but they will have a blank table header.
> LEAF-2626 edge case inbox error fix

- LEAF_Request_Portal/scripts/updateServicesFromOrgChart.php
Changed the behavior of the 'Sync Services' button in the admin panel. It now syncs members of groups that are not marked as 'active'. Previously, it would ignore 'inactive' members of the group. The problem in ticket LEAF-2668 can now be resolved with the 'Sync Services' button.
> Group Backup Sync Fix

- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/report.php
- LEAF_Request_Portal/templates/menu.tpl
- LEAF_Request_Portal/templates/reports/LEAF_sitemaps_template.tpl
Updates to allow the non-admin menu to use the customized menu_links and menu_help templates.
Also includes a fix to the admin link in the sitemap section.
> LEAF-2783: menu_links, menu_help template customization

- LEAF_Request_Portal/Inbox.php
- LEAF_Request_Portal/api/controllers/InboxController.php
- LEAF_Request_Portal/templates/reports/LEAF_inbox_combined.tpl
This deprecates the /nonadmin endpoint. Using the masquerade modifier clarifies the intent of the request. This is left as a modifer since it communicates the the Login system: "I'm an admin and want to masquerade as a non-admin".
The /nonadmin endpoint should be removed in the future, after implementations to it are updated in prod. Implementations of need to be replaced with inbox/dependency/[text]?masquerade=nonAdmin
> Clarify API

- LEAF_Request_Portal/admin/templates/mod_form.tpl
Form Editor: 
Updates logic used to compare an edited indicator's selected format to account for indicators that have options (eg radio, dropdown, multiselect, grid, checkboxes).  Also updates strictness of comparison operators for other potentially edited fields.
> LEAF 2821 mod_form format change detection

- LEAF_Request_Portal/js/formPrint.js
If a form with 'checkboxes' format items is immediately viewed as a single page (without entering data / clicking next question), validation to enter the 'no' values does not run.  The respective 'checkboxes' input element's value is an empty string instead of an array, which in turn causes the code associated with the 'print to PDF' feature to error.
Adds an or operator to ensure that the returned value for checkboxes format questions is an array if there are unentered/unsaved data.
> LEAF 2879 handle empty unsaved 'checkboxes' values

- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/templates/initial_form.tpl
Adds a bottom margin to checkbox/radio containers, and hr elements between each form type listed on initial_form.tpl, to make selections more distinct for options with long titles and/or descriptions. 
Also adds additional css selectors to facilitate tab selection.
> LEAF-2919 improve initial form selection display

- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/js/formGrid.js
Wraps certain patterns of digits and slashes/dashes from Report Builder query results in quotes if they are not explicitly date format.  This prevents excel from interpreting these entries as dates and altering them.
> LEAF 2354 Wrap certain non-date format patterns in quotes

- LEAF_Request_Portal/admin/templates/mod_system.tpl
This patch resolves an issue where async POST calls are not consistently executing because the "Save" button has an undefined HTML button type. This also addresses a UX issue to improve visibility of the in-progress save action.
> Prevent race condition

- LEAF_Request_Portal/js/formSearch.js
Quick fix to give multiselect format questions CONTAINS/DOES NOT CONTAIN (LIKE) operators for searches
> LEAF 2896 move multiselect format queries to default case

- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/js/formGrid.js
Adds the 'data-format' data property to report builder table cells.
A format check is now used in combination with a date-pattern regex so that date format questions are not affected by an earlier changed intended to prevent Excel from auto-formatting non-date input as dates.
> LEAF 2971 Report Builder exports: implement format check

- .gitignore
Development related update to .gitignore
Excludes custom_override template files.
Also excludes files in the request_portal/templates/reports or request_portal/files directories if they contain 'custom_dev'.
> LEAF 2963 gitignore update

- LEAF_Request_Portal/js/form.js
- LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
Resolves display and behavior issues that occur if a condition's prefill value, or its parent trigger options contain encoded characters (eg, quotes, apostrophes, &).
> LEAF 3004, IFTHEN: handle conditions with encoded characters

- LEAF_Request_Portal/form.php
This resolves a type mismatch issue when the sanitization function (within subindicators template) expects a string, but an object is provided via unserialize().
Data is only unserialized in supported formats: "grid", "checkboxes", and "multiselect".
@pete-nerantzinis @aerinkayne
> Selectively unserialize data based on format

- LEAF_Request_Portal/form.php
This resolves an issue where valid queries would return false instead of an empty array.
This function should only return a non-array (false or error message) if the request is malformed.
> Return false only on malformed requests

- LEAF_Request_Portal/form.php
Added try catch for the the array merges, This does not fix the errors just makes them act more like php 7 but also lets us know they are still happening. If I understand the code, this probably could be permanently fixed for two instances where it looks for default data, if there is no default message we do not merge the data.
> Add in try catch for array merge

- LEAF_Request_Portal/js/workflow.js
This provides better support for customization of the workflow UI, particularly with visibility of buttons. Adding a return here provides access to the JS Promise interface, enabling reliable transformations.
Example use:
```js
let workflow = new LeafWorkflow('workflowContainer', '_CSRFTOKEN_');
workflow.getWorkflow(1234).then(function() {
// custom transformations
});
```
> Enable post-render customizations

- LEAF_Request_Portal/admin/Group.php
On sites with large numbers of groups and members, it takes too long to open the User Access Groups page.
Part of the reason for this seems to be that api/group/members is returning redundant data: it returns a list of all groups + all members + **all groups for each member**.
Since "all groups for each member" can be derived from all groups + all members, this patch removes the redundancy.
> Speed up admin/?a=mod_groups page load

- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/templates/view_reports.tpl
This splits large queries into smaller pieces, which significantly reduces working-set memory usage.
1. Loads large datasets in groups of 1,000 requests
2. Adds a counter and stop button when loading large sets
3. Reduce data transfer by 40-70% by filtering out unused data
4. Remove some IE9 workarounds
> LEAF-3098 Report builder optimization

- LEAF_Request_Portal/templates/view_reports.tpl
This reincorporates a timestamp that was mistakenly left out of the previous hotfix.
> LEAF-3103: Hotfix: Left out timestamp

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
This resolves an issue where the API returns ints but was being compared as strings, causing comparisons to fail.
> These need to be ints

- LEAF_Request_Portal/js/formQuery.js
This reduces data transfer when a cached result can be used, improving UX on slow connections.
Tested with Edge/Chrome/Safari in a prod sandbox, and Firefox in dev
> LEAF-3100 Remove client-side cache workaround

- LEAF_Request_Portal/templates/subindicators.tpl
This resolves an issue where the negative symbol in an indicatorID conflicts with JS variable naming standards.
> fix negative indicatorID conflict

- LEAF_Request_Portal/form.php
Corrects an error that occurs if the total number of required questions on a form is reduced to zero when accounting for conditional display states.
> LEAF 3238 add check if total was reduced to zero

- LEAF_Request_Portal/FormWorkflow.php
- LEAF_Request_Portal/js/workflow.js
Previously, for a non-admin if you were to go to the request page to view a request and the dependencyID was a -1 or -3 the title on the page would say Pending action from null. Now, when you go to this page you will see the stepTitle which matches the home page status column.
> LEAF-3199 clearer next step

- LEAF_Request_Portal/form.php
Came in via a snow ticket, this is where filenames with & would not delete since on the file system and in the database they would be encoded however when they would be indexed for deletion that check had the files decoded. Since &amp; does not equal & it would not delete.
> LEAF-3330 - Filenames with & would not delete

- LEAF_Request_Portal/templates/subindicators.tpl
This is an attempt to re-merge[ PR#1713](https://github.com/department-of-veterans-affairs/LEAF/pull/1713), which didn't make it into prod.
This implements JS promises in orgchart_* widgets, intended to be used within customizations. Promises must be used since the widget can potentially load asynchronously.
Example to disable the standard orgchart_group widget:
```js
let fieldID = 5;
leaf_groupSelector[fieldID].then(grpSel => {
grpSel.disableSearch();
});
```
> LEAF-3231 Update orgchart_* widget customization

- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
When selecting the Email Template Editor in the admin section, at the bottom of the page there's a dialog box.
With this fix, the dialog is no longer displayed.
https://localhost/LEAF_Request_Portal/admin/?a=mod_templates_email
> Bug / LEAF-3334 / Dialog Box being displayed at bottom of page

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Hotfix/leaf 3308/email notification icon missing
Missing Icon
> LEAF-3308 - Missing icon on step when email notification is enabled.

- LEAF_Request_Portal/templates/form.tpl
Adds a call to window.scrollTo after the progress check (form entry page only) to ensure that it is at the top.
Also focuses the top next question button if the form had been progressed through the prev or next buttons (does not affect the form nav menu), so that the tab focus also will be at the beginning of form entry.
> LEAF 3350  form entry scroll behavior

- LEAF_Request_Portal/FormWorkflow.php
- LEAF_Request_Portal/admin/index.php
This addresses an issue that can affect the 'hasAccess' value for users who are members of more than one ELT group, and prevent the action buttons from appearing during the request workflow.  This also resolves an error caused by a return value data type
> LEAF 3392 ELT access issue

- LEAF_Request_Portal/FormWorkflow.php
This mitigates an issue within FormWorkflow.php -> handleAction() where the following conditions exist:
1. The filled status within the records_dependency table is not written correctly due to an aborted request
2. The workflow contains two sequential steps that utilize the same dependencyID
Solving # 1 would also resolve the problem, however it's riskier due to its complexity and therefore not suited within a hotfix.
To reproduce the problem:
1. Create a workflow: Start -> Step A -> Step B -> End
2. Start a request and advance the workflow to Step B
3. Edit the database: records_dependency, and set filled = 1 for the respective request ID. This simulates the server interruption.
4. When viewing the request, note that the workflow does not show any action buttons
> Mitigate issue when "filled" status isn't updated

- LEAF_Request_Portal/admin/templates/mod_form.tpl
This should resolve formatting issues that can occur on the indicator privileges modal if the indicator name contains quotes or apostrophes.
> LEAF 3336 escape quotes and apos in indicator names

- LEAF_Request_Portal/admin/templates/print_subindicators.tpl
- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/js/form.js
- LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
- LEAF_Request_Portal/templates/print_form.tpl
Adds checkboxes as both a parent and child format to the conditions editor.
Also reworked some of the comparison logic that occurs on the form data entry page to make it easier to follow, and added styles for checkboxes and radio buttons that have the disabled attribute.
> LEAF 3217 checkboxes format for IFTHEN

- LEAF_Request_Portal/form.php
Updates the code so that **only** checkbox and checkboxes format questions will trigger the behavior intended to handle the situation described below.  Single text and textarea formats had incorrectly been triggering this behavior, causing entries that consisted solely of 'no' to not be counted towards the total of answered required question.
--
Checkbox and Checkboxes formats save the value 'no' if their corresponding input is not checked. 
Introducing checkboxes for if then creates the scenario where a required question could be hidden.  In this case, it is treated as not required by the front interface and allows the user to save, resulting in these 'no' values being stored in the data field.
Previously, questions were counted as answered in form->getProgress if the corresponding data …
> LEAF 3421 update specificity when looking for 'no' values

- LEAF_Request_Portal/form.php
This missing groupID prevents the following access check from working correctly.
```js
if (isset($line['groupID']))
```
> LEAF-3420 Add missing groupID

- LEAF_Request_Portal/templates/view_reports.tpl
This resolves an issue when custom queries are imported into the Report Builder.
To replicate this:
Add the following script as a new page in LEAF Programmer.
```js
<script>
let today = new Date();
today.setDate(today.getDate() - 30);
let query = new LeafFormQuery();
query.addTerm('deleted', '=', 0);
query.setLimit(10);
query.addTerm('dateSubmitted', '>=', `${today.getMonth() + 1}/${today.getDate()}/${today.getFullYear()}`);
let indicators = [
{indicatorID: 1, name: 'Col 1'},
{indicatorID: 2, name: 'Col 2'},
];
let exportQuery = LZString.compressToBase64(JSON.stringify(query.getQuery()));
let exportIndicators = LZString.compressToBase64(JSON.stringify(indicators));
window.location.href = `index.php?a=reports&v=3&query=${exportQuery}&indicators=${exportIndicators}`;
</script>
```
Prior to …
> Leaf 3437 - Replace arbitrary pop()

- LEAF_Request_Portal/FormWorkflow.php
- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/js/formSearch.js
The new "actionable" query parameter identifies records that the current user has pending workflow actions. This inherits features from api/form/query and will be used as part of a performant Inbox.
Testing:
- Workflow access types: admin/non-admin/groups/designated person/designated group/requestor followup
- The workflow action box should have the same behavior as before
- Report Builder: setting "Current Status IS Actionable by me" should only show records that the current user has pending actions for
- Report Builder: setting "Current Status IS NOT Actionable by me" should only show resolved requests
> Leaf 3431 - New query parameter: Actionable

- LEAF_Request_Portal/FormWorkflow.php
Fixes two issues:
1. Admins can't see the actual name of the person or group in the workflow action area's header.
2. Resolves issue related to wrong type when a group has been deleted, but the group has previously been assigned in the workflow
3.
> Leaf 3463 - Restore supplemental orgchart info

- LEAF_Request_Portal/admin/css/style.css
- LEAF_Request_Portal/admin/templates/form_editor_vue.tpl
- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Adds a banner warning users against making modifications, to the top of the Form Editor, Form Editor Refresh, and Workflow Editor views if these areas are accessed on a subordinate site.
> LEAF 2459 add warning to subordinate sites

- LEAF_Request_Portal/scripts/automated_email.php
Nationals do not normally use services. Add in flexibility to allow for services to exist or not.
Local replication, take a request that is currently on the step that an email reminder would go out. In the database remove the service (set it to 0 which is how nationals work). Then run the email reminder script from with in the scripts folder.
I would also suggest we get a demo national and a demo vax portal for us to specifically test.
> LEAF-3424 - Email Reminders not working on National sites

- LEAF_Request_Portal/sources/Shortener.php
This avoids having to lookup the database manually when investigating shortened URLs provided via Report Builder -> JSON.
Add "?debug" at the end of the URL to get the original query terms.
> Leaf 3478 - Simplify debugging

- LEAF_Request_Portal/js/form.js
- LEAF_Request_Portal/js/workflow.js
- LEAF_Request_Portal/scripts/workflowStepModules/LEAF_workflow_indicator.tpl
- LEAF_Request_Portal/scripts/workflowStepModules/TEMPLATE_workflowStepModule.tpl
This enables pages such as the Combined Inbox to work correctly.
Preconditions:
- Two LEAF sites A and B
- [Combined Inbox](https://github.com/department-of-veterans-affairs/LEAF/blob/combined_inbox_v3/LEAF_Request_Portal/templates/reports/LEAF_inbox_combined_sort_type.tpl) saved on site A, and configured to import data from B
- Site B has a workflow containing a Step with a Form Field configured
- A request on Site B is on the Step with a Form Field
Before this patch: The form field does not load correctly in the Combined Inbox
After: It works
> Leaf 3480 - Improve compatibility for multi-site interactivity

- LEAF_Request_Portal/js/formSearch.js
In certain customized dropdown/radio fields, the <select> list is populated dynamically. Therefore when searching within these data fields, it's impossible to find these in the dropdown list.
To simplify testing, it's sufficient to show this is true:
Before: Searches within dropdown/radio fields can only be made on exact matches or comparisons
After: Searches for partial "CONTAINS" or "DOES NOT CONTAIN" matches are possible
> Leaf 3481 - Enable "contains" condition for dropdown/radio searches

- LEAF_Request_Portal/js/formSearch.js
There's a potential race condition that triggers an error: "currRequest.abort is not a function", which prevents people from searching on the homepage.
This might be happening because the underlying $.ajax() call is resolving before this timer loop expects it.
This workaround checks to see if currRequest.abort is a valid function before trying to execute it.
> LEAF-3519 - Workaround race condition

- LEAF_Request_Portal/js/formGrid.js
Fix issue when the table on the main page is cleared after attempting to sort one of the columns.
> Clear render history when tbody is emptied

- LEAF_Request_Portal/admin/templates/mod_file_manager.tpl
- LEAF_Request_Portal/api/controllers/SystemController.php
Updates the registered deletion endpoint used in the file manager to take the file name as a parameter rather than through the url, which had caused some file names (eg test#file) to be undeletable through the UI.
> LEAF 3398 file del endpoint update

- LEAF_Request_Portal/form.php
This optimizes a hot spot that was flagged in monitoring.
Testing preconditions:
- A request is on a step that's configured with "person designated by requestor"
- The current user is not the person designated
- The current user is a backup of the person designated
- The current user is not an admin
Testing checklist:
> LEAF-3517 - Avoid redundant queries

- LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
- LEAF_Request_Portal/js/formGrid.js
- LEAF_Request_Portal/templates/view_reports.tpl
This primarily adds a feature to save sort preferences in the report builder.
Other fixes and changes:
- Resolve shortlink issue if the base64 encoded URL included a slash (/)
- Fix reversed sort indicator issue
- Use Intl.Collator for most sort operations
- Add sort callback to formGrid.js
- Adjust label editor UX
- Optimization: Replace $.each with forEach in hotspots
Testing checklist:
> LEAF-3516 - Report builder sort persistence

- LEAF_Nexus/api/RESTfulResponse.php
- LEAF_Request_Portal/api/RESTfulResponse.php
This adds missing double quotes defined in RFC9110 and summarized in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
> LEAF- 3534 - Align with HTTP specification for etags

- LEAF_Request_Portal/Login.php
- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/scripts/automated_email.php
- LEAF_Request_Portal/sources/Workflow.php
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023012400-2023012600.sql
- scripts/scheduled-task-commands/automatedEmailReminder.php
This required me to re-pr the changes since not everything pulled in. For reference: https://github.com/department-of-veterans-affairs/LEAF/pull/1830
Notes from previous pr:
I have adjusted the previous testing methodologies from just sending the current information to augmenting the number of days to number of minutes. So for example initial email can go out in 1 day and every other notification will be 2 days. These numbers will then become 1 minute and 2 minutes when using the url below.
https://localhost/LEAF_Request_Portal/scripts/automated_email.php?minutes=minutes
Some talking points for this would be the wording on the popup when choosing the additional notifications.
> LEAF-3346 - automated emails iteration after the first email

- LEAF_Request_Portal/templates/view_reports.tpl
Resolves an issue where Report Builder output gets mangled in these conditions:
- Report Builder must have a "Current Status IS Cancelled" term
- "Date Request Cancelled" is selected in Step 2
- Attempt to sort on any column
> LEAF-3547 Fix Report Builder: Date Cancelled

- LEAF_Nexus/scripts/refreshOrgchartEmployees.php
missing the org employee empuid line, adding this back in restores the import functionality.
> LEAF-3615 - refresh orgchart employees script

- LEAF_Request_Portal/api/RESTfulResponse.php
- LEAF_Request_Portal/sources/Shortener.php
- LEAF_Request_Portal/templates/view_reports.tpl
Adds decode for the Report Builder -> JSON (toolbar option) -> JSON option, use compat mode checked, endpoint to avoid encoded characters in excel 'from web' imports.
> LEAF 3411 add decode for excel 'from web' import

- LEAF_Request_Portal/api/controllers/ServiceController.php
- LEAF_Request_Portal/api/index.php
When copying a request, services were not showing when a user was not an admin, this was due to the services call being an admin only call. I did not see any reason for this since none of the other sections working with services in this way needed to be admin only.
> LEAF-3568 - Copy request_service does not show on non admin

- LEAF_Request_Portal/templates/subindicators.tpl
Adjusts the aria attribute on grid format questions so that it refers back to the element containing the question's name, rather than directly to the name value, where the value was being interpreted as html in some circumstances. 
Also corrects the format value for no-format questions to an empty string. 
edit:  format is empty string, but this did not cause further formatting issues, so this update will only correct the duplication issue in grid questions
> LEAF 3501 duplicate text issue and 'no format' text formatting

- LEAF_Request_Portal/scripts/automated_email.php
- LEAF_Request_Portal/templates/email/LEAF_automated_reminder_body.tpl
This is the change that was brought up in the CoP where end users wanted to see the actual number of days since the last activity in the email. For testing  this is standard automated email sending it will now just have the extra text for number of days since last action.
> LEAF-3606 - automated email days ticket has been open

- LEAF_Request_Portal/js/formGrid.js
Workaround code for IE was making certain reports not work because of certain edge cases reported in helpdesk ticket.
> LEAF-3607: Removed IE Workaround

- libs/js/LEAF/formSearch.js
This change will validate the gate parameter in newSearchWidget. Requested by the fortify team.
> LEAF 3618 - Update formSearch.js validation - Fortify

- LEAF_Nexus/utils/jsonExport_PDL.php
the htmlspecialchars function is used to escape any special characters that might be included in the JSON output. The ENT_QUOTES flag is used to escape both single and double quotes, and the UTF-8 charset is used to encode the output. Finally, the JSON is outputted using the echo statement. This was requested by the fortify team.
> LEAF 3617 - Update jsonExport_PDL.php - Fortify

- LEAF_Request_Portal/templates/print_form.tpl
Reworks the logic for copying file upload formats to confirm that the value is an array prior to proceeding with array methods.
Value is an empty string on an original (non-copied) form if no files have ever been attached because there is no data table entry. 
Associated with yourIT INC26366962
> LEAF-3596 file upload copy error

- LEAF_Request_Portal/templates/reports/LEAF_inbox_combined.tpl
Per feedback from MGao during Open Office, this retains the default light gray between request items and re-adds the bottom border.
> LEAF-3672 keep default bg color btw requests

- LEAF_Request_Portal/sources/Form.php
Signature were being added to the db when they shouldn't have been. This just comments the code to make sure it does not.
> Leaf 3611 digital signature v2

- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/js/form.js
- LEAF_Request_Portal/js/gridInput.js
- LEAF_Request_Portal/templates/subindicators.tpl
Adds the cell type 'dropdown from file' for grid format questions..  This allows options for the dropdown to be loaded from a file manager text file.
Other: Fixes an issue that caused quotes to break dropdown options for grid format questions, and adds 'Select an Option' as an initial dropdown text prompt.
> LEAF 3635 grid format - load options from file celltype

- libs/js/LEAF/intervalQueue.js
This resolves an issue where intervalQueue incorrectly clears out arrays provided through setQueue().
To reproduce the issue, copy and run this in LEAF Programmer:
```js
<script src="../libs/js/LEAF/intervalQueue.js"></script>
<script>
let list = [1,2,3,4,5];
let queue = new intervalQueue();
queue.setQueue(list);
queue.setWorker(item => {
return new Promise(resolve => resolve());
});
queue.start().then(() => {
console.log(list);
});
</script>
```
Prior to this patch, the output in the console would be an empty array.
After this patch, it correctly shows: Array(5) [ 1, 2, 3, 4, 5 ]
> LEAF-3629: intervalQueue setQueue() should create a copy of the array

- LEAF_Request_Portal/scripts/events/TEMPLATE_CustomEvent_YOUR_ID.php
- LEAF_Request_Portal/sources/Form.php
This removes the email sent from the comments section on the request page, and also removes them from the comments section in report builder. All per Michael Gao.
> Hotfix Leaf 3757 email tracker not in comments

- LEAF_Request_Portal/js/formSearch.js
Changes the path to the jQuery plugin referenced in portal/formSearch.js back to what it was prior to autoloader.
Another longer term solution might be needed, but this will fix the current error that is making the search on the homepage unusable for the 'date submitted' type selection.
> LEAF 3775 fix path to datepicker plugin

- libs/loaders/Leaf_autoloader.php
Description
Email class is calling on DbConfig class to instantiate and send emails.
DbConfig no longer exists
Email class is failing when calling DbConfig class
Currently old portals still have the DbConfig class so the Email class works properly
New portals as of 6/8 do not have the DbConfig class so it's possible their Email class does not work
> LEAF-3790: Email Class not Working on New Portals

- LEAF_Request_Portal/admin/css/style.css
- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/admin/templates/mod_file_manager.tpl
Adds a table in the file manager to display information about files used to load active indicator options.  This includes which forms and indicators they are used for.
> LEAF 3732 Add File Manager Form Info

- LEAF_Request_Portal/js/formGrid.js
This allows custom implementations to use a hash in place of a recordID.
Currently used in a Nationally Standardized Report Builder prototype.
Testing:
- LEAF Tables (Report Builder, Main Page, etc) should function the same as before
> LEAF 3804 - allow custom hashes as recordID

- LEAF_Nexus/sources/Group.php
It was found that queries for orgchart groups can return non-unique results in some circumstances (<=10 records retrieved and value of the group abbreviation field).  This update replaces an array merge with a loop so that the groupIDs of the additional records can be confirmed to be new before adding them to the results list.
> LEAF 3803 fix group search non-unique results

- LEAF_Request_Portal/admin/templates/menu.tpl
- LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
- Added "Get Help" in the Admin Panel and Admin Header Menu
- Removed alt tags for decorative icons
Testing:
- The "Get Help" button links to a site in the prod environment, and opens it in a new window
> LEAF-3837: Add "get help" button and remove unnecessary alt tags

- LEAF_Request_Portal/templates/view_reports.tpl
Prevent an error by checking to make sure the array has a > 0 length before accessing it in the following assignment on line 295:
```js
let lastAction = recordBlob.action_history[lastActionRecord];
```
If recordBlob.action_history was empty, lastActionRecord would be an invalid reference.
> LEAF-3827: Check array length before accessing

- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/templates/print_form.tpl
Adds the ability for backups to submit requests (for example if they have been returned to requestor).
This also fixes an error that occurred if a (non-admin) backup tried to re-submit a request and normalizes the Form.php  doSubmit method return values.  Custom code can use this endpoint, so I otherwise retained the return value array format used for this method.
> LEAF 3830 - backup submit errors and behavior

- LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
Adds a method to the Conditions Editor on the old interface to update the ifthen icon tooltips to reflect whether questions have conditions added to them.
> LEAF 3808 - ifthen tooltip updater for old interface

- LEAF_Request_Portal/templates/view_reports.tpl
1. Start a new request and submit it
2. Report Builder: set filter to "Current Status IS NOT Resolved", Click next
3. Select "Days since last action"
5. Note the request from step 1 shows up as "Not Submitted" in the "Days since last action" column
> Leaf 3887 - fix incorrect indicator

- LEAF_Request_Portal/admin/templates/mod_form.tpl
Updates the comparisons used to detect changes for some form and indicator properties.
Adds the default values for form sort, visibility and needToKnow to the local object after new form creation.
Adds the ajax call to set form visibility to the promise all array to avoid an async issue.
> LEAF 3863 form and indicator change detection

- LEAF_Request_Portal/sources/Email.php
This resolves an error when this function returns null, but the return type is declared as a bool.
> LEAF-3842: Initialize Return Variable

- docs/Development.md
I noticed there were a few header typos in the **Development.md** markdown, so I went ahead and corrected those. 
On branch master
Changes to be committed:
modified:   docs/Development.md
> Fix small markdown typo in docs/Development.md for sub headers

- LEAF_Nexus/api/controllers/EmployeeController.php
- LEAF_Nexus/templates/view_employee.tpl
empUID is passed into the API, but it's not used in the associated PHP function: https://github.com/department-of-veterans-affairs/LEAF/blob/master/LEAF_Nexus/sources/Employee.php#L87
```php
public function refresh(string $user_name): array
```
> Leaf 3891 - Remove unused empUID argument

- LEAF_Nexus/sources/Employee.php
There's a missing index in Nexus :: employee, where indicatorID + data. However implementing this would benefit from further discussion/analysis.
This temporarily disables the "deep" employee search feature to mitigate the performance impact.
> Temporarily disable deep search

- LEAF_Request_Portal/sources/Form.php
Resolves API consistency error where the parentID of a field was missing if the field has child fields.
> Add missing parentID

- LEAF_Nexus/sources/Login.php
- LEAF_Request_Portal/sources/Login.php
This is intended to resolve an issue where signing out does not clear out all cookies.
Testing procedure, might need to be done on pre-prod instead of dev:
1. Open the LEAF homepage
2. Open the browser's devtools, navigate to Application -> Cookies
3. Note that PHPSESSID and REMOTE_USER cookies exist
4. Click "Sign out" on the LEAF homepage
5. Confirm that the PHPSESSID and REMOTE_USER cookies have been deleted
6. Close the browser
7. Go back to the LEAF homepage, it should load normally
> LEAF-3937: Attempt to clear cookies and fix sessions

- LEAF_Nexus/sources/Employee.php
- LEAF_Nexus/sources/Tag.php
- LEAF_Request_Portal/admin/ajaxIndex.php
- LEAF_Request_Portal/admin/templates/mod_groups.tpl
- LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
- LEAF_Request_Portal/api/controllers/GroupController.php
- LEAF_Request_Portal/api/controllers/ServiceController.php
- LEAF_Request_Portal/api/controllers/SystemController.php
- LEAF_Request_Portal/scripts/sync_services.php
- LEAF_Request_Portal/sources/Group.php
- LEAF_Request_Portal/sources/Service.php
- LEAF_Request_Portal/sources/System.php
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023072000-2023082400.sql
- libs/logger/DataActionLogger.php
- libs/logger/formatters/ServiceChiefFormatter.php
This started out as a revamp of services but because of found bugs it became a revamp of services and update of user groups.
This will require a db update, I would recommend keeping a copy of the db as it is before testing this so that you can go back to that db if you need to work on something else.
For testing it is important to check both sides, Portal and Nexus. When a change happens on the Nexus side it should be reflected on the portal upon a sync services or closing out of the group modal. Also, multiple backups should be checked along with mutual backups of people.
I think the biggest part of testing is going to be emails. Making sure that the correct people get the emails and such.
I also updated the inactive user section for both user and services. You are only allowed to prune …
> Leaf 3902 - Update groups, service and user

- LEAF_Request_Portal/sources/FormWorkflow.php
Notify the requestor events have been getting the logged in user ID rather than the request initiator ID.
This had caused the backups of the last action-taker to get emails intended for the backups of request initiators.
> LEAF 3947 fix incorrect backups notification

- LEAF_Request_Portal/ajaxIndex.php
- LEAF_Request_Portal/api/controllers/FormController.php
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/templates/form.tpl
- LEAF_Request_Portal/templates/print_form.tpl
There is now a textarea in the cancel dialog box for a user to enter a comment if they want. Saves it to view history.
> Leaf 2784 - comments on cancel

- LEAF_Request_Portal/js/formSearch.js
- LEAF_Request_Portal/templates/view_reports.tpl
This improves load time in two key areas:
1. Homepage -> (Search) Advanced Options -> Select "Data Field"
2. Creating a new report in the Report Builder
Observed ~50% improvement on larger sites. The x-filterData parameter is used to limit data transfer to the requested content.
This also disables jQuery's cache-busting workaround. It's redundant because the cache behavior for API responses on Prod is configured correctly.
Testing:
- Report Builder should function normally
- Advanced Searches on the homepage should function normally
> LEAF-3949 Only load relevant data

- LEAF_Nexus/api/RESTfulResponse.php
- LEAF_Request_Portal/admin/templates/mod_system.tpl
- LEAF_Request_Portal/api/RESTfulResponse.php
- LEAF_Request_Portal/api/controllers/SystemController.php
- LEAF_Request_Portal/js/LeafSecureReviewDialog.js
- LEAF_Request_Portal/sources/System.php
- LEAF_Request_Portal/templates/form.tpl
- LEAF_Request_Portal/templates/reports/LEAF_start_leaf_secure_certification.tpl
This helps Admins avoid taking actions on records that are not explicitly assigned to them, by displaying the review screen in a non-admin context.
This also resolves an issue where an approved and then deleted "LEAF Secure" record would appear to remain certified, but would navigate to a broken link.
Testing:
> LEAF-3950 LEAF-S and Admin user flow update

- LEAF_Nexus/sources/Group.php
This changes the query to perform a right join rather than a left join getting only groups that actually exist.  This exists because a tag was added to a group and then the group was subsequently removed but the tag was left. So when getting the tags from Nexus it used to get all the tags even though the group no longer exists. By changing this to right join we only get the valid groups, or groups that exist in the groups table.
> Leaf 3973 hotfix sync services

- LEAF_Request_Portal/js/formQuery.js
This helps avoid conflicting with the new upcoming behavior in LEAF-3427 (large queries).
Prior to this change, a custom implementation of formQuery.js could request 1001 rows, trigger the new LEAF-3427 behavior, and appear to return no data.
After this change, customizations can request 1001 rows and return normally.
> LEAF-3979 - Compatibility for upcoming large query handler

- LEAF_Request_Portal/scripts/events/CustomEvent_LeafSecure_DeveloperConsole.php
- LEAF_Request_Portal/sources/Email.php
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/sources/FormWorkflow.php
- LEAF_Request_Portal/sources/Group.php
- LEAF_Request_Portal/sources/Service.php
- LEAF_Request_Portal/sources/System.php
- LEAF_Request_Portal/sources/VAMC_Directory.php
The autoloader creates more database connections than it needs to. When accessing ./api/form/version, this PR reduces the number of connections opened by 20%.
Original:
- new \Leaf\Db(\DIRECTORY_HOST, \DIRECTORY_USER, \DIRECTORY_PASS, \ORGCHART_DB);
Replacement:
- OC_DB;
Are these equivalent? Seems so:
1. OC_DB is defined globally here: https://github.com/department-of-veterans-affairs/LEAF/blob/autoloader-db-optimization/libs/loaders/Leaf_autoloader.php#L127
2. ... by using $oc_db defined here: https://github.com/department-of-veterans-affairs/LEAF/blob/autoloader-db-optimization/libs/loaders/Leaf_autoloader.php#L55 
3. ... which references $site_paths['orgchart_database']. This is the only difference compared to the Original DB connection, and...
4. ... ORGCHART_DB is actually assigned …
> LEAF-3978 - Optimize autoloader DB connections

- libs/jsapi/nexus/LEAFNexusAPI.js
Create an xlsx document with 2 columns one with text and one with an email address. Upload the file to LEAF_import_data. you may need to create a form for this. Ticket has a bit more information on what the error looks like. In the console you will see "controller not found" for the api calls due to the malformed url caused by the ? instead of &
> LEAF-3977 - org chart employee field in import data error

- LEAF_Request_Portal/js/formQuery.js
This improves the ergonomics of formQuery.js -> getData() when many indicatorIDs need to be referenced. The change is backward compatible.
Before:
```js
query.getData(1);
query.getData(2);
query.getData(3);
```
After:
```js
query.getData([1, 2, 3]);
```
> LEAF-3998 - Improve ergonomics of getData() when using many indicators 

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
This updates an error where an event tied to the submit of a workflow caused an error to occur when duplicating it.
the commented out new code was what I came up with to begin with, I followed up with what is here now. If what is here now looks good I will remove the commented section.
> Hotfix update

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023082401-2023091100.sql
This is a prerequisite for an upcoming change to mitigate certain worst-case response time scenarios when users run broad searches.
The "CONTAINS" comparator is the default when users run a broad search such as "any data field contains...". It takes about 20-30 seconds for the DB to respond when there's ~16M rows in the "data" table.
The 20-30s query looks like:
```sql
SELECT * FROM records
LEFT JOIN services USING (serviceID) LEFT JOIN (SELECT * FROM records_workflow_state) lj_status USING (recordID)
LEFT JOIN (SELECT stepID, stepTitle FROM workflow_steps) lj_steps ON (lj_status.stepID = lj_steps.stepID)
LEFT JOIN (SELECT recordID, indicatorID, series, data FROM data) lj_data ON (lj_data.recordID = records.recordID)
INNER JOIN (SELECT indicatorID, format FROM indicators 
WHERE format != …
```
> LEAF-4007 - Prepare for fulltext search feature

- libs/php-commons/Setting.php
This reverted a change that should not have been made. I double checked all the other classes to make sure something similar did not happen to them as well.
> Leaf 4002.2 - making backward compatible

- LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
Removes custom batching from timeline explorer query to avoid potential infinite loop.
Adds a check for the version property.
Adjusts some spacing.
> LEAF 4038 timeline explorer infinite loop

- LEAF_Nexus/sources/Position.php
- LEAF_Request_Portal/sources/FormWorkflow.php
This resolves a couple data type issues that result in fatal errors.
1. Uncaught TypeError: count(): Argument #***** ($value) must be of type Countable|array in orgchart/sources/Position.php:293
2. Uncaught TypeError: Portal\FormWorkflow::handleAction(): Argument #***** ($comment) must be of type string, null given in sources/FormWorkflow.php:667
- The comment is supposed to be optional, based on the original handleAction() definition.
1. No known negative impacts
- [URL_TO_NEXUS]?a=view_position&positionID=1 should have the same output as before
- Automated API test case: it should be possible to execute an action with no comment provided to the server (./portal/api/formWorkflow/[digit]/apply)
> Leaf 4037 - Resolve data type issues

- LEAF_Request_Portal/templates/email/LEAF_notify_next_body.tpl
- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This improves Inbox UX when sitemaps are configured with LEAF URLs that link to specific pages, instead of a typical homepage. 
Other minor changes:
- Wording change that clarifies a status message
- Email template change that updates the URL to the new Inbox
The sitemap URL list is parsed to obtain base URLs and removes duplicates.
- No other dependencies
Multiple URLs:
1. Configure a sitemap with multiple identical LEAF URLs
2. When viewing the Inbox, there should be fewer duplicates compared to the previous version
Specific pages:
1. Configure a sitemap that contains links to the Admin area or reports
2. When viewing the Inbox, there should not be a warning on the top of the screen: "Not all records have been loaded"
> Leaf 4027 - Inbox v2 UX update

- LEAF_Request_Portal/sources/Email.php
This resolves a performance issue due to an unindexed query. However instead of adding an index, this drops the query entirely because it's not necessary to check for an active email address. If the email is inactive, it would be the responsibility of the administrator to update any groups associated with the inactive email. It's important for the admin to take action, as this helps avoid stagnation. The related function definition has also been updated to account for the query removal.
This also works around a minor issue where $fields is uninitialized.
- Changes how email recipient assignments work
- End-users might see inactive emails in the recipient list. Need to communicate that this is expected, and admins should update groups.
- Emails are sent to their intended recipient
> Leaf 4031 - Optimize email hotspot

- LEAF_Request_Portal/scripts/updateDatabase.php
This just adds the Portal Path to the log file when doing a db update. This will help to know which db's got updated and which failed.
> Leaf 4043 - more info in dbupdate log

- LEAF_Nexus/sources/Employee.php
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/sources/FormWorkflow.php
- LEAF_Request_Portal/sources/VAMC_Directory.php
- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023999999-2023092100.sql
This optimizes form/query performance when there are many "person designated" records, primarily by reducing DB roundtrips. Observed ~60% improvement when testing 500 "person designated" records.
- When filtering for actionable records, or retrieving Inbox related data, "person designated" records are batched into a single query instead of running 500 queries
- employee->lookupEmpUID() - Consolidated 2 queries into 1
- VAMC_Directory->lookupEmpUID() - Removed redundant query
- checkEmployeeAccess() - Consolidated O(n) queries into 1. Instead of running a query for each user to determine if the current user is a backup, we run one query to see who the current user is a backup for. A new DB index has also been added to accommodate this.
- LEAF_Inbox.tpl has been updated to render …
> Leaf 4039 - Optimize "person designated" queries

- LEAF_Request_Portal/auth_domain/LEAF_coach_key.php
Summary:
This fixes the reference to the Db in the Leaf coach key.
Potential Impact::
This will not have an impact on the community at large. The impact is on support staff getting access to community portals. This change should fix the access and point it to the correct new location Db
Testing:
Regular regression testing but specifically the auth_domain/LEAF_coach_key.php
> Leaf coach key update

- LEAF_Request_Portal/admin/templates/mod_access_matrix.tpl
- LEAF_Request_Portal/auth_domain/LEAF_coach_key.php
Summary
In our last release a reference to a file was incorrect, causing a 404 not found error. The reference has been modified to the correct location.
Potential Impact
This shouldn't cause any other issues as it is contained within the access matrix
Testing
Be sure that the access matrix page loads and that there aren't any other errors on the page.
> Leaf 4048 - file found

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This lets the Inbox parse shortened report links correctly.
No known impact because the change extends an existing filter list, isolated on the Inbox page
> Inbox v2 - Catch shortened report links

- LEAF_Request_Portal/sources/Email.php
This removes an unused JOIN, which caused poor performance when the following conditions are met: 1) record submission or workflow actions 2) there are many data fields on the form 3) an email notification is sent to the next approver. Removing the JOIN avoids around [# data fields] * 3 queries in the subsequent loop.
None because the query doesn't select any data from the joined table.
> LEAF 4050 - Remove unused SQL JOIN

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/scripts/automated_email.php
- LEAF_Request_Portal/sources/Workflow.php
- LEAF_Request_Portal/templates/email/LEAF_automated_reminder_body.tpl
- LEAF_Request_Portal/templates/email/LEAF_automated_reminder_subject.tpl
Adds an option to start sending email reminders after a specific date to the workflow editor (email reminders modal).
Updates automated email script to use possible date values.
Updates automated email templates as needed to use the alternative option.
> LEAF 3913 - email reminders by scheduled date

- LEAF_Nexus/sources/Employee.php
This issue was brought up by a user saying that he wasn't able to pull disabled users by email or alias. The issue has been resolved and the way to test this by:
1. Going to the admin panel and click on New Account Updater
2. Search for the user that is disabled using the email or alias.
This can also be tested in the Nexus org chart, by searching for email or alias.
> LEAF - 4035 - New Account Updater Search Bug

- LEAF_Request_Portal/sources/FormWorkflow.php
This is a followup to https://github.com/department-of-veterans-affairs/LEAF/pull/2184
As it turns out, the existence of the "non-existent property" referenced in PR#2184 is conditional based on whether includePersonDesignatedData() is resolving employee IDs to their respective names. This caused an issue where the Workflow UI incorrectly displays duplicate labels. 
This re-adds the comparison, scoped to the relevant section, and clarifies documentation.
- Access rules that involve Person Designated Records
- Workflow UI that involves Person Designated Records
1. A record should be on a step that contains 2 requirements: Person Designated AND a Custom requirement assigned to a group
2. As admin, while reviewing the record, the workflow area should show the group's name and designated …
> LEAF-4077 - Add dependencyID check before overwriting approverName

- LEAF_Request_Portal/sources/Form.php
Note the PR merge base. This series of optimizations have been split into multiple PRs to simplify review.
Similar to PR#2155, this continues to optimize hotspots where "person designated" records are involved. This is important for usability in the Inbox and Report Builder. The reduction of DB round trips dramatically improves performance, measuring around 100% faster response time in the Inbox and 40% in the Report Builder.
Areas that depend on access checks related to "person designated" and employee backups
> LEAF 4062 - Optimize Form.php person designated access check (3 of 3)

- LEAF_Request_Portal/sources/Form.php
Note the PR merge base. This series of optimizations have been split into multiple PRs to simplify review.
This modifies getCustomData() to avoid duplicate checkReadAccess() queries. If checkReadAccess() was already run, then it's not necessary for getCustomData() to call checkReadAccess() again because it could only check a subset of the already checked records.
Read access to records
Preconditions:
- A record that the current user doesn't have access to read
- The record doesn't show up in the Report Builder
> LEAF 4061 - Optimize form/query and getCustomData's read access check (2 of 3)

- .gitignore
- LEAF_Nexus/qrcode/index.php
- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/admin/templates/mod_groups.tpl
- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/qrcode/index.php
- LEAF_Request_Portal/report.php
- LEAF_Request_Portal/templates/reports/coach_roster.tpl
- app/Leaf/Site.php
- app/libs/globals.php
- app/libs/globals_plus.php
- app/libs/loaders/Leaf_autoloader.php
- app/libs/smarty/plugins/modifier.sanitize.php
- app/libs/smarty/plugins/modifier.sanitizeRichtext.php
**Summary:**
This is a follow up to Leaf 4010.1. It updates any references to the old location to the new location. It also refactors the globals file to construct the PORTAL_PATH. 
**Potential impact:**
If a reference to the original was completely missed and it is still referring to the old location nothing should happen, the old files are still in their original location and accessible. However, if a reference were changed and it isn't quite right we could end up with broken references and 404 errors.
Where the globals are concerned, if a portal has the exact name as any of the folders we have it will break the site. A different way to construct the portal path would need to be figured out.
**Testing:**
A full regression testing is needed for this release. We are looking for broken …
> Leaf 4010-2 - update references to copied files

- LEAF_Request_Portal/js/LeafPreview.js
This seems to resolve issues getting details for forms on the portal admin LEAF library page.
Testing
On portal admin LEAF library page:
-'Preview' button should show the first page of the form.
-'Get a Copy' should import the form to the Form Editor.
We currently have limited ability to test this locally, as it requires a library portal with specific form and indicator IDs.  It would more easily be tested once staged.
> LEAF 4065 update endpoint url

- LEAF_Request_Portal/templates/view_reports.tpl
Adds the string 'isDisabled' to the key names passed to the new x-filterData parameter value so that information about indicator archived status is received.  This information was used to present archived status in the Report Builder Step 2.
Testing:
In the Report Builder, questions that are archived should once again display with a grayed-out background and also have '(Archived)' next to their name/label.
Possible Impact:
None expected.  This value is only used in the Report Builder Step 2 question display, and this change corrects for it currently being undefined.
> LEAF 4088 - add isDisabled to indicator list x-dataFilter

- LEAF_Request_Portal/mailer/mailer.php
This just places an if statement around the last two unlinks checking to make sure the file exists before trying to unlink it.
> Leaf 4042 - remove double unlink in mailer

- LEAF_Request_Portal/sources/FormWorkflow.php
This resolves an issue where a query for actionable records skips certain records in a specific condition.
To reproduce the issue:
1. Create a workflow with two sequential "person designated" steps
2. Create a form with two orgchart_employee fields
3. Map the workflow steps to the form
4. Create request A with the first designated person as the current user, and the second designated person as anyone else
5. Advance request A to the first step
6. Create request B with the first designated person as the current user, and the second designated person as anyone else
7. Advance request B to the second step
8. View the Inbox, we should expect to see request A
form/query for actionable records where a "person designated" assignment is involved
- [Experimental automated test …
> LEAF-4015 - Resolve actionable query issue

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This resolves an issue when an admin has added a shortened report URL into the sitemap.
Limited to the Inbox's "combined" mode
To reproduce the issue:
1. Create a report using the Report Builder
2. Click "Share Report", and copy the shortened URL
3. Go to the Sitemap Editor, add a button with the short URL as a target
4. Load the Combined Inbox. It should have a red error message on the top of the screen.
After this patch, there should not be an error message.
> LEAF-4093 - Inbox v2 - Add endpoint check

- LEAF_Nexus/js/dialogController.js
- LEAF_Nexus/templates/permission_iframe.tpl
- LEAF_Nexus/templates/print_subindicators.tpl
- LEAF_Nexus/templates/view_group.tpl
- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/admin/templates/mod_groups.tpl
- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/admin/templates/print_form_ajax.tpl
- LEAF_Request_Portal/admin/templates/print_subindicators.tpl
- LEAF_Request_Portal/js/dialogController.js
- LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
- LEAF_Request_Portal/templates/form.tpl
- LEAF_Request_Portal/templates/print_form.tpl
- LEAF_Request_Portal/templates/print_form_ajax.tpl
- LEAF_Request_Portal/templates/print_subindicators.tpl
- LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
- LEAF_Request_Portal/templates/view_inbox.tpl
- LEAF_Request_Portal/templates/view_reports.tpl
***Summary of changes***
-Delegated a listener to dialogController content to prevent default behavior for input elements if the enter key is pressed.
-Added listener to dialogController X(close) button so that it behaves the same way as the Cancel button.
-Wrapped dialogController show() method's content with a setTimeout 0 to consistently clear JS stack before trying to apply styles.  Added comment for clarification (there were prior comments suggesting this was related to older browsers when it is not) and removed some repetitive setTimeout wrappers around this modal show call.
-Deprecated onkeypress listener was replaced with onkeydown.
other:
The dialogController js file is currently in two places (one nexus, and one portal), and seem to have diverged somewhat - this is better …
> LEAF 2122 dialog modal and button related issues

- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/sources/FormWorkflow.php
This expands on earlier optimization efforts and improves performance when "group designated" records are involved. The optimization logic was largely copied from the "person designated" implementation to minimize complexity at the cost of some code duplication.
Performance improvement compared to Sprint-64-c1 when testing with ~500 "group designated" records:
```
goos: windows
goarch: amd64
pkg: LEAF/API-tester
cpu: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
│ sprint64c1.txt │     optimize-group-selected.txt     │
│     sec/op     │   sec/op     vs base                │
Inbox_nonAdminActionable-8     156.62m ± 4%   96.32m ± 2%  -38.50% (p=0.000 n=10)
```
Total improvement since Sprint-60-c2:
```
goos: windows
goarch: amd64
pkg: LEAF/API-tester
cpu: 11th Gen Intel(R) Core(TM) …
```
> LEAF-4123: Optimize "group designated" hotspot

- LEAF_Request_Portal/js/formQuery.js
- LEAF_Request_Portal/js/formSearch.js
- LEAF_Request_Portal/sources/Form.php
This follows [PR#2127](https://github.com/department-of-veterans-affairs/LEAF/pull/2127) and implements fulltext search for data fields within the portal.data table, which provides a better overall search experience. Backward compatibility in ./api/form/query is not impacted because the change only adds new search terms: MATCH ALL, MATCH, and NOT MATCH.
Using the original implementation as a baseline: Although the worst case performance is significantly better, this comes at a cost in best case performance and minor change in initial sort order. Average case performance also seems to be better when using the fulltext index.
| Condition | Before (s) | After (s) |
| :-- | :---: | :---: |
| Worst case performance (obscure search term "sterile pants") | 22.363 | 0.007 |
| Best case …
> LEAF-4121: Fulltext search

- LEAF_Request_Portal/sources/Form.php
This amends a filter used in the form/query when the debugQuery URL argument is present. The filter is meant to scrub unsafe characters in a HTTP header, however the characters ":" and "=" should be safe to use in this context.
Partially reverses commit c4f8dfc relating to HTTP header injection
Security: It should not be possible to overwrite previously defined headers.
> LEAF-4120: Update filter

- LEAF_Request_Portal/sources/Form.php
This patch prevents an invalid query and Error 500 due to an unchecked variable. It's a rare and low-impact issue because the user would have to be testing an incomplete configuration of the Parallel Workflow feature in order to trigger the error.
API endpoint: ./api/form/[RECORD_ID]/workflow/indicator/assigned
- [Experimental automated test added](https://github.com/mgaoVA/LEAF_test_experiments/commit/0429b7c777e2c2c60457c8d2f6c1d7fc0083e0d7)
Procedures:
- Precondition: Request's workflow only has a single "requestor followup" step
1. In dev env: Attempt to access https://localhost/LEAF_Request_Portal/api/form/RECORD_ID/workflow/indicator/assigned , where RECORD_ID is the ID of the request
2. You should expect to see this output in the Raw Data:
```
[]
```
> LEAF-4119: Prevent invalid query

- LEAF_Request_Portal/file.php
- LEAF_Request_Portal/sources/Form.php
This enables customizations to easily embed file uploads by adding the parameter *&inline* to the end of the file's URL.
For example, the following code in the LEAF Programmer would immediately display a PDF in compatible browsers.
*file.php?form=123...* is an example URL for an uploaded PDF document.
```html
<object data="file.php?form=123...&inline" width="800" height="600" type="application/pdf"></object>
```
A type checking issue was also identified and fixed.
Ability to download files
> Enable easy file embeds

- LEAF_Request_Portal/js/formQuery.js
This resolves an issue where only the first matching character would be replaced, instead of all matching characters.
The function updates the URL to replace "+" with its encoded format "%2b", since "+" would normally be interpreted as blank spaces.
Areas where formQuery.js is used, such as the homepage
The homepage should load correctly
> Use replaceAll function

- LEAF_Request_Portal/js/formSearch.js
This resolves an issue where the search term's first item could be drawn incorrectly.
1. Report Builder: set the filter to "Title CONTAINS test"
2. Continue and Generate the report
3. Refresh the screen
4. Click "Modify Report"
5. Note that the filter incorrectly states "Title CONTAINS [Resolved]", where [Resolved] is a dropdown.
Areas that depend on formSearch.js.
> LEAF-4157 - Resolve UX issue in formSearch.js

- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
Cleans up an event dispatch used to sync mod_form.tpl (original Form Editor) and the Conditions Editor app and simplifies the associated code.  Adjusts corresponding code in the Conditions Editor.
This is to resolve as issue where updates made to indicators in the Form Editor where not immediately reflected in the Conditions Editor app on staging and production.
Conditions Editor in the original Form Editor.
New Question / Question update issue could not be reproduced locally, but regression testing should be undertaken to ensure that this fix does not inadvertently introduce other issues.   This issue could be reproduced consistently on staging, so this specific fix can be tested further then.
> LEAF 3971 conditions editor new question display

- LEAF_Nexus/js/orgchartForm.js
- LEAF_Nexus/templates/view_position.tpl
This updates the .keypress listeners in the Nexus orgchartForm js file to .on("keydown" listeners.
This should restore enter-save functionality of Nexus employee, position and group modals.  These were not changed in the recent update but seem to have been impacted by the addition of a dialogController modal keydown listener. 
The deprecated/removed jQuery size() method was also replaced by the .length property to fix a separate uncovered error.
Impact/Testing
Nexus side, editable (check write access) position, group and employee fields should save when enter is pressed in orgForm modals.  Confirm that these fields consistently save correctly (particularly the Position 'Pay Plan' field, which required a short timeout for the chosen dropdown). 
Confirm that updating a position Total …
> LEAF 4139 update keypress listeners in orgchartForm

- LEAF_Request_Portal/ajaxIndex.php
- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
- LEAF_Request_Portal/templates/subindicators.tpl
Updates the subindicators template to use file type inputs rather than iframes for uploads and makes some minor display and contrast adjustments.
Fileupload and image formats were combined to a single case since their templates were almost identical.
This update should be backwards compatible for custom subindicators templates.
Should confirm that entry and editing of fileupload and image format request questions behave as expected.
This update should be largely unnoticed by users.
> LEAF 2531 (3188) file upload formats

- scripts/evolving.php
- scripts/time_to_evolve.php
Summary:
A script to replace the text from Leaf 4116. 4116 saved a file, this script will take that file and go through the array and replace the string searched for and replace it with a new string, or blank string to delete something.
This could have a huge impact as it is changing the content of files being used within the app. Special care needs to be taken to ensure that strings aren't being changed that shouldn't be. A careful observation of the json text file created in 4116 should be done to ensure that something isn't going to be changed that shouldn't be.
Testing:
This will require a full regression test. The amount of files and their content isn't readily available at this time. Not until a string has been determined to be replace.
> Leaf 4130 - update string found

- LEAF_Request_Portal/templates/subindicators.tpl
Updates the file format validator to check the new input element rather than querying for other DOM elements to determine if new files have been attached.
This change is specific to file and image upload format questions with required status.
> LEAF 4183 update file upload validator

- LEAF_Request_Portal/js/formQuery.js
This prevents an issue where subsequent executions of formQuery don't reset limit counters to their original intended state.
To reproduce the issue, view this LEAF Programmer script on a site that has more than 500 records:
```html
<script>
async function main() {
let resultDom = document.querySelector('#result');
let query = new LeafFormQuery();
let result = await query.execute();
resultDom.innerHTML += `First run #: ${Object.keys(result).length}<br />`;
let result2 = await query.execute();
resultDom.innerHTML += `Second run should be the same #: ${Object.keys(result2).length}`;
}
document.addEventListener('DOMContentLoaded', main);
</script>
<div id="result"></div>
```
Areas where formQuery.js is used, such as the main page and report builder
> Leaf 4186 - Persist original parameters

- LEAF_Request_Portal/admin/templates/mod_templates.tpl
- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
- LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
Cleaned code for template editors to prevent console logs from displaying in dev tools during certain processes.
Users will no longer encounter console logs during specified processes, enhancing the overall user interface.
1. Navigate to the template editor.
2. Open the browser's developer tools (F12).
3. Select the console tab.
4. Perform actions like saving and deleting. Confirm that no console logs are visible during these processes.
> LEAF-4107-Remove-Console-Logs-From-Editors

- LEAF_Request_Portal/sources/FormWorkflow.php
This prevents an invalid query, because the groupID variable here can actually be blank. The invalid query did not cause any end-user impact, however it's cleaner to not run an invalid query in the first place.
Queries that involve "group designated" records
This passes [existing tests](https://github.com/mgaoVA/LEAF_test_experiments/blob/main/Go/formQuery_test.go#L71) related to group designated records.
> Leaf 4173 - Prevent invalid query

- LEAF_Request_Portal/sources/Form.php
This resolves an issue where a Report Builder query that contains the following terms results in an ambiguous query.
- RecordID
- Data field
The ambiguity happens because the Data field uses a join that retrieves the RecordID from a different table.
Searches for record ID
[Automated test case](https://github.com/mgaoVA/LEAF_test_experiments/commit/f3ef7f815d37823eefb65bdac027aabb4c1d1baf#diff-b7b1922b928b6c4ca9f0342a10188972bc7aa07897032f05faff1cb2b96f5234R115)
[0] For example if record 500 contains a field filled with 12345, you should expect to find it when searching for Record ID = 500 AND Any standard data field CONTAINS 123*.
> Leaf 4172 - Avoid ambiguous query when used in combination with a data query

- LEAF_Nexus/js/employeeSelector.js
- LEAF_Nexus/js/nationalEmployeeSelector.js
This simplifies customization of the employee selector. Instead of requiring a dev to re-implement the default select handler, this introduces the new method addSelectHandler() to execute custom functions after the default handler has run.
Example use case: https://github.com/department-of-veterans-affairs/LEAF-Developer-Examples/blob/master/forms/custom_fields/copy_orgchart_employee_email_to_new_field.md
Loading of employeeSelector.js and nationalEmployeeSelector.js.
Successful completion of these tests ensure that the modified files have been loaded correctly.
> Leaf 4171 - Improve customizability for Employee Selector

- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
To reproduce this issue:
Create a request that includes a checkboxes format question.
Go directly to the print view / review page.
Note that a checkmark displays even though no information was entered.
Specific to checkboxes format form questions.
Ensure above behavior no longer occurs and that no unexpected behavior is introduced.
> LEAF 4166 prevent checkmark if initial value is empty

- LEAF_Request_Portal/sources/FormWorkflow.php
There was reported behavior that showed custom email fields not showing in cases other than custom emails. This change modifies the logic so that custom email fields are usable in the body of any type of email.
Custom email fields are now usable in default email templates.
Test every kind of email with custom email fields
* Custom emails
* Notify Requestor
* Notify Next Approver
> LEAF-4155: Custom Fields not added to non-custom email templates

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/sources/Workflow.php
Adds an update to prevent users from creating a Requestor --> End connection on build in workflows.  This correction is necessary because it creates an unavoidable help desk ticket as the user cannot undo this change.
Also prevents duplication of built in workflows and provides more obvious feedback about modifications to built-in workflow being restricted.
Workflow Editor
-It should no longer be possible to modify the initial requestor --> step connection on built in workflows.
-Confirm that custom workflows still behave as expected.
> LEAF-3190 prevent built in workflow modification

- LEAF_Request_Portal/js/workflow.js
- LEAF_Request_Portal/templates/subindicators.tpl
Adds relative position to the parent of the date format _focusfix element.
This prevents the modal content from shifting in the Inbox 'take action' modal when the date is updated.
testing / impact
Date format questions.  Ensure that display is not unintentionally impacted elsewhere.
See Jira LEAF-4193 for a test form.
> LEAF 4193 - add relative position to parent to prevent form shift

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This resolves an issue where files can't be deleted using the in-line workflow interface on the Inbox page.
- Precondition: The request must have a workflow step that contains an inline file upload field, and is currently on that step
1. Open the Inbox, find the request, and click "Take Action"
2. Attempt to delete a file referenced in the file upload area
No external dependencies
> Leaf 4207 - Add missing dialog template

- LEAF_Request_Portal/admin/templates/mod_templates.tpl
- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
- LEAF_Request_Portal/api/controllers/EmailTemplateController.php
- LEAF_Request_Portal/api/controllers/TemplateController.php
- LEAF_Request_Portal/sources/EmailTemplate.php
- LEAF_Request_Portal/sources/Template.php
This resolves an issue where templates are incorrectly listed as "custom".
- Precondition: The "intial_form" and "form" templates have not been customized.
1. Navigate to the Template Editor
2. Modify the "initial_form" template
3. Click refresh
4. Note that the "form" template is incorrectly listed with a "custom" flag.
None, because there are no external dependencies on api/template and api/emailTemplates.
> Leaf 4208 - Resolve issue related to incorrect "custom" designation

- LEAF_Request_Portal/sources/FormWorkflow.php
- LEAF_Request_Portal/templates/print_form.tpl
- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
3 changes:
1. When there's a disabled account associated with a "person designated" request, the workflow shows a visible "\*NEEDS REASSIGNMENT\*" message.
2. Text related to "restore records" has been re-worded to clarify its status.
3. In the Inbox, approverName can contain the label of a field in the event there's a disabled account in a "person designated" field, which can contain HTML formatting. This change scrubs HTML from the text to ensure formatting is consistent.
- Admins may require notification to explain the "NEEDS REASSIGNMENT" message
1. Set up a record that's pending a "person desginated" field
2. Disable the account associated with the "person desginated" field
> LEAF-4199 - Text updates

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This resolves an issue where default columns incorrectly shows "UID", instead of "UID,service,title,status".
- Inbox when the Sitemap has been populated
1. Create a new entry in the Sitemap with an active site. Or remove and recreate an existing entry.
2. Open the Inbox.
> LEAF-4200 - Fix default Inbox columns

- LEAF_Request_Portal/sources/Group.php
- LEAF_Request_Portal/sources/System.php
Summary:
When User A is added to System Admin via the User Access Groups page their backups are added as well. Subsequently, if a backup is removed from that User in the Nexus the portal side can never be updated, unless you remove the User A and then add them back in. In this story I updated the sync services in order to update and refresh the system admins, it only flushes backups that are no longer backups.
By fixing this backups that are no longer will not be receiving notifications for things they are no longer responsible for.
Testing:
Add a user, that you know has one or more backups as a system admin 
Go to Nexus and remove at least one of those backups
before fix
attempt to remove this backup from the system admin group (should not be removed)
do a sync service …
> Leaf 4210 - former backups cant be removed from system admin

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This seems to be the correct implementation of a plain JS HTML scrubber.
Local to the Inbox, no external dependencies.
> LEAF-4214 - Attempt to fix html scrubber

- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/templates/view_inbox.tpl
This resolves issues in the legacy inbox view affecting file/image upload and textarea format questions.
New inbox template dialog issue is already being addressed by LEAF-4207
Impact/Testing
**Legacy inbox Take Action modals** with file/image upload format or textarea questions should not cause errors in console when opened.  File/image upload and removal should behave as expected.
> LEAF 4195 add files to legacy inbox view

- scripts/leaf-scripts/check_user_upload_sizes.php
- scripts/leaf-scripts/filehistorgram.php
- scripts/leaf-scripts/showdbvers.php
This is a script that will export a csv with the max, min, average filesizes and count of files. It outputs in MB to make things a bit more useful. 
I also have a copy of the db vers, this  is setup for looking at portal db versions. This had not been copied over and this has been useful for helping find and verify things are working.
These files should have no impact since they are scripts run by developers only.
> LEAF-2478 - Histogram for sizes of uploaded files

- LEAF_Request_Portal/templates/print_form.tpl
Increases the width of the chosen dropdown used for changing the workflow step to 100%.
Adds a label element and some attributes for the chosen dropdown.
Testing/Impact
Chosen plugin dropdown used to change request step.  This is accessed via the admin tools 'change current step' option for the print view of a submitted request.
Dropdown should now be 100% of the modal width.  Appearance and functionality should otherwise remain the same.
> LEAF 4231 increase chosen width to 100%

- LEAF_Request_Portal/ajaxIndex.php
- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
Assigns an absolute portal path variable and updates the file path in print_subindicators_ajax.tpl to correct for potential cross portal request attachments in the combined inbox.
**Testing / Impact** 
Request file upload and image downloads and links should continue to behave as expected.
Although listed in the template editor, print_subindicators_ajax does not appear to actually be customizable, so there should not be issues from potential template customization.
> LEAF 4196 update file paths for combined inbox 

- LEAF_Request_Portal/admin/templates/mod_account_updater.tpl
- LEAF_Request_Portal/admin/templates/mod_groups.tpl
- LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
- LEAF_Request_Portal/api/controllers/GroupController.php
- LEAF_Request_Portal/api/controllers/ServiceController.php
- LEAF_Request_Portal/sources/Group.php
- LEAF_Request_Portal/sources/Service.php
This simplifies Group/Service Chief management in Request Portals by eliminating the "prune" step, and resolves issues where "users can't be deleted from groups". Related API endpoints have also been simplified to minimize database queries and to align with intended behavior based on REST semantics.
In the User Access Group and Service Chiefs sections, the headers "Local" and "Nexus" have been removed. "Inherited" has been added, which represents whether the user was inherited from the Nexus.
The search in User Access Groups has also been updated to find backups.
- Changes are primarily limited to the Admin Panel: User Access Groups and Service Chiefs
- Other dependencies include New Account Updater and print_form.tpl (it retrieves a list of services)
- Preconditions:
1. Nexus contains …
> Leaf 4250 - Simplify group/service management in Request Portals

- LEAF_Request_Portal/sources/FormEditor.php
Updates the check prior to logging form changes for:
categoryName, categoryDescription, workflowID, sort, visible (availability), and need to know
Form Editor (server side)
Setting a form name or description to an empty value, removing a form workflow, turning off need to know, hiding a form, or setting a form sort order to 0 should all result in a log entry in the form history.  Form updates and logging should continue to behave as expected.
> LEAF 2938 log form falsey value updates

- LEAF_Request_Portal/sources/Service.php
Fixes empty header elements for ELT groups in the portal Service Chiefs admin area.
Uses the services.service field (the service name) rather than the groups.name field when selecting quadrads since the group name is null on this join unless the ELT is tagged with the portal (which users should not need to do).
Using the suggestion to select the service field as name to avoid needing further front end adjustments.
**Testing/Impact**
Create a new ELT in the nexus and a new Service under that ELT (nexus admin, Setup Wizard, Exec Leadership Team and Services steps).  Sync services in the portal.
In the Service Chiefs area, the new ELT name should appear in the h2 header tags with sub-services listed beneath it.
> LEAF 4233 fix null service name

- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/js/combined_inbox_editor/src/combined_inbox_editor.vue.css
- LEAF_Request_Portal/js/combined_inbox_editor/src/combined_inbox_editor.vue.js
- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
**Combined Inbox Editor (beta) and LEAF_Inbox options updates**
-Fix bug that causes non portal sitemap cards to be deleted.
-Fix error that occurred if the sitemap card target does not end in a slash.
-Add js XSSHelpers to strip out all potential HTML in custom header names and update custom headers to use the short label if it's available instead of the full indicator name for the multiselect plugin options.
-Add Priority and Date Submitted header options.  Inbox view will automatically sort by priority if this header is present.
-Add ability to add form-specific settings for indicator questions.
-Inbox View 508 Adjustments:
Category Headers are now buttons instead of divs for keyboard accessibility.
Top buttons for view and organization options now tab left to right.
**Testing / …
> LEAF 4223 idea inbox customizations

- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/js/combined_inbox_editor/src/combined_inbox_editor.vue.css
- LEAF_Request_Portal/js/combined_inbox_editor/src/combined_inbox_editor.vue.js
- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Fixes a potential breaking error by chaining formColumns property, which can be missing.
More effectively handles the case of a portal not yet having any sitemaps cards:
-'loading...' replaced with a message and link to the Sitemap Editor, where cards are created.
-Adjusts some styling for the default display that is used in the inbox when the site has no sitemap cards
> RC 69c1 fix inbox error, handle no cards case better

- LEAF_Request_Portal/ajaxIndex.php
- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
- LEAF_Request_Portal/templates/subindicators.tpl
Updated:
Tentative solution to resolve an uncovered issue that can cause cross site upload format questions updated through Combined Inbox Take Action form fields to either fail, or potentially upload to the incorrect ERM folder.
Also resolves an issue that results in a temporary incorrect link in the indicator print display loaded into form questions after an edit is made through a print view area.  The variable name was also updated to help avoid confusion.
Site specific and Cross site upload format questions (fileupload, image) should behave as expected on site specific pages and in the combined inbox view.
> LEAF 4248 update availability for variable used for uploads

- LEAF_Request_Portal/css/style.css
Setting against RC for now for easier review.
Removes a change made on 69c1 that increased the search container font by 2px.
Explicitly sets browsetype span to 11px meet font size scan threshold.
> LEAF 4259 - set browsertype span to 11px, rm table font change

- LEAF_Request_Portal/js/formGrid.js
Summary:
exporting data where fields have a large number (approximately 10 numbers or more) caused Excel to format it as an exponential number. This fix will force Excel to look at those numbers as text keep the number as it was.
Impact:
If someone wanted the number to be shown as an exponential number they would have to force Excel to do it after opening the file.
Testing:
create a report that have fields with only numbers and more than 10 numbers long. export it and notice the way Excel formats it.
> Leaf 4216 - fixes large number exports.

- LEAF_Request_Portal/sources/Email.php
Issue:
Automated emails were not coming through, this is an error that we saw in our logs and did not have a case study to figure out what is going on since there were no paths shown around the error in the main log. 
What I found to be the issue, the query is not returning a userid, further inspection using directive in the sql query is not joining as one would expect. When I adjusted the query to specifically use specific columns it returns the data that I would have expected.
Affected Site:
Staging could be used to test this out. 
https://leaf.va.gov/VISN20/653/health_administration_service/index.php?a=printview&recordID=2104
Possible Problems:
The code talks about quadrads I do not think this is a quadrad issue it self but this code could be used for it. 
Testing queries: 
`SELECT …
> LEAF-4241 - INC31179685 : Mail error No Recipients

- app/Leaf/Site.php
Summary: A query needed to pull as Select * so that we wouldn't break the site while everything was pushed last Thursday. This is just to clean that query up and make it pull specific fields.
There shouldn't be any impact. It was only changed to prevent the site from breaking during deployment. This sets it back to what it was before with the addition of the 2 fields added in that deploy.
> Leaf 4239 - cleanup after 4204 release

- LEAF_Request_Portal/css/style.css
Re-adjusts submenu location.
An alternative approach would be to lower the observer threshold (eg 0.75), but this seemed the simplest and cleanest looking one.
Testing
Non-admin side nav.  Submenus are positioned back at the end of the parent ul.
Distance between the default nav buttons 'links' and  'help' and the corresponding submenus is suitable for hover behavior.
Observer on both buttons should trigger in both admin and non-admin modes.
Help submenu should display the name and email of the portal's primary admin if the role has been set.
'Primary admin has not been set' should display if there is no primary admin.
> LEAF 4261 change submenu location

- LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
- LEAF_Request_Portal/sources/Service.php
- LEAF_Request_Portal/sources/System.php
Summary:
The headings on the services page were not always correct. The issue was pulling the service rather than the group name which was brought about by the ELT/Quadrad not being added to the groups table unless they were tagged in the ELT on the Nexus side. This change will add the ELT to the groups table no matter what. The query was changed back to using the group name.
This should just show the correct ELT name now. 
Testing:
Ensure there is an ELT in the Nexus that is not tagged for the portal
Complete a sync services
check that the ELT is the heading of a service
> Leaf 4260 - service headings now show correctly

- LEAF_Request_Portal/admin/templates/mod_form.tpl
Fixes an issue that causes the file name used to add grid cell dropdown options to be incorrect if the file name contains spaces.
> LEAF 4253 fix file name with spaces

- LEAF_Request_Portal/js/formSearch.js
This resolves an issue with formSearch (e.g. main page advanced search or report builder) where the previously selected Current Status appears to revert to the default search option. This can cause significant confusion when modifying reports, since people would expect their previous selection to stay the same.
Technically the issue is that a callback wasn't being executed. The call was mistakenly embedded in a solution for a race condition.
Steps to reproduce the issue:
1. Set two search terms. The first search term can be anything other than Current Status. The second search term must be Current Status IS [Any specific step in a workflow]
2. Save the search (by applying filters on the main page, or generating a report in the Report Builder)
3. Refresh the view multiple times. Sometimes …
> LEAF-4296 - Resolve issue when rendering previous search UI

- LEAF_Request_Portal/templates/reports/LEAF_Data_Dictionary.tpl
- LEAF_Request_Portal/templates/view_reports.tpl
This makes the Data Dictionary view more user friendly.
This also serves as an example for how features that require a table view could leverage formGrid.js to inherit basic features with little effort (sticky headers, sorting, export, consistent UI).
> Leaf 4285 - Data dictionary UX

- LEAF_Request_Portal/sources/Email.php
This update adds cc values to the emails logged by the email tracker.
Step or submit a request with an appropriate event.
eg notify next, where designated approver has a backup. 
Customized notify next email template with cc field.
Users (eg backups) as CC on emails should show as having been emailed in the request history.
local - Confirm smtp server recipients are those expected and show in history.
live - Confirm email received, that recipients are those expected and show in history.
> LEAF 4283 add cc to tracker history

- LEAF_Nexus/admin/index.php
- LEAF_Nexus/sources/System.php
- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/sources/System.php
Adds the following time zones to the available selections in portal and nexus site settings.
"America/Puerto_Rico",
"Pacific/Guam",
"Pacific/Saipan",
"Pacific/Pago_Pago",
"Asia/Manila",
Portal and / or Nexus admins should be able to select and save the new time zone selections.
portal -> admin -> Site Settings (time zone)
Nexus -> admin -> Setup Wizard -> Site Preferences (time zone)
> LEAF 4287 expand timezone selection and validation

- LEAF_Request_Portal/sources/Service.php
Adds two lines that are in the group getMembers call to sort by last name to the service getMembers call as well.
Service Chiefs page.
Group members will be listed alphabetically by last name.
No other functionality should change.
> LEAF 4286 service chiefs area member sorting

- LEAF_Request_Portal/js/form.js
- LEAF_Request_Portal/js/gridInput.js
Updates a sort method used to create options for grid cells and chosen dropdowns so that options with numeric values have a more natural order.
Grid format questions, dropdown from file type.
Dropdown and Multiselect format questions using loading via ifthen.
Confirm these continue to behave as expected.
The only difference should be the order of selections for grids and chosen dropdowns when values include numeric entries.
> LEAF 4274 file options natural sorting

- LEAF_Nexus/templates/view_position.tpl
Fixes a TypeError on the Nexus view_position page that occurs after updating a supervisor.
A TypeError should not occur when a supervisor is updated.
Trying to set the supervisor as a non-admin should show an intended alternate message.
> LEAF 4298 fix callback error in view_position set supervisor

- LEAF_Request_Portal/sources/System.php
Summary:
deletedUser
When deletedUser had a backup that didn't get deleted or deletedUser was a backup to someone else who got deleted they will still get email notifications but will not show up in the service chief list.
userName        backupID
User1                                    Is a regular member of the group
User1            User2                User1 is a backup to User2
User3            User1                User3 is a backup to User1
In this scenario User1 will show up as a regular user and User3 will show as a backup for this user
User2 will not show up at all and user1 will not show as a backup because user2 isn't showing up anywhere.
However, User2 will get any notifications that this group gets because they are still in the group in the db.
It's not known how to get to …
> Leaf 4271 - orphaned users and chiefs

- LEAF_Request_Portal/admin/templates/menu.tpl
- LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
- LEAF_Request_Portal/templates/reports/LEAF_Data_Visualizer.tpl
This introduces a basic data visualizer and adds a button on the Admin Panel.
The visualizer makes it easier to review form responses, especially for surveys. Similar to the Report Builder, filters are encoded in the URL, which makes it trivial to share custom views.
- No dependencies
- Admin Panel -> Data Visualizer generates accurate charts
> Leaf 4307 - Simple data visualizer

- LEAF_Request_Portal/sources/FormWorkflow.php
Replaces Microsoft Smart Quotes (curly quotes) with normal quotes and some other unrepresented characters with equivalents to avoid character display issues in email content.
> LEAF 4299 unrepresented characters in email templates

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Accounts for an additional nested modal in the **workflow editor** when creating a new requirement
workflow step -> stepInfo Modal -> Add requirement -> create new requirement -> **add label + save -> add group**
Workflow Editor
stepInfo modal should not re-open after adding the label and saving.
stepInfo modal should reopen after adding group, or after cancelling at any point in the process above
Changes are specific to the requirement creation process.  Other functionality not expected to be impacted.
If helpful/ for clarity, the dialog controller does not have a 'cancel' handler, it has a poorly named 'always do this on close' handler
> LEAF 4318 fix stepinfo submodal popup

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This hides buttons intended to edit the form that currently don't work. It also opens the UID link in a new tab when clicked.
Potential Impact
Testing
Navigate to the combined inbox. Click any Quick View button. See that there are no edit buttons.
In inbox, click any UID link and it will open in a new tab.
> Leaf 2836 - Hide edit buttons inside inbox and open UID link in new tab

- LEAF_Request_Portal/templates/view_reports.tpl
When using the JSON export option in the Report Builder, this reduces metadata that users have not explicitly asked for.
- JSON exports from the Report Builder don't include metadata that aren't explicitly requested. If power-users want all metadata, they can remove the x-filterData parameter in the URL.
> Leaf 4319 - Report Builder: Default option to reduce metadata for JSON exports

- LEAF_Request_Portal/qrcode/index.php
QR codes aren't working due to a HTML entity encoding issue.
Steps to reproduce the issue:
1. Navigate to a record
2. Print preview
3. Note that the QR code resolves to a non-working URL because it includes \&amp; when we expect to have &
- No other dependencies
> LEAF-4273 - Fix broken QR code

- LEAF_Request_Portal/templates/reports/LEAF_Data_Visualizer.tpl
This cleans up some visual design quirks on the first "select a form" page:
- Table header border
- Streamlined date tooltip in the sparkline
- Switched to line charts for the sparklines
- HTML syntax is stripped when exporting to the Report Builder
- No dependencies
> Leaf 4323 - Data Visualizer: Cleanup layout

- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/sources/Workflow.php
- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This resolves a few issues with integrated forms, such as the LEAF-S Certification form.
Issue 1: The records_dependency table wasn't being updated correctly because integrated forms have a negative workflow ID, which prevented the record from showing up in the Inbox
Issue 2: The Inbox wasn't retrieving form labels correctly because it didn't include forms that were associated with a negative workflow ID.
The new GET parameter `includeStandardLEAF` was added to ./api/workflow/categories, which includes standard integrated forms in its output.
This also slightly improves organization of the Inbox's "Organize by Roles" view, so that sections are organized by a unique identifier that combines the dependencyID and stepID.
- Submitting new records
1. Navigate to Admin Panel -> Site settings
3. …
> LEAF-4335 Resolve issues with integrated forms

- LEAF_Request_Portal/js/formGrid.js
- app/libs/js/LEAF/formGrid.js
-Includes commit for LEAF-4330 (DOM script scrub).
-Resolves JAWS code being read after sorting headers.
-Resolves NVDA reading headers multiple (X3) times after sorting.
-General 508 updates:
A status message for the table is read after sorting a header.
A briefer column sorting status is read upon tabbing to a header. This might also be read immediately after sorting (NVDA).
Aria-hidden attribute should prevent 'up/downward pointing triangle' being read when present.
Other info: Does not resolve issues associated with table layer navigation.
In both JAWS and NVDA, screen reader table layer nav exits after sorting headers.  Table layer nav can be re-entered once out of headers.  While adding a button seems to resolve this, it is not being added at this time since it could cause issues …
> LEAF 4311, LEAF 4330 formGrid 508 no buttons and DOM scrub

- LEAF_Request_Portal/admin/css/mod_templates_reports.css
Removes a prior style override that can cause issues with templates / reports that are over 999 lines.
Style is specific to Template Editor, Email Template Editor, LEAF Programmer pages.
Margin-left value of the sizer element associated with code line numbers should scale as needed (this is calculated by CodeMirror lib) and left side of code should consistently be completely within view.
Please test with Edge and Chrome, in both code editor and code comparison views.  Confirm display remains consistent after horizonal and vertical screen resize and page scrolling.
> LEAF 4331 remove codemirror style sizer override

- LEAF_Request_Portal/ajaxIndex.php
- LEAF_Request_Portal/api/controllers/FormController.php
- LEAF_Request_Portal/sources/Form.php
- x-test/API-tests/form_test.go
The only situations when a record can be cancelled:
- If you are the author of the record and it has not been submitted
- If you are an admin
Added automated tests.
- This changes previous rules about who can cancel records. The community should be notified about this change.
> LEAF-4345 - Update rules for cancelling requests

- LEAF_Request_Portal/templates/view_reports.tpl
Covers an edge case in Report Builder where headers associated with Step fulfillment dates (Checkpoint Dates) continue to display the generic 'Checkpoint Date' text.
It adds a call to /steps to get the information if it's still needed after grid render.
However, this call should not typically be needed (the issue occurs if data for that step does not exist for any records returned by the query), so it should not make much impact.
**Impact/Testing**
Report Builder field selection.
Step 2, top right column, select options for Checkpoint Dates.
Headers should update to show the step name after generating a new report, or after opening an existing report using a short url (this is obtained by clicking the 'share report' button).
> LEAF 4315 checkpoint date headers edgecase

- LEAF_Request_Portal/css/style.css
Adds a style to prevent request notes from overflowing the note container.
Form request, side notes.  Add a note with long text (eg request URL).
Text should wrap if needed.
> LEAF 4342 fix comment note overflow

- LEAF_Request_Portal/api/controllers/FormWorkflowController.php
- LEAF_Request_Portal/js/workflow.js
- LEAF_Request_Portal/sources/FormWorkflow.php
- x-test/API-tests/database/portal_test_db.sql
- x-test/API-tests/dbsetup_test.go
- x-test/API-tests/employee_test.go
- x-test/API-tests/formQuery_test.go
- x-test/API-tests/formStack_test.go
- x-test/API-tests/formWorkflow_test.go
- x-test/API-tests/form_test.go
- x-test/API-tests/hotspot_benchmarks_test.go
- x-test/API-tests/main_test.go
- x-test/API-tests/service_test.go
This modifies the response for `api/formWorkflow/[digit]/apply` by replacing the returned "status" property with HTTP status codes, which improves interoperability in custom implementations.
Also:
- Adds automated tests for common error conditions
- Updates verbiage for incomplete workflow
- Changes in API test framework:
- Modifies the names for some global variables
- Now automatically runs DB schema updates (updateDatabase.php)
- Updated the base test DB with the latest schema
- This can potentially break existing custom pages that use `api/formWorkflow/[digit]/apply`. Custom code must be scanned to determine whether they use the now-removed "status" property. Note that the reference implementation within `workflow.js` did not use it.
> LEAF-4343 - Form workflow error handling

- LEAF_Request_Portal/js/formSearch.js
- LEAF_Request_Portal/templates/reports/LEAF_Data_Visualizer.tpl
- LEAF_Request_Portal/templates/view_reports.tpl
This resolves a few edge-cases related to the formSearch widget.
Additionally, this hides references to built-in forms behind the "dev" GET parameter to reduce clutter.
Steps to reproduce Issue 1:
1. Open the Data Visualizer
2. Select a form
3. Click on `Edit Filter`
4. Add a filter for `Date Submitted...` (can be anything)
5. Click on `Apply Filters`
6. Click on `Edit Filter` 
7. Note that excess search options are incorrectly included
Steps to reproduce Issue 2:
1. On the homepage in the search area, click on `Advanced Options`
2. Change the search term to `Record ID`
3. Change the search term back to `Current Status`
4. Note that the dropdown of status options is missing
Steps to reproduce Issue 3:
1. Open the Report Builder
2. Note that every time you click on `And...`, a network …
> LEAF-4346 - formSearch.js cleanup

- LEAF_Request_Portal/js/formPrint.js
Updates the way print to PDF sets up the URL so that it is not reliant on content in customizable templates.
Print to PDF button.
Changing the home link  href value in Template Editor menu.tpl should no longer cause an error when PDF button is clicked.
QRCode on forms exported with Print to PDF button should continue to refer to the request URL.
> LEAF 4238 update print to PDF homeurl

- LEAF_Request_Portal/js/formGrid.js
This avoids a duplicate "No results" message in certain customizations.
Minimal since we're asserting that the grid should only ever show "no results" when there's no data to display.
> LEAF-4359 - Avoid duplicate message in formGrid

- LEAF_Request_Portal/admin/templates/mod_account_updater.tpl
- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/js/formGrid.js
- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
- LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
- LEAF_Request_Portal/templates/view_reports.tpl
- app/libs/js/LEAF/formGrid.js
- docker/vue-app/src/site_designer/LEAF_Designer.scss
- libs/js/LEAF/formGrid.js
This removes an IE7 workaround for CSS `position: sticky`, and removes all references to the old virtual header.
The main improvement is that it's possible to change the sort (or other features in the header) even when scrolled down, and the header doesn't appear to lag while scrolling. This also resolves an issue where the old virtual header would become misaligned in certain situations (e.g. Inbox).
Note that the formGrid.js file in /app/libs and /libs/js were outdated, and have been overwritten by the one in /LEAF_Request_Portal/js . The scope of this review should exclude the former 2 directories.
Potentially impacts the Homepage, Report Builder, and Inbox, when scrolling through many records
> LEAF-4361 - Use CSS position: sticky in formGrid headers

- LEAF_Request_Portal/sources/Form.php
Resolves an issue where the Special Access Restriction indicator doesn't show up correctly for fields where its `parentID == 0`
Steps to reproduce issue in the Form Editor:
1. Open a form and edit a section heading
2. Click "Show Advanced Attributes" and add a group
3. Note that the icon in the form overview is missing
Minimal. This adds a missing join and the same join is used for fields where `parentID > 0`
> LEAF-4351 - Form Editor: Fix access indicator

- LEAF_Request_Portal/templates/view_reports.tpl
Minor fix to avoid a database join when it's not requested
1. Report Builder -> Do not select "Service" in step 2 -> Generate report
2. Click JSON
3. Note that the URL incorrectly includes "service" in the "joins" section
> LEAF-4350 - Report Builder: Only join service when requested

- LEAF_Request_Portal/admin/templates/mod_system.tpl
Add a warning display and modal confirmation if a subordinate site tries to change an existing value of the associated primary site.
Add comparisons for existing site settings so that calls are only made for values that have changed.
Add Title / Facility text update in respective ajax success options to make Title and Facility name updates more reactive.
Add ajax error options.
Portal admin area, Site Settings page.
If the site type is subordinate and an existing primary site value is changed, a warning message will display.
If save is clicked in this situation, a modal will prompt to confirm the change.
Confirm that all settings can be updated as expected.
other:
Only changed values should result in POST requests.
The site Title and Facility displayed in the header …
> LEAF 4232 subordinate site warning when primary changed

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This partially reverts 36b3bdb000aab8e54c04c680ab1c86c20f0ab561 where Inbox Role organization was "improved" to subdivide roles by the forms in which they appear.
The view when organizing by roles has also been updated to remove the form label and step, which aligns more strictly with the original intent of "Organize by Roles".
This can cause confusion if roles are shared between multiple forms. In those cases, people should be directed to use the "Organize by Forms" option. It may be necessary to explain that people will only see records when they personally have a pending action, unless they're an admin.
> LEAF-4360 - Revert inbox role organization

- LEAF_Request_Portal/sources/Form.php
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024022901-2024052000.sql
Adds a metadata column to portal data and portal data_history tables.
Also comments out a currently unused query.
Portal Database update for table associated with request data entry and editing.
Confirm database update and revert work as expected.
The added column is not currently used and has a null default value.  Confirm no changes in behavior.
> LEAF 4344 - add metadata column to portal data, data_history

- LEAF_Request_Portal/js/formGrid.js
- app/libs/js/LEAF/formGrid.js
In essence: Dates should be dates. Text that look like it could be a date should be treated as plain text.
If the user enters in a text field:
- 2/2
- 2-2
- 1/2/34
- 123456789000000000000000
Excel should NOT show:
- 2-Feb
- 2-Feb
- 1/2/1934
- 1.23457E+23
> LEAF-4364 - INC33016631 Data export date not detected as date

- LEAF_Request_Portal/js/formSearch.js
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/templates/view_search.tpl
- x-test/API-tests/database/portal_test_db.sql
- x-test/API-tests/formQuery_test.go
- x-test/API-tests/form_test.go
This expands `api/form/query`: Find all records if a specific action was taken for a given step.
No additional DB indexes seem to make a meaningful difference in query performance. Observed up to 0.14s query time on a site containing 2M actions.
Automated tests pending merge of PR#2390
- https://github.com/department-of-veterans-affairs/LEAF/pull/2395
- https://github.com/department-of-veterans-affairs/LEAF/pull/2390
Minimal because this adds new functionality without touching existing core logic.
> LEAF-4349 - Query step actions

- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/js/workflow.js
Adds a word-break style for form -Comment- area and printResponse spans to prevent text overflow.
Style change should be specific to Comment and form data areas and only be noticeable for long strings without spaces.
Long comments (eg Report Builder URL) should wrap rather than overflow the comment or form areas.
Check for unexpected display changes.
> LEAF 4362 Add word breaks for form comments and content

- LEAF_Request_Portal/sources/Email.php
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/templates/email/LEAF_cancel_notification_body.tpl
- LEAF_Request_Portal/templates/email/LEAF_cancel_notification_subject.tpl
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024052000-2024060700.sql
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024060200-2024060600.sql
Summary:
An email should be sent to notify people associated with prior steps
- The email should state the request has been cancelled, the reason for cancellation (if any), and a link to the request
- If a request has not been submitted, the email is not necessary
This should only affect cancelled requests.
Testing:
Setup a request that can be cancelled.
Cancel the request, (entering a comment as well as not entering a comment)
Observe that an email went to the previous recipients of emails from this request (check the view history to find a list of those previously email)
The email should have the comment if one was supplied.
> Leaf 3135 - email priors on cancel

- LEAF_Request_Portal/sources/Form.php
This is a quick fix to change the wording in the Status column of the "Restore Fields" page `?a=form_vue#/restore`.
Given the context of the page, "Deletion Date" implies it's a date when the user deleted the item. However the meaning is actually "Scheduled Deletion Date".
Also added a TODO item, since more consideration is needed when introducing structural changes to API responses.
Should be minimal since it's a verbiage change
> Leaf 4378 - Change wording

- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024052000-2024060200.sql
The main advantage of using a descending index here is that most views typically show the newest records on top. This provides a much better user experience, especially in the Report Builder, since we can quickly render the first set of records while the rest load in the background.
How does this impact performance elsewhere?
This might impact performance.
> Leaf 4382 - Switch to descending record index

- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/js/formGrid.js
- LEAF_Request_Portal/js/formQuery.js
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/templates/view_reports.tpl
- x-test/API-tests/database/portal_test_db.sql
- x-test/API-tests/formQuery_test.go
This will help us avoid potential issues in the future.
Originally when exploring this, it was thought that only MySQL <= 8.0.32 had issues with a descending records.recordID index. In the process of creating an automated test, it was apparent that no current version of MySQL supports this.
> Leaf 4392 - Add Test: Descending indexes apparently break things

- LEAF_Request_Portal/templates/view_reports.tpl
This updates the JSON dialog in the Report Builder:
- Remove 10,000 record limit
- Added "JavaScript Template" example
- "Copy to clipboard" button
Minimal because the changes are limited to the JSON dialog area.
> Leaf 4386 - Report Builder: Add example in the JSON dialog

- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024060700-2024062000.sql
This is associated with the overall story for 4373.  Separated out for easier tracking and deployment
DB upgrade file to add a userMetadata column to the portal action_history table.
> LEAF 4404 action_history userMetadata portal db upgrade file

- LEAF_Request_Portal/js/formSearch.js
- LEAF_Request_Portal/sources/Form.php
Adds a check for an existing join to category_count when searching for multiple form types in the report builder before adding to the joins clause.  Updates reference names where needed.
Issue can be reproduced on API Testing DB (or regular local if you have 8+ form types).
-Use the Report Builder to search for numerous (8+) form types (type is form 1 OR type is form 2 etc).
-From the resulting report, open one of the requests in another tab.
-Use the admin tools 'change form'.  Add multiple forms (4+) from the checkbox selection.
-Reload the Report Builder report.
The request with multiple forms associated with it will have a large number of duplicates DB side.  The front end will repeatedly query for more results and process thousands+ before the report finally …
> LEAF 4357 avoid multiple joins (INC33064668 report not loading)

- LEAF_Request_Portal/templates/reports/LEAF_Data_Visualizer.tpl
- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
- LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
- LEAF_Request_Portal/templates/view_reports.tpl
This updates the front-end `scrubHTML()` function to ensure that recursively encoded text does not bypass the scrubber.
At some point we'll probably want to make this a global function.
Precondition: Add a HTML link in a field's name. Leave the short label blank.
1. Navigate to the Report Builder
2. When viewing the field name in Step 2, you should not see a clickable HTML link
> Leaf 4398 - Update JS HTML scrubber

- LEAF_Request_Portal/admin/css/style.css
- LEAF_Request_Portal/admin/templates/mod_file_manager.tpl
- LEAF_Request_Portal/api/controllers/SystemController.php
- LEAF_Request_Portal/sources/System.php
This adds a "Last Modified" column to the File Manager.
API Change:
- `./api/system/files` now accepts the optional GET parameter `getLastModified`. When set, it includes the last modified time for each file.
- Impact due to API change mitigated via use of backward compatible $_GET flag
- CSS style for leaf_grid was updated in the admin area. This might actually indirectly fix styling for the LEAF Library, which can only be checked in pre-prod.
> Leaf 4401 - File manager: last modified date

- LEAF_Request_Portal/js/formGrid.js
- LEAF_Request_Portal/templates/view_reports.tpl
This shows the "loading" text a little earlier, and resolves a styling issue.
1. Navigate to the report builder
2. In Step 2, select as many columns as needed to overflow the horizontal scroll in the generated report
3. When the horizontal scroll overflows, scrolling down is supposed to invert the header's color
Minimal because this only presets the status text.
> Leaf 4403 - Loading UX

- LEAF_Request_Portal/templates/reports/LEAF_table_input_report.tpl
Updates the grid-splitter report to use formQuery methods to query the selection rather than getting data for each record.
Minor style updates.
LEAF Programmer built-in report: LEAF_table_input_report
Confirm that grid format question entries for submitted requests can be split into columns and downloaded
> LEAF 4402 update gridsplitter to use formQuery

- .gitignore
Summary:
*.key and *.jks were added to the gitignore file. I searched for various placeholder words and wasn't able to find anything that needed updating.
> Leaf 3143 - gitignore updated

- LEAF_Request_Portal/js/formGrid.js
- When navigating through column headers, screen readers will say "Sort by column [name of column]"
- Resolves aria-attribute mismatch @aerinkayne 
Specifically table headers on the Homepage and Report Builder
> Leaf 4397 - formGrid.js Accessibility improvements

- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024062000-2024071100.sql
- scripts/scheduled-task-commands/automatedEmailReminder.php
- scripts/scheduled-task-commands/automatedEmailReminderVAPO.php
This changes the automated email scripts that run daily to account for our VAPO migration when we will have two infrastructures operating at the same time. This is a preliminary action to avoid multiple emails going out from both infrastructures.
- Issues with automated emails going out
> LEAF-4426: VAPO Automated Emails

- docker/docker-compose.yml
- docker/nginx/src/index.html
- docker/php/ssmtp/ssmtp.conf
- docs/InstallationConfiguration.md
- Prevents mysql/smtp from auto starting
- Replaces Fake SMTP Server with smtp4dev
Only changes the dev environment
> LEAF-4428 Dev UX

- scripts/leaf-scripts/updatedbvers.php
This was where a db was not updating properly, one of the index's was causing the version to not update.
I created the script based off of our db checker to update the timestamp to the proper version. this checks to make sure we have the valid update that was requested. I did not check every entry just the last known good entry.
Testing was done on staging to confirm the update worked as expected. This is a command line script.
> LEAF-4447 - HOTFIX: DB version cleanup

- app/Leaf/VAMCActiveDirectory.php
- scripts/scheduled-task-commands/updateNationalOrgchartEmployees.php
- scripts/updateNationalOrgchart.php
Summary: In an attempt to speed up the updating of data coming from Active Directory here are the scripts to process the data from the scripts container rather than on the auth server.
Employee data is updated faster and more accurately.
Testing:
What I found in testing is the current process on staging takes about 7.5-8 hours to complete.
To get the data from AD and place in a table on the national_orgchart db it has consistently taken about 15 minutes.
From the scripts container on our server it has consistently finished in 30 minutes. 
Next steps:
I would think at this point we would want to put this on staging and add them to the nightly scripts and monitor them for a while before moving them to prod.
> Leaf 4376 - Processing AD Data

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/sources/Workflow.php
Fixes an issue that could cause the next step ID for a copied workflow to be -1 if the Step Info modal action list was used to connect sendback routes prior to copying the workflow.
This will also need some timely follow-up to look for and correct requests stuck in a -1 workflow state.
Workflow Editor
To reproduce this issue, complete the following steps without refreshing the page.
- select a workflow.  
- if the WF does not yet have one, add a route back to requestor
- click a mid-workflow step to open the step info modal
- use the left menu tools Copy Workflow button to copy the workflow 
- in Adminer, note that the nextStepID field for the new workflow is -1 instead of 0
Copies made on the fixed branch should copy as expected.  Adding routes with either the …
> LEAF 4363 fix potential workflow copy issue

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Resolves Inbox issue: When building the list of records, use the list of recordIDs provided by the function instead of using the full dataset.
Changes are isolated on the Inbox
> LEAF-4466 Hotfix/inbox

- LEAF_Request_Portal/sources/Form.php
- x-test/API-tests/formQuery_test.go
This implements the same solution in #2452 to avoid multiple joins on `records_workflow_state` and resolves a similar problem where searches on multiple stepIDs creates exponential database work.
An automated test has also been added to help validate the accuracy of query results.
Before (4.5s):
```sql
SELECT * FROM records
LEFT JOIN (SELECT * FROM records_workflow_state WHERE stepID=141) rj_stepID0 USING (recordID) 
LEFT JOIN (SELECT * FROM records_workflow_state WHERE stepID=357) rj_stepID1 USING (recordID) 
LEFT JOIN services USING (serviceID) 
LEFT JOIN (SELECT * FROM records_workflow_state) lj_status USING (recordID) 
LEFT JOIN (SELECT stepID, stepTitle FROM workflow_steps) lj_steps ON (lj_status.stepID = lj_steps.stepID) 
WHERE (rj_stepID0.stepID = 141 OR rj_stepID1.stepID = 357) …
```
> LEAF-4461 Optimize hotspot: avoid multiple joins

- LEAF_Nexus/scripts/refreshOrgchartEmployees.php
- x-test/API-tests/database/portal_test_db.sql
- x-test/API-tests/formQuery_test.go
Summary:
The nightly orgchart refresh was causing the employee's empUID to increment even though there wasn't a new record added. It was determined that this was because that table has an auto increment as well as a separate column that was unique. Testing the current script revealed that there were instances where the userName from the national orgchart and local orgchart were spelled differently case wise. This was causing an issue where the empUID from the local orgchart was not being included in the update query. So when MySql hit this record it would increment the db auto increment but when it tried to insert it hit the unique index and found a match and therefore updated that record. The auto increment still increased but would not be noticeable until a new employee was added.
The …
> Leaf 4449 - orgchart refresh plus tests

- LEAF_Nexus/sources/Employee.php
- LEAF_Request_Portal/admin/templates/mod_account_updater.tpl
This changes some prefixes when searching employees.
Before:
- username_disabled
- disabled
- disabled.user
After:
- username.disabled
Are the old prefixes used anywhere else?
> LEAF-4460 Improve syntax consistency

- LEAF_Request_Portal/sources/Workflow.php
Removes the check for a non-zero nextStepID during workflow copy, since other IDs are also valid for the 'sendback' (Return to Requestor) action type.
The bug associated with a potential -1 value should no longer be an issue.
Workflow Editor
Use a workflow with multiple steps.  If it does not have Return to Requestor actions to both Requestor and another step, add them.  Test adding the action with the connectors as well as with the step actions select box.
Open any step info modal.
Without refreshing the page, copy the workflow.
Confirm in adminer that the new workflow copied as expected (portal workflow_routes table).
nextStepID should be 0 if routed to the Requestor
nextStepID should be that of the step it routes to
Confirm API tests still pass
> LEAF 4467 fix step id checking

- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/admin/templates/menu.tpl
Adds a customTemplate function call for menu.tpl, which is the template associated with the top admin nav.
This will allow an alternate custom template for this menu on the small number of sites that need it.
Admin Top navigation menu.
- There should be no change if portal/admin/templates/custom_override/ does not contain a file called menu.tpl.
- When this file **is** present, the admin top nav should reflect the custom_override file and not the base file.
> LEAF-4469 (assoc 4463) add customTemplate call for admin menu

- x-test/end2end/tests/lifecycleSimpleTravel.spec.ts
- x-test/end2end/tests/reportBuilder.spec.ts
This adds a test that covers a known issue with the Report Builder, where we expect the report columns to maintain their order after modifying the report's filter.
Other minor changes:
- Improve the test locator for the `lifecycleSimpleTravel` test to improve repeatability.
This also serves as an example for how tests should be documented in situations where development of tests advances beyond the current UI development backlog.
- Since the underlying issue is unresolved, the test is implemented with the failing condition `test.fail` and annotated with a tag that references the issue.
- The tag must be prefixed with `issue:` to make it easier to search and identify.
- This prefix must not be used in the test's title.
- The example includes an actual issue #. To reduce development …
> End to end testing: Report Builder column order

- LEAF_Request_Portal/admin/templates/site_elements/generic_xhrDialog.tpl
- LEAF_Request_Portal/js/dialogController.js
- x-test/end2end/playwright.config.ts
- x-test/end2end/tests/lifecycleSimpleTravel.spec.ts
This works towards resolving an issue identified during automated testing, and is described in more detail here: https://playwright.dev/docs/navigations#hydration
The issue is that buttons can be clicked before an event handler is assigned to it, which results in nothing happening when the button is clicked.
This updates one of the admin's dialog templates to implement the solution described in Playwright's documentation.
Additional minor changes in tests:
- Reduced an operation in `lifecycleSimpleTrave.spec.ts` that was used as a part of a workaround for the previously described issue.
- Enabled test retries (up to 2 total runs per test) in order to highlight potentially flaky tests and minimize their impact on dev velocity
This solution will also need to be implemented in the remaining …
> LEAF-4498 - Mitigate dialog button race condition

- docker/mysql/db/db_upgrade/orgchart/Update_OC_DB_2023092100-2024092100 .sql
Summary:
This is to prepare the database to accept a longer userName for those that need to be disabled.
The biggest thing is this will allow us to keep users even after they are no longer with the VA and their userName is recycled and given to someone else.
Testing:
Go to the Nexus
Click on the OC Admin Panel
Click on Other Tools
Click on Update Database
Verify in the database that the field size was increased for expected tables.
> Leaf 4501 - Database update

- LEAF_Nexus/js/employeeSelector.js
- LEAF_Nexus/js/groupSelector.js
- LEAF_Nexus/js/positionSelector.js
- LEAF_Request_Portal/templates/subindicators.tpl
Associated with Help Desk INC34511903, where a user noticed that some requests would contain the incorrect value for orgchart group questions that were prefilled using ifthen logic.  Issue was found to be independent of ifthen functionality and due to rare prefixID collision of the orgchart selectors.
This update adds a method to orgchart selectors that first checks that an element associated with a generated ID is not already in the DOM before returning it for use as the prefix ID.  AJAX option async: false was also added when an orgchart class needs to be imported (it would otherwise import multiple times).
Group, Position, and Employee selectors.
- Confirm these continue to work normally.  
- ID collision, it might be easiest to locally edit the value of the …
> LEAF 4476 prevent orgchart selector ID collision

- LEAF_Request_Portal/js/formGrid.js
- app/libs/js/LEAF/formGrid.js
- libs/js/LEAF/formGrid.js
We received feedback from the 508 audit team about a label being added to the formGrid tables to ensure screen-reader users knew that they need to press escape before trying to use table layer nav from a header.  They thought this _should_ be adequate but that it might be preferable if this aria-label were on the thead rather than the table element.
There is also an issue re-introduced at some point where aria-labels for sortable headers could contain html and/or quotes.  This can cause the label to read incorrectly and/or affect the header display if html is truncated.
Changes should be limited to screen-reader output and some rare custom header content.  General regression-testing of formGrid tables should still be undertaken.  Some testing requires a screen reader …
> LEAF 4505 move aria label and address truncation issue

- LEAF_Request_Portal/admin/templates/site_elements/generic_OkDialog.tpl
- LEAF_Request_Portal/admin/templates/site_elements/generic_confirm_xhrDialog.tpl
- LEAF_Request_Portal/admin/templates/site_elements/generic_simple_xhrDialog.tpl
- LEAF_Request_Portal/js/dialogController.js
- LEAF_Request_Portal/templates/form.tpl
- LEAF_Request_Portal/templates/reports/LEAF_start_leaf_dev_console_request.tpl
- LEAF_Request_Portal/templates/site_elements/generic_OkDialog.tpl
- LEAF_Request_Portal/templates/site_elements/generic_confirm_xhrDialog.tpl
- LEAF_Request_Portal/templates/site_elements/generic_xhrDialog.tpl
- x-test/end2end/README.md
- x-test/end2end/playwright.config.ts
- x-test/end2end/tests/lifecycleDeveloperConsoleApproval.spec.ts
- x-test/end2end/tests/lifecycleSimpleTravel.spec.ts
Note: This does not need to be rolled out as a hotfix, because functionality is not impacted.
This PR:
- Resolves an error message that shows up in the JS console during the LEAF Developer Console approval workflow
- Added automated test that reproduces the issue, and checked for validity against `rc/2024-08-27/Sprint-80-c2`
- Also resolves a JS warning on the same page
- Expands the work to mitigate page hydration issues from https://github.com/department-of-veterans-affairs/LEAF/pull/2532
- Reduces test flakiness
- `x-test/end2end/tests/lifecycleSimpleTravel.spec.ts` now checks the results of a key async request. Previously, the UI would occasionally render two workflows on the screen during repeated test runs.
Similar to #2532: 
> pages that utilize [dialog templates] depend on the …
> Resolve JS error (dev console approval), Improve tests

- LEAF_Nexus/js/ui/position.js
- LEAF_Nexus/templates/editor.tpl
- LEAF_Nexus/templates/navigator.tpl
Nexus Orgchart navigator and editor
Page needs a number of improvements
Additional info to user on overview page about what the page is conveying and what can be edited (brief ok)
Drag behavior in the editor should be available from keyboard
Tab order at least appears unintuitive. There is a number associated with each cell that might mediate this. Tabbing should be tree breadth so presentation alone might resolve this
Doublecheck how / when associated dropdowns collapse - tabbing away and full mouse off should close them
These changes should make it easier for people to navigate the orgchart navigator and editor with the keyboard.
Testing:
Open the orgchart and click browse.
using only the keyboard tab through the page. Once you get to the different positions they …
> Leaf 4465 - 508 keyboard navigation updates

- scripts/leaf-scripts/update_records_notes_dh_fields.php
Associated with 4507, which will update LEAF code base to start posting to new fields notes.userMetadata, records.userMetadata, data_history.userDisplay.  These fields will be NULL for prior values until updated by script.
Script needs to be confirmed as correctly updating fields locally.
> LEAF 4522 update script for notes, records, data_history fields

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Address an issue where a step title would have encoded characters when a workflow was copied.
Uncovered: fix error that would occur when a workflow was deleted due to url param for a workflow that no longer exists.
Workflow Editor - Copy Workflow feature
-Confirm API tests pass/regression
(if playwright has been recently updated, you might need to bash to playwright container and run npx playwright install.  Test trace will indicate if this is needed).
-Confirm workflow copying works as intended.
-There should be no console error when a workflow is deleted
> LEAF 4523 (INC35162350) fix workflow copy step title encoding

- scripts/automatedEmailReminder.php
- scripts/refreshOrgchartEmployees.php
Remove the ini_set that was overriding system default for display errors. Also removed error_reporting line since this too overrode the server default setting.
> HOTFIX: LEAF 4450 - deprecated warnings

- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024100300-2024101500.sql
**Description:**
This database change is intended for the final migration of launchpad.
Its purpose serves to make it so isVAPO boolean in the sites table is marked as true by default on portal creation.
**Impact:**
Minor Impact to LEAF site creation, avoid misinformation of portal creation.
> VAPO: Full Migration isVAPO true default

- health_checks/index.php
Summary:
A liveness probe is needed to check that all is up and running. If not things need to be restarted.
> Leaf 4564 - liveness probe

- LEAF_Request_Portal/css/printer.css
**Issue**
Images were not allowed in the print to pdf, so for example the image upload would not show when printing a pdf using the browsers print to pdf functionality. 
**The fix**
Adjusted print style sheet to allow images within the request.
** Other Issues Fixed **
- Skip to content link
- First section item was pushed over
**New**
**Old**
**Testing**
- Upload an image to a form
- Using the browsers print preview you should now see the image in view to print
> LEAF-4577 - Print to PDF Image

- scripts/leaf-scripts/update_records_notes_dh_fields.php
Adjustments made to the script to update records.metadata, notes.metadata and data_history.userDisplay.
One batched pull to get required information from national instead of per orgchart (all updates here are associated with the userName value and do not require local nexus level queries).
Portals are ordered by sites.id to make multiple limited runs possible (currently still the tentative solution for the data_history table).  
Requests for userID rows and the number of updated rows have hard limits (previously, these queries affected a very highly variable number of rows).
Distinct / ordering is avoided SQL side to try to simplify the query. 
Memory impact SQL side is still significant for the data_history table.
> LEAF 4552 metadata field update optimizations

- LEAF_Request_Portal/sources/Email.php
- LEAF_Request_Portal/sources/FormWorkflow.php
This was specifically in the title but it was anything in the content of the email. So text fields and other data that was requested to be shown could have this issue.
Windows Special Character Keyboard
https://www.theverge.com/22351023/windows-pc-special-characters-how-to
Linux Special Character Keyboard
https://forums.linuxmint.com/viewtopic.php?t=347624
Testing
- Setup a workflow that sends an email
- Make sure the form has a text field 
- Make sure the email has a text field and title in it
- Fill out a form and run it through the step that would send an email
- Check the email to make sure it shows proper text
Example Of Failure:
Example Of Success:
> LEAF-4584 - Special Character in request email not displaying correctly

- scripts/leaf-scripts/update_records_notes_dh_fields.php
Basing against rc 2024-11-20 for now since this is a further update to the metadata script.
This modifies the portal query to match VAPO migration schedule, where possible.
(There are 3 portals at base paths that require a slightly different query).  Batch to update is specified by cmd.
Local testing portals are included in batch 0 with other base paths.
num_portals --- directories
3-----		resources_mtsbg, awards_mtsbg, launchpad 
10----		SWARM, Academy
110---		200, 504, 660, 662CRH, 693, 695NA, ASTEST, ASTESTSITE2, ASTESTSITE3, CRH, CSP, DEU, DEV, Dev, DevSecOps, HLTI_10A2E, LEAF, LGYC, OAWP, OEHRM, ORD, Other, platform, TEST
80-----		HAMVAMC, HAM, ham, Innovations, NCA, OIT, OIT_DAPM, OIT_OPS, ProjectManagement, SBY, VACI, VACO
326---		VBA, VISN0, VAMHCS, vamhcs, inde, demo, charleston …
> LEAF 4603 metadata prior vals, records notes, batch by paths with arg

- LEAF_Request_Portal/templates/reports/LEAF_Data_Visualizer.tpl
Fixes parameter order for method 'addDataTerm' used in the Data Visualizer.
Data Visualizer
Portal Admin -> Data Visualizer
Choose a Form Type
Choose Edit Filter
Add Filter 'Data Field ...'
Test with 'Any Standard Data Field' or with a specific indicator selection (choose from updated dropdown)
Data Terms should be searchable and return expected results.
> LEAF 4602 fix data visualizer addDataTerm param order

- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/admin/templates/main.tpl
- LEAF_Request_Portal/admin/templates/menu.tpl
This will attempt to resolve a navigation consistency defect brought up by the most recent 508 audit.
Removes user menu and an associated script from the portal admin menu.
Adds Welcome and Sign Out link similar to that found on the non-admin portal pages.
Other/Comment:
Portal admin side 'login' template and its associated variables do not appear to be used, but this has been left untouched until further feedback
Portal admin side header - appearance and link functionality.
> LEAF  4601 - admin menu 508 fix

- LEAF_Request_Portal/ajaxJSON.php
- LEAF_Request_Portal/api/controllers/FormController.php
- LEAF_Request_Portal/js/form.js
- LEAF_Request_Portal/sources/Form.php
The current Form getProgress method still compares a flat array of required questions with data entries in order to determine form progress percentage.  Individual questions account for direct conditional logic.  However, since there is no information about form structure, using conditional logic when the conditional indicator has required sub-questions is problematic / tedious because the logic needs to be repeated on the subquestion.
This update will take form structure into account (when needed) during the progress count so that any ancestor in a hidden state is sufficient.
**Front end:**
Updates to form.js to handle conditional display states and to toggle front end validation for required questions
**Server-Side:**
Updates to form method getProgress to account for structure. …
> LEAF-4604 update form progress checking to account for conditional logic

- LEAF_Nexus/css/editor.css
- LEAF_Nexus/js/ui/position.js
- LEAF_Nexus/templates/editor.tpl
This element displaying keyboard instructions has been moved to the right side under the editor buttons where it is less likely to overlap with position cards.  It will also not show unless a card is being moved by keyboard arrows.
When it is showing, there is a checkbox available to hide the additional information (pending some feedback - it might be fine to remove this since the keyboard info will not usually show)
Other:
minor UX update to re-paint connectors after a position is saved if a card has been moved by keyboard
This update is specific to the orgchart editor (Nexus -> browser -> edit orgchart)
Keyboard instruction location has been moved and should not display unless a card is being moved with keyboard arrow keys.  Confirm that card behaviors have not …
> LEAF 4597 - move orgchart keyboard info banner

- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/sources/FormWorkflow.php
- LEAF_Request_Portal/sources/View.php
- LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
- LEAF_Request_Portal/templates/view_reports.tpl
- LEAF_Request_Portal/templates/view_status.tpl
Uses data saved in the new metadata and userMetadata columns to replace display related orgchart lookups.
Lookups are still used for requests pending direct action and for emailing.
**server side:**
Replaces lookupLogin calls with available metadata.
Replaces an orgchart join when getting initiator information with Report Builder queries
**front:**
data.metadata
Form print view, Report Builder. Display of user info associated with orgchart employee format data entries.
For orgchart_employee format entries with metadata, the entered user name will continue to display even if the associated account is disabled. Accounts disabled prior to metadata entry will continue to display disabled account information.
action_history.userMetadata
Request history modal, Report Builder (Approval History, …
> LEAF 4455 metadata reading (ao 121224)

- LEAF_Request_Portal/templates/subindicators.tpl
Fixes an issue that caused error messages associated with file upload formats (files, images) to remain hidden.
File upload, images format request question types.
- Attempt to upload a file or image greater than 20MB
- Attempt to upload a file or image with a malformed suffix (for example .txtx, .pngg)
A suitable error message should be displayed for file upload related errors.
> LEAF 4543 fix display property on file upload error response

- LEAF_Request_Portal/admin/css/mod_templates_reports.css
Updates a CSS definition that had been causing email template subject and body full screen modes to display incorrectly.
Admin -> Email Template Editor
F11 (depending on computer, fn + F11), should toggle full screen display with 100 view height.
> LEAF 4600 (INC36349916) - email editor CSS update

- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/templates/subindicators.tpl
Orgchart group and orgchart position format questions can display incorrectly (false) or oddly (--) in the report builder if the group or position associated with the data entry is not found.
server-side:
Value that is set has been updated so that the Report Builder cells will display nothing if a group or position value is empty and 'group/pos #id no longer available' if it is not empty but the group/pos is not found by lookup.   For positions, further lookups are also not completed if the initial position title lookup does not find a position.
front:
Adds some logic to form editing areas to avoid additional lookups if a position title is not found and displays 'position #id no longer available' instead of 'false' and a position card with a link to a broken page. …
> LEAF 4258 orgchart group and position, fix report builder display when not found

- LEAF_Request_Portal/js/dialogController.js
- LEAF_Request_Portal/sources/FormStack.php
- LEAF_Request_Portal/templates/print_subindicators.tpl
- LEAF_Request_Portal/templates/subindicators.tpl
Address some common errors logged in Dynatrace (frontend JS)
1) Prevent a ReferenceError in the LEAF Inbox that occurs if the quick view is displayed
2) Prevent a TypeError that can occur when the dialogController attempts to modify attributes of the cancel button.
3) Prevent a TypeError that could occur due to an incorrect indicators.conditions value.
When the Conditions Editor was released, a brief issue caused form packets to be exported with indicator.conditions set to 'null' instead of null.  This update handles this value for existing forms and prevents it from being set if a form packet that has the value is imported.
1) Inbox 
Open any form quick view.  Dev Console Reference Error should no longer occur.
2) Potentially anywhere dialogController is used.  This …
> LEAF 4623 address common logged errors (javascript)

- scripts/scheduled-task-commands/disableNationalOrgchartEmployees.php
When testing on staging I ended up moving this file and didn't change a reference to the globals.php file. I found it out when I was testing again after the push to staging. This is just to correct that.
> Leaf 4376 missed reference

- LEAF_Nexus/sources/Employee.php
Summary:
A way was needed to prevent Active Directory userNames from being recycled and showing data to the wrong person.
Currently there are userNames that have already been recycled. These will get missed and need to be done manually when they come up.
Disabling a user one at a time will use the same process but re-enabling them needs to be programmed yet.
Testing:
This will need to be done on staging. It is possible to set up local to do this I think but it is not currently done. Staging should be set and ready to do this.
To test just run the refreshOrgchartEmployees.php. All instances of userNames in all tables that store the userName in both the orgchart and any portals for that orgchart should be updated to the new format. disabled_ts_userName
> Leaf 4486 - prevent user name recycle

- app/Leaf/VAMCActiveDirectory.php
When moving the script from auth server to vapo server a function was omitted that shouldn't have been. It needs to be added in and the domain formatted correctly before saving.
Testing: 
Run the script to update national orgchart from AD
verify that the domain in the employee table is formatted correctly
> Leaf 4631 - update domain formatting on save

- LEAF_Request_Portal/api/controllers/FormEditorController.php
- LEAF_Request_Portal/templates/reports/LEAF_import_data.tpl
- app/libs/js/portal/LEAFPortalAPI.js
Add null coalesce to where parentID POST value is used.  At some point this started causing new form creation to fail (method seemed to be getting explicit null, and parentID cannot be null).
Add a call, abstracted within the portal API createCustomForm method, to update the form visible value to 0 after it is created.  New forms have a default visibility of -1 (unpublished) and requests cannot be made for them.
Admin -> Toolbox -> Import Spreadsheet
Confirm that new forms and associated requests can be created using the report interface and an excel template with headers and data.
Confirm requests for existing forms also continue to be created as expected.
> LEAF 4620 import spreadsheet - new form

- LEAF_Request_Portal/sources/Form.php
Re-add empUID in custom data section.
Associated Go update is under
https://github.com/department-of-veterans-affairs/LEAF-Automated-Tests/pull/36
Create a Report Builder report that gets orgchart formats (with entries).  Use JSON button to get query url and open it in a new tab.
empUID should exist on the associated id__orgchart objects.
Associated Go test above should pass on this branch.
> LEAF 4639 - custom data orgchart empUID

- LEAF_Nexus/sources/Employee.php
When re-enabling a user their userName gets deleted. The reason is because when we pulled 4486 back the reenabling code didn't get changed back to it's original state.
Testing:
Disable a user
Enable a user
userName should still be in the record.
> Hotfix -Leaf 4640 - enabling user deletes user name

- LEAF_Request_Portal/js/workflow.js
This resolves an issue in workflow.js where subsequent calls to workflow.getWorkflow() don't render inlined form fields correctly.
Automated test added: https://github.com/department-of-veterans-affairs/LEAF-Automated-Tests/pull/38/files#diff-fec443a7fb26885985db23970be7c5dc8cade8533e013fc6948fb080fd4f53d7
Minimal because this resolves an incomplete if-else clause.
> Leaf 4647 - Fix subsequent JS getWorkflow() calls

- LEAF_Request_Portal/admin/css/mod_templates_reports.css
- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
- LEAF_Request_Portal/sources/EmailTemplate.php
- LEAF_Request_Portal/templates/email/LEAF_automated_reminder_body.tpl
- LEAF_Request_Portal/templates/email/LEAF_cancel_notification_body.tpl
- LEAF_Request_Portal/templates/email/LEAF_mass_action_remind_body.tpl
- LEAF_Request_Portal/templates/email/LEAF_notify_complete_body.tpl
- LEAF_Request_Portal/templates/email/LEAF_notify_next_body.tpl
- LEAF_Request_Portal/templates/email/LEAF_send_back_body.tpl
- LEAF_Request_Portal/templates/email/base_templates/LEAF_template_body.tpl
This update adds the Trumbowyg text editor to the Email Template Editor.  Users will be able to toggle between the CodeMirror and WYSWYG inputs.
It was found that the 'Default Email Template' is not used through the email template editor.  This template is used from templates/email/LEAF_main_email_tamplate.tpl (not custom_override).
A query in EmailTemplate.php has been updated to exclude this template from the Email Template Editor.
The Email Template Editor has also been updated to display 'Notify Next Approver' as the default view.
Portal Admin - Email Template Editor
Email editing from either CodeMirror or WYSWYG Text Editor should function as expected.
Page navigation should function as expected.
> LEAF 4634 - email editor wyswyg

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/sources/View.php
- LEAF_Request_Portal/sources/Workflow.php
- LEAF_Request_Portal/sources/WorkflowRoute.php
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024112500-2025020100.sql
**Description**
If a request initiator is changed, a request step is changed, or a request is cancelled, the Request History modal displays
'Action by username'.  Step change and initiator change include additional comments to clarify the action.  Cancel does not, which makes what has occurred unclear.  In the report builder, the approval history displays as 'null' for these changes.
This update adds 'move', 'changeInitiator', and 'deleted' actionTypes and associated text to the actions table.
These actionType names correspond to the entries that are already added to the actions_history table.
Prod was queried for existing custom workflow actions.  One active 'Move' actiontype was found and updated to MoveRequest.
-----
**Request History modal** should show the below …
> LEAF 4625 - history/approval info

- LEAF_Request_Portal/js/workflow.js
The earlier fix (adding async) did not look like it completely resolved this issue, as there still appears to be issues saving data when multiple requirements are on the step.
This branch removes the new 'else' statement as well as the async: false config.
> remove new else and async false config

- LEAF_Request_Portal/js/workflow.js
Adds some comments to drawWorkflow to clarify that it is potentially called multiple times and that its step param also includes dependency information.
Adds a param to drawWorkflow to identify the requirement that the form fields are loaded to.
Fields are only loaded on the first requirement - running init on more than one was associated with breaking things.
The else clause has been updated so that it should reinit the module if
-it is already flagged as loaded and
-the depID/requirement currently being drawn is also the first one.
Updates ajax config object callback name to 'error'
This item impacts request workflow fields.  If these fields do not load or otherwise function correctly, the workflow process could be stopped and/or data could not correctly save. …
> LEAF 4664 workflow module loading issue

- LEAF_Request_Portal/admin/templates/mod_templates.tpl
- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
- LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
- LEAF_Request_Portal/sources/Applet.php
- LEAF_Request_Portal/sources/TemplateFileHistory.php
Updates template editor areas to take an initial snapshot of current content if a template is saved and there are no history snapshots yet to ensure original state also has a recorded snapshot. 
Server side
Template file history and applet history have a template prefix added with uniqid instead of with time.
The addition precision is needed to potentially take two snapshots in rapid succession.
Email template editor already used uniqid.
Updates a query to sort by file_id DESC instead of by the file_created text field to ensure file history list appears in the expected order.
Front:
Adds a check for file history and performs ajax call to snapshot history of the current content if necessary.
Disables save button during the save process to prevent multiple clicks.
Removed a div nested in a …
> LEAF 4203 - dev initial snapshot on save

- LEAF_Request_Portal/login/index.php
On the login page the icon was not loading and resulted in errors in our error reporting system
Adjust login page to load in the proper ico
> LEAF-4658 - VA Favicon loading error

- LEAF_Request_Portal/templates/print_form.tpl
Adds template logic and submit success logic to print_form so that the Cancel Request button does not display unless the form is not submitted, or the user is an admin.
Cancel button should be visible if a request is not submitted.
Cancel button should not be visible if a request is submitted unless the user is an admin.
Cancel button should become hidden after being submitted unless the user in an admin.
> LEAF 4667 add cancel button template logic

- LEAF_Request_Portal/js/form.js
Fixes a logic check associated with front end validator reset.
See Jira-4669 for an example form.
Impact should be minimal since this is a correction to intended logic
Issue occurs when
-A controller question triggers a branch check.
-Another controller question is in a separate branch than the question(s) it controls
-The questions it controls are required, and in the branch initially checked
-The controller is in a hidden state (so it cannot be interacted with to re-trigger a validator swap)
> LEAF 4669 required validator reset logic correction

- LEAF_Request_Portal/js/pages/mass_action.js
- LEAF_Request_Portal/templates/reports/LEAF_mass_action.tpl
Adds a textarea where comments can be added for a cancel mass-action event.
This is the only mass-action event associated with comments
Per feedback, this section is now required when mass-cancelling requests.
Portal admin -> Toolbox -> Mass Actions Report
The new textarea should show if cancel is chosen.
A comment must be provided in order to perform this action.
The 'required' notice near the comments section will be highlighted if comments are not entered.
Comments should show in the respective request histories.
> LEAF 4615 add textarea for comments when mass action is cancel

- LEAF_Request_Portal/js/formGrid.js
- app/libs/js/LEAF/formGrid.js
On export, there is an endpoint call to pull indicator format information to avoid some issues with excel exports.
The orgchart does not have this endpoint, which results in a breaking error when attempting to export vacancy summary.
This update adds a try catch block so that potential errors will not affect the export.
It also adds pattern checking of the exported header ids to avoid trying to get format information if indicator patterns are not present.
Impact/Testing
formGrid export should work wherever it is used (Nexus Vacancy Summary page, Report Builder, Account Updater, Custom Reports)
> INC37469608 LEAF 4661 catch nexus side export error

- docker/php/php-dev.ini
Allow php to show error messages for docker log. 
Previously error_log and other messages would not be put out to `docker logs leaf-php-fpm-1` now it will output errors, see "moo" below.
This will only affect local development
> PHP Docker Logs

- LEAF_Nexus/scripts/updateNationalOrgchart.php
- LEAF_Nexus/sources/Employee.php
- app/Leaf/VAMCActiveDirectory.php
- docker/php/leaf_monlith.dockerfile
- scripts/scheduled-task-commands/disableNationalOrgchartEmployees.php
- scripts/scheduled-task-commands/refreshOrgchartEmps.php
- scripts/scheduled-task-commands/updateNationalOrgchartEmployees.php
Summary:
The old script, which resides on the Auth server processed all Active Directory updates to Leaf. Now the Auth Server will get the data from AD and save it to a table (cache) in the National Orgchart. Then a cron job on Leaf servers runs to update Employee and Employee data in the national orgchart. After this update is complete another script runs to disable Employees that have not been updated within the last 30 hours. 
For the purposes of this PR an Employee is considered disabled if their record in the National Orgchart hasn't been updated within the last 30 hours. Every Employee has a lastUpdated field and this gets updated whenever the first script runs to update Employees whether or not they had data to be updated, if it hasn't been updated they were not pulled from AD …
> Leaf 4663 - refactor ad to leaf updates

- LEAF_Request_Portal/templates/print_form.tpl
- LEAF_Request_Portal/templates/print_subindicators.tpl
- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
This moves the method used to find-replace URLs to parent template print form to prevent the code from being associated with more template sections than intended.
This was noticed because it modified code behavior for a user getting jquery element text() through selector #xhrIndicator_id.
This is not a consistent selector regardless, so I am not sure what test modifications specific to this feature should be made.
A wrapper check has also been added prior to the function call, since portals with custom print-form templates will not have this method.
> LEAF 4687 move url method to parent template

- .gitignore
- LEAF_Nexus/api/controllers/PlatformController.php
- LEAF_Nexus/api/index.php
- LEAF_Nexus/index.php
- LEAF_Nexus/sources/Platform.php
- LEAF_Nexus/templates/view_group.tpl
Summary:
Currently, If you go to the nexus and search for a group and view the group. When you click on a tag name a popup will ask if you are sure you want to remove the tag. It doesn't matter if the group is still in the portal or not, the tag will be removed.
With this PR, when you click on the tag name the system checks that the group is no longer in the portal that was clicked. If it does exist in the portal a message will appear telling the user that the tag cannot be removed until the group is removed from the portal. If it does not exist in the portal the user will be asked if they are sure they want to remove the tag.
```mermaid
graph TB
subgraph Nexus
group(Group)
end
subgraph Platform API
platform_api(return all portals<br>for orgchart)
end
subgraph Frontend
script(process …
```
> Leaf 4571 - nexus cant delete tag unless removed from portal first

- LEAF_Nexus/api/controllers/PlatformController.php
- LEAF_Nexus/index.php
- LEAF_Nexus/sources/Platform.php
- LEAF_Nexus/templates/view_group.tpl
This PR is in lieu of #2682 - nexus can't be delete tag unless removed from portal first and makes adjustments to the script to allow orphaned tags to be removed.
#2682 - nexus can't be delete tag unless removed from portal first, added a new Nexus API endpoint 'api/platform/portal' see this PR for further details.
> Leaf 4571 - nexus tags only delete when not used

- app/Leaf/VAMCActiveDirectory.php
This change helps Help Desk in that new users will get imported into Leaf from AD where previously they were not.
Help Desk should see a decrease in the number of requests to manually import users from AD
Run the nightly script to import users from AD
Any new users should be in the National Orgchart
> Leaf 4702 - update AD importer

- LEAF_Nexus/api/controllers/PlatformController.php
This change addresses a use db_name command that doesn't work when a db_name has a dash in it. 
This allows portals with dashes in the db name to use the delete tag api endpoint.
Once released go to a portal with a dash in the name (more specifically in the db name) attempt to delete it's tag from the nexus group area.
> Leaf 4704 - hotfix use db

- docker/playwright/playwright.dockerfile
This avoids an issue in the development environment, where on first run, the end2end test suite would error with "Looks like Playwright Test or Playwright was just installed or updated...".
The changes are limited to the development environment.
After deleting all development docker volumes, containers, and images, following the instructions in https://github.com/department-of-veterans-affairs/LEAF/blob/master/docs/InstallationConfiguration.md results in a working environment. Then, following prompts to run the end2end test suite should not result in any errors or failures.
> LEAF-4707 Avoid playwright warning

- LEAF_Request_Portal/templates/reports/LEAF_import_data.tpl
The initial scope of this update was to add the interval queue to the Toolbox - Import Spreadsheet (LEAF_import_data ) utility report.  Unlimited rates would cause imports with a large number of rows (~1000+) to fail on production.
The scope was expanded to resolve column order issues, fix an unresolved promise that would stop the import process, and add a needtoknow update if a question on a new form is marked as sensitive.
Minor template logic was also added to restrict display of the 'new form' choice to admins.
All changes are to the front end LEAF_import_data template file.
This update affects the portal admin Import Spreadsheet utility.
Users with a moderate-large number of updates (~1000) will find that the process is slower.
This should correct breaking issues for imports with a …
> LEAF 4685 - limit data importer requests with interval queue

- LEAF_Request_Portal/ajaxIndex.php
- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/report.php
- LEAF_Request_Portal/sources/Login.php
This resolves an issue where new users who visit a site see a "session expired" message. 
This refactors some logic out of `loginUser()` into a new `requestAuthentication()`. The old logic shows the error message because the local Nexus doesn't contain an active reference to the user.
The new logic transparently routes them through the authentication process, which creates an active reference in the local Nexus, and avoids the error message.
This potentially has high impact for user logins and automated scripts. Pre-prod testing is required to help mitigate potential issues.
1. Navigate to a Site's homepage, and click "Logout"
2. Manually edit the site's Nexus database's employee table, and change your account's `deleted` field to 1
3. Navigate to the same homepage again
4. You should see …
> LEAF-4714 Redirect "inactive" users through authentication path automatically

- LEAF_Request_Portal/auth_cookie/index.php
I messed up the branch name, it should have been called Power Bi Gateway, this doesnt really have to do with large query besides none of this works even without the large query changes in place.
Currently if the user is in the national orgchart and you try and request data through power bi, power query or through a power bi gateway it will never get the data. In power bi and the gateway it will return with "We reached the end of the buffer" which would lead you to believe data would have issues and not authentication, however it is failing the authentication and returning an empty data set.
The issue is when the system is authenticating it is also requiring an email. A service account does not have an email address attached so the check for this causes it to fail. I have adjusted this to …
> LEAF-4653 - Power BI/Power Query/Gateway Authentication Issues

- docs/InstallationConfiguration.md
update for installation, right now I think this may not be seen by 100% of people but could be something that is seen by users
How does this change help the customer or platform?
This is documentation updates to include notes on if you receive an error while building, depending how the system is setup you may receive this message.
This is a help documentation that should help people get around possible errors
N/A
> LEAF-4727 Documentation: docker compose build on new docker desktop

- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/sources/FormWorkflow.php
- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This improves load performance for the Inbox's "Organize by Roles" mode by ~27% in testing, and up to ~80% in a site containing 2.5k pending requests:
```
│ before.txt  │              after.txt              │
│   sec/op    │   sec/op     vs base                │
Inbox_adminActionableRoles-24   138.8m ± 2%   101.3m ± 4%  -27.06% (p=0.000 n=10)
```
The improvement is achieved by leveraging the `data.metadata` column to retrieve information (first/last name, email), which avoids needing a query for each unique user in the set.
Since this closes the remaining advantage of the old Inbox, this PR also discourages use of the old Inbox. Visitors are redirected to the current one. In the event something is overlooked, the old inbox remains accessible at a new link: `PORTAL_URL/?a=inbox_old`
This …
> LEAF-4725 Optimize query used in Inbox: Organize by Roles

- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
- LEAF_Request_Portal/sources/Email.php
- LEAF_Request_Portal/sources/FormWorkflow.php
This update helps ensure sensitive data is not potentially displayed in emails.  The values of the 'fullTitle' and 'truncatedTitle' variables in the email template normally refer to the user-entered request title.  These values are replaced with the type of form if the form's need to know setting is turned on.
Since it has been requested by users in the past, formType has also been added to available smarty variables.
Users should be notified of this update.  Template variables 'fullTitle' and 'truncatedTitle' will have unexpected values if the form's need to know setting is on.
Within emails:
- If need to know is off, fullTitle and truncatedTitle should contain the title of the specific request.
- If need to know is on, fullTitle and truncatedTitle should contain the type of form …
> LEAF-4700 - if need to know is enabled, replace request titles in emails with the type of form.

- LEAF_Request_Portal/sources/Form.php
This resolves an issue in https://github.com/department-of-veterans-affairs/LEAF/pull/2708 identified during pre-production testing.
If the current user isn't serving as a backup for another, the local cache is never initialized which causes duplicate database calls.
Same as PR#2708
Same as PR#2708
> LEAF-4726 - Followup to PR#2708: Fix variable assignment

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This is Phase 2 of https://github.com/department-of-veterans-affairs/LEAF/pull/2714, which improves feature parity with the old Inbox, resolving:
- Collapse individually assigned records in admin view
- The old inbox collapsed these requests (e.g. requestor followup, person designated) in a single collapsible section
The name of the assigned person will now show up in the Status column in the new collapsed group, as it would otherwise be hidden.
- When viewing the Inbox (Organize by Roles, View as Admin), individually assigned records are consolidated into a section: "Assigned to an individual"
- When viewing the Inbox (Organize by Roles, View as Admin):
1. Open the "Assigned to an individual" section
2. Open the "Group A" sections
3. For records that exist in both …
> HOTFIX: LEAF-4756 Improve feature parity with the old inbox pt2

- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This resolves a feature regression with the Inbox introduced in https://github.com/department-of-veterans-affairs/LEAF/pull/2716, where v2 would not combine individual users in the "Organize by Roles" view.
Following community feedback, all 5 permutations of Inbox views have been integrated:
1. Organize by Forms (Default for v2)
2. Organize by Forms, Admin
3. Organize by Roles
4. Organize by Roles, Admin
5. Organize by Roles, Admin, Combined Individuals (Only option for Original Inbox)
Since the default for the original is # 5: The original URL, `index.php?a=inbox`, will redirect to that one.
The feature regression from https://github.com/department-of-veterans-affairs/LEAF/pull/2716 caused an issue with # 4. This PR restores # 4 and implemented # 5.
The community may need to be reminded …
> LEAF-4762 - Inbox: Add option to combine individuals

- LEAF_Request_Portal/admin/index.php
Adds the portal formGrid.js file for future use in the Form Editor.
Adding this prior to 4705 will ensure it is available.
No expected impact - adds a javascript file for future use.
Regression testing.  Check network log to confirm formGrid file is part of the Form Editor content.
> LEAF-4731 (dependency for LEAF 4705) add formGrid js file to Form Editor view

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This enables customizable columns in the "Organize by Role" view, for a specific condition within the Inbox.
Since the Role-based view can potentially include more than one type of form, custom columns are normally disabled. However if all records within the section contain the same type of form, then we can enable the columns.
Changes are limited to the "Organize by Role" section in the Inbox.
New automated test: https://github.com/department-of-veterans-affairs/LEAF-Automated-Tests/pull/79
> LEAF-4771 - Role-based Inbox: Enable custom columns in specific conditions

- LEAF_Request_Portal/templates/view_reports.tpl
This resolves a potential issue where a report would appear incomplete.
The issue is due to an undefined variable, and missing check. This issue is also highly unlikely to appear in normal operation, as it requires a form to be fully destroyed, which is not possible using the Admin interface.
No dependencies outside of the report builder
- This can be tested in the Demo1 site because its database has been manually modified.
1. Navigate to Admin Panel -> Unresolved Requests
2. All of the cells within the "Days since last action" column contain information
> LEAF-4765 - Report Builder: Add undefined check

- LEAF_Request_Portal/sources/FormWorkflow.php
This follows https://github.com/department-of-veterans-affairs/LEAF/pull/2706, which improves performance for the Inbox's "Organize by Roles" mode.
This provides an additional ~45% improvement, specifically when requests are pending "Requestor Followup" AND the user is an admin.
The test database has been updated to include more "Requestor Followup" conditions, which helps highlight this hotspot, and is a more realistic real-world scenario. Performance improvements across multiple builds are as follows:
```
│ build.20250407 │               this_PR               │
│     sec/op     │   sec/op     vs base                │
Homepage_defaultQuery-6              55.80m ± 1%   55.85m ± 2%        ~ (p=0.971 n=10)
Inbox_nonAdminActionable-6           82.00m ± 3%   81.97m ± 1%        ~ (p=0.853 …
```
> LEAF-4770 - Optimization: Use userMetadata instead of individual lookups

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Addresses pain points noted by the community.
**Action Bubbles** for custom routes are positioned 50% across the route line.  Multiple routes from-to the same steps can be difficult to read and interact with.  This update spreads up to 5 actions between 20-80%.  If there is only one route, it will be at 50%.  If there are more than 5 routes, they will max at 80% across the line.  Action positioning will get some further refinement in a future story, but this will address the main issues for most workflows.
**Step and Action Modals** can open off the right side of the screen.  This could cause scrolling issues on some browsers.
When opened, positioning will be assessed and updated if needed to keep the modals on the screen.
**Return to Requestor** action has an incorrect label for its …
> LEAF 4716 - workflow editor UX improvements

- LEAF_Nexus/templates/view_group.tpl
This will help users not delete groups from the Nexus that are being used in portals. By making the user remove any tags before removing the group will keep them from inadvertently removing a group that is being used.
This will force people to remove any tags before removing the group
Navigate to the Nexus
search for a group with a known tags
Click "Delete Group"
Expect a popup informing the user that tags must be removed before performing this action.
If the group does not have a tag expect a confirmation popup to delete the group
> Leaf 4570 - Nexus Tagged Groups Cant be Removed

- LEAF_Request_Portal/templates/reports/LEAF_mass_action.tpl
This PR addresses a bug where the mass action - email reminder, days since last action does not filter the result set. 
This will allow filtering of data based on days since last action
Navigate to the mass action page.
In the drop down select Email Reminder
The result set should filter down to requests where there is an action history and the date is older than 7 days.
If there are multiple requests with different dates of last actions you should be able to change the days since last action the the result set should change based on those days.
> Leaf 4779 - email reminder last action

- LEAF_Request_Portal/templates/reports/LEAF_mass_action.tpl
This fixes a bug created by the first fix of this ticket. When fixing the email last action days it broke the cancel, restore, and submit result sets. This fixes that and all are now working as expected.
This will prevent a hot fix where the dropdown doesn't return anything but for email reminders
Go to the mass action page and select each of the dropdown options and verify that the results are correct.
> Leaf 4779 - dropdown results fix

- LEAF_Request_Portal/templates/reports/LEAF_mass_action.tpl
When attempting to send email reminders from mass action page there is an alert box error being produced. This is the result of code that was getting the valueOf instead of value for the days since last action.
Email reminders will now go out.
navigate to mass actions
select email reminders from dropdown
select at least one request to send an email to
observe that the email got sent.
> Leaf 4803 - mass action email reminders producing error

- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
- LEAF_Request_Portal/sources/Email.php
- LEAF_Request_Portal/sources/FormWorkflow.php
This provides flexibility in email templates related to forms marked as "Need to know", following https://github.com/department-of-veterans-affairs/LEAF/pull/2705.
This adds two new email template variables, `fullTitle_insecure` and `truncatedTitle_insecure`, which require explicit action by an administrator to enable.
This also includes some minor formatting and description changes in the Editor's Template Variable section.
This solution has not been extended to the automated email system in order to minimize the scope of this PR. LEAF-4815 has been created to address this.
- Prerequisites:
1. A Workflow has been configured with an email notification event, associated with a Form
2. The relevant email template has been updated to include the *_insecure variable
1. Create a record with a …
> LEAF-4755 Add "insecure" template variable

- LEAF_Request_Portal/templates/subindicators.tpl
Removes logic that forced sub-questions that had no / empty formats to be bold.
Moves the logic that adds Advanced Options (html) for 'no format' questions so that it does not apply only to main headers.  htmlPrint does not have this issue.
Users will have intended control over indicator name formatting and can add advanced options for sub-questions that have a 'none' format.
There might be users who have saved prior attempts at Advanced Options added to none-format questions.  Advanced Options will now run (as intended) but could potentially cause unexpected results.  This is likely a rare situation, but noted so we can be on the lookout for it.   Removing the html AO would resolve it. 
None-format sub-questions will not be bold unless they are set to be in the form editor.  This could …
> LEAF 4758 remove alternate bolded heading label and move html AO

- LEAF_Request_Portal/templates/view_reports.tpl
Cached row locations could cause requests to sort incorrectly when the 'Create Row' button was used.
Adds a call to grid.stop to prevent use of render cache in this situation.
The code controlling the styling update of the newest row has been moved to occur after grid render rather than after request creation to improve consistent reactivity.  The prior 750 MS timeout has been removed.  The ID of the latest record created is also added to the button as a data property to facilitate testing.
Addresses a sorting issue in the Report Builder / view_reports.tpl
Use a Report Builder filter for a form type that has over 50 requests.
Use the 'Create Row' button several times after sorting by a header other than UID (eg title).
If present, only one row should have highlighting (if there are a …
> LEAF 4801 call grid stop if Create Row is used, move style update

- pkg/form/query/go.mod
- pkg/form/query/response.go
This is prerequisite work for future functionality.
This defines basic response types for `api/form/query` as a package and reserves the `pkg/*` path.
N/A, no dependencies
N/A, not functional
> LEAF-4820 pkg/form/query: Define types

- LEAF_Request_Portal/api/controllers/FormWorkflowController.php
- LEAF_Request_Portal/sources/FormWorkflow.php
This provides a mechanism to provide "strict actions", which can reduce confusion in very specific circumstances.
Background: In order to fulfill an action, two conditions must be fulfilled: 1) a workflow step requirement (aka dependency) must be currently active, and 2) the action is valid for the current step.
The combination of the two conditions are ideally unique, as duplication implies an inefficient business workflow. In some workflows, process owners may elect to intentionally duplicate the conditions. Confusion can potentially occur if a record is on different steps that require the same conditions AND an older page state exists (via open window) AND the user(s) tokens have not expired.
This PR adds an optional `stepID` parameter in `api/formWorkflow/[digit]/apply` to provide a …
> LEAF-4826 - FormWorkflow: Add optional stepID for action validation

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
It was reported that the new inbox does not have the unmasking functionality that the old one did. It was discovered that the sensitiveIndicator.js file was not included in the new inbox.
This will allow users to quickly view sensitive data if they are allowed.
Find an Inbox item that has sensitive data in it and hover over the **** and the data will show up.
> Leaf 4860 - add sensitiveIndicator.js

- .github/codeql-config.yml
This resolves a CodeQL false-positive related to syntax errors.
The file prefixed with `TEMPLATE_` intentionally contains invalid JS, as it's an example.
n/a
n/a
> LEAF-4881 - CodeQL: Ignore example

- LEAF_Request_Portal/admin/templates/view_form_library.tpl
The LEAF Library is blank and not displaying any results.  In the past I could view a national list of LEAF forms available for downloading. Looked into the inspector window and found an error in the console "SyntaxError: Unexpected token 'j', "jsonpCallb"... is not valid JSON". 
PR that causes this: https://github.com/department-of-veterans-affairs/LEAF/pull/2758/files
Leaf library was not able to load due to a code update, this gets around this issue for now since jsonp is not needed on this page.
This is not testable on development and needs to be done on non production. Go to Academy/Demo1 and Academy/Demo2. Demo 1 has the fix in place and Demo 2 has the original code. IF there is a better way to test this please let me know.
> LEAF-4905 - INC39443060 - LEAF library not loading

- LEAF_Request_Portal/ajaxIndex.php
- LEAF_Request_Portal/templates/print_form_ajax.tpl
- LEAF_Request_Portal/templates/print_subindicators.tpl
- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
This enables more customization options for field developers.
This makes it easier to customize the following templates:
- print_subindicators.tpl
- print_subindicators_ajax.tpl
Minimal performance impact for non-customized sites due to additional customTemplate() lookups.
Prerequisites:
- LEAF record contains multiple nested subfields
1. Open a LEAF record
2. Navigate to Admin Panel -> LEAF Template Editor
3. Add unique text, AAAAA, at the top of `print_subindicators`
4. Add unique text, BBBBB, at the top of `print_subindicators_ajax`
5. Refresh the record from step 1
6. You should expect to see AAAAA and BBBBB in the document
> LEAF 4960 Enable deeper customization of printview templates

- LEAF_Request_Portal/api/index.php
This allows non-admins to view a portal's Admin list.
This modifies the `GET ./api/group/1/members` endpoint's access control, which previously required admin access. This change is needed to support activities related to the SSN Reduction Act.
The access control change was determined to be acceptable, as it's important for a user of the site to be able to contact its administrator, and sites routinely list them.
The impact here is that a list of admins for a site are now available to everyone, not just other admins.
Nothing to test here.
> Leaf 4789 - SSN Scan

- LEAF_Request_Portal/js/formQuery.js
This resolves an issue where searching for a URL results in an error.
Minimal since this URI encodes double slashes within the URL's query parameters, which generally expect URI encoded data.
1. Change a record's title to `https://leaf.va.gov`
2. On the homepage, search for `https://leaf.va.gov`
3. You should expect to see the record from step 1
> LEAF-5003 - uriencode double slashes

- LEAF_Nexus/sources/Platform.php
This avoids a hardcoded path and prevents a potential typechecking error.
Potentially impacts dependencies on `api/platform/portal`, which is used when deleting Group tags in the Nexus.
- Check that deleting Group tags in the Nexus work normally
> LEAF-5000 - Remove docker host hardcode and fix getTags empty array

- LEAF_Request_Portal/sources/Form.php
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2025041000-2025081400.sql
:warning: Deployment: This includes a database schema change, which must be applied prior to this patch.
This enables form fields to be used as an efficient data store for ephemeral content.
The LEAF Agent logs metadata server-side, however relevant data is difficult to review for admins. This uses form fields to make metadata such as the "Timestamp for last successful run" and specific error logs more accessible to admins. However since the metadata can be updated as frequently as once every 10 seconds, this can unnecessarily bloat the local database's changelog.
The new portal database column `indicators.trackChanges` provides server-side control to avoid maintaining a full changelog for specific indicators. The direct change is still logged via timestamp and userID.
Track changes is …
> LEAF-4999 - Control track changes

- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/js/formGrid.js
This improves the developer experience by reducing the need for certain initialization statements, which can accelerate development of customizations.
1. Include formQuery.js on the `?a=newform` and `?a=view` pages
2. In formGrid.js: setDataBlob() no-longer requires the `id` parameter to be provided
Impact to dependencies minimized by the approach of importing a JS file that doesn't do anything by itself, and optional parameter checking.
No user-facing changes.
> LEAF-5068 - Improve Dev UX

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/sources/Workflow.php
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2025081400-2025100200.sql
This prevents modification of reserved requirement IDs using server-side restrictions.
The reserved IDs are intended to be standardized to facilitate effective communication.
This also uses a database update to enforce consistency for the affected ID# `-4`, as well as hide the "LEAF Agent" requirement as an option.
None because the affected requirement ID# `-4` has not been fully implemented.
Automated test added: https://github.com/department-of-veterans-affairs/LEAF-Automated-Tests/pull/173
> Leaf 5083 - Prevent modification of reserved requirement IDs
