- LEAF_Request_Portal/admin/templates/mod_form.tpl
Fixed the issue with keyword no and duplicate options.
@mgaoVA
> Bug #49 Fix.

- LEAF_Request_Portal/FormWorkflow.php
- LEAF_Request_Portal/Inbox.php
- LEAF_Request_Portal/Login.php
- LEAF_Request_Portal/form.php
Code updates to fix concerns related to designated backups
cc: @mgaoVA, @apgates
> Code changes for designated backUps

- LEAF_Request_Portal/FormWorkflow.php
- LEAF_Request_Portal/Inbox.php
- LEAF_Request_Portal/Login.php
- LEAF_Request_Portal/form.php
> Revert "Code changes for designated backUps"

- LEAF_Request_Portal/FormWorkflow.php
- LEAF_Request_Portal/Inbox.php
- LEAF_Request_Portal/Login.php
- LEAF_Request_Portal/form.php
Corrected typos and resubmit of previous code.
@cc: @mgaoVA , @apgates
> Corrected typos.[Leaf-37]

- LEAF_Request_Portal/admin/templates/mod_form.tpl
UI Update for PIV Signature.
@apgates
> UI Update for PIV Signature.

- LEAF_Request_Portal/admin/templates/mod_form.tpl
Option text updated for piv signature field
@mgaoVA , @apgates
> Option text updated for piv signature field

- README.md
This is also a test of the workflow described in the README. The line
above should appear as the commit subject, while this paragraph
should appear as the commit message body.
> Update README with developer git workflow.

- LEAF_Nexus/js/positionSelector.js
Added an aria-label on input elements per 508 scan
> added aria label for assistive technology

- LEAF_Nexus/js/groupSelector.js
Added an aria-label on input elements per 508 scan
> Added aria label for accessibility technology

- LEAF_Nexus/js/employeeSelector.js
Added an aria-label on input elements per 508 scan
> Added aria-label for assistive technology

- LEAF_Nexus/css/style.css
- LEAF_Nexus/login/index.php
- LEAF_Nexus/templates/main.tpl
- LEAF_Nexus/templates/main_iframe.tpl
- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/login/index.php
- LEAF_Request_Portal/templates/main.tpl
Updated the html tag with a language designation and updated the color of the "about" section for ease of viewing and assistive technology.
> Leaf374 nexus portal accessibility

- .gitignore
- LEAF_Nexus/admin/index.php
- LEAF_Nexus/ajaxEmployee.php
- LEAF_Nexus/ajaxGroup.php
- LEAF_Nexus/ajaxIframe.php
- LEAF_Nexus/ajaxIndex.php
- LEAF_Nexus/api/index.php
- LEAF_Nexus/auth_domain/index.php
- LEAF_Nexus/auth_token/index.php
- LEAF_Nexus/enforceHTTPS.php
- LEAF_Nexus/file.php
- LEAF_Nexus/image.php
- LEAF_Nexus/index.php
- LEAF_Nexus/report.php
- LEAF_Nexus/test.php
- LEAF_Request_Portal/admin/ajaxIndex.php
- LEAF_Request_Portal/admin/ajaxJSON.php
- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/ajaxIframe.php
- LEAF_Request_Portal/ajaxIndex.php
- LEAF_Request_Portal/ajaxMicro.php
- LEAF_Request_Portal/api/index.php
- LEAF_Request_Portal/auth_domain/index.php
- LEAF_Request_Portal/auth_token/index.php
- LEAF_Request_Portal/enforceHTTPS.php
- LEAF_Request_Portal/image.php
- LEAF_Request_Portal/index.php
Moved redundant block of code to single file and included it once where needed.
> ATO Header Manipulation Fixes

- LEAF_Nexus/css/view_position.css
- LEAF_Nexus/templates/view_employee.tpl
eliminated duplicate id's for Group, Back up, and Position assignments when searching for employees
> Eliminating duplicate ID attributes for employee view

- LEAF_Nexus/admin/templates/mod_templates_reports.tpl
- LEAF_Nexus/admin/templates/setup_medical_center.tpl
- LEAF_Nexus/admin/templates/view_admin.tpl
- LEAF_Nexus/css/style.css
- LEAF_Nexus/templates/browse_group.tpl
- LEAF_Nexus/templates/view_group.tpl
- LEAF_Nexus/templates/view_homepage.tpl
- LEAF_Request_Portal/admin/css/style.css
- LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/templates/print_form.tpl
- LEAF_Request_Portal/templates/view_homepage.tpl
Reverts VHAINNOVATIONS/LEAF#17
Prep to merge into dev instead of master
> Revert "Aaron dev"

- LEAF_Nexus/admin/templates/mod_templates_reports.tpl
- LEAF_Nexus/admin/templates/setup_medical_center.tpl
- LEAF_Nexus/admin/templates/view_admin.tpl
- LEAF_Nexus/css/style.css
- LEAF_Nexus/templates/browse_group.tpl
- LEAF_Nexus/templates/view_group.tpl
- LEAF_Nexus/templates/view_homepage.tpl
- LEAF_Request_Portal/admin/css/style.css
- LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/templates/print_form.tpl
- LEAF_Request_Portal/templates/view_homepage.tpl
This reverts commit 16b4894507363543c1018b339d92c5ca2ca5da92, reversing
changes made to 7e1780e09816b29030098db6b687e30d9d9897a2.
> Revert "Merge branch 'master' into dev"

- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/index.php
path needs to be relative to the current file
avoid including dependent files within loops
> fix fatal errors

- LEAF_Request_Portal/form.php
- libs/php-commons/CryptoHelpers.php
- test/.gitignore
- test/LEAF_Nexus_Tests/phinx.yml.example
- test/LEAF_Request_Portal_Tests/phinx.yml.example
- test/LEAF_Request_Portal_Tests/tests/api/FormControllerTest.php
- test/LEAF_Request_Portal_Tests/tests/helpers/CryptoHelpersTest.php
- test/README.md
Added methods to verify that a signature is authentic for a given
message and signing key.
> LEAF-435 Sign Form JSON

- LEAF_Request_Portal/FormWorkflow.php
- LEAF_Request_Portal/api/controllers/FormController.php
- LEAF_Request_Portal/api/controllers/FormEditorController.php
- LEAF_Request_Portal/api/controllers/GroupController.php
- LEAF_Request_Portal/sources/System.php
- libs/php-commons/XSSHelpers.php
- test/LEAF_Nexus_Tests/tests/utils/HelpersTest.php
- test/LEAF_Request_Portal_Tests/db/seeds/BaseTestSeed.php
- test/LEAF_Request_Portal_Tests/tests/api/FormControllerTest.php
- test/LEAF_Request_Portal_Tests/tests/api/FormEditorControllerTest.php
- test/LEAF_Request_Portal_Tests/tests/helpers/CryptoHelpersTest.php
Added tests for Request Portal API.
Updated Request Portal API endpoints to sanitize input where necessary to prevent potential XSS vulnerabilities.
> LEAF-448 Request Portal API XSS

- LEAF_Request_Portal/admin/templates/mod_form.tpl
- libs/php-commons/XSSHelpers.php
> Emergency fix

- LEAF_Request_Portal/js/formGrid.js
updated the table on the main request portal page to allow the table head to be reached with the keyboard and to sort with the enter key.
> Navigable table headers

- LEAF_Request_Portal/Inbox.php
- LEAF_Request_Portal/scripts/custom_js/TEMPLATE_workflow_YOURNAME.js
> show correct name

- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/admin/templates/print_subindicators.tpl
- LEAF_Request_Portal/api/controllers/FormEditorController.php
- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/sources/FormEditor.php
- LEAF_Request_Portal/templates/print_form.tpl
- libs/jsapi/portal/LEAFPortalAPI.js
- test/LEAF_Request_Portal_Tests/db/seeds/BaseTestSeed.php
- test/LEAF_Request_Portal_Tests/db/seeds/InitialSeed.php
- test/LEAF_Request_Portal_Tests/tests/api/FormControllerTest.php
- test/LEAF_Request_Portal_Tests/tests/api/FormEditorControllerTest.php
- test/LEAF_Request_Portal_Tests/tests/helpers/CryptoHelpersTest.php
Enables admins to set group read access to an individual indicator within a form.
> Indicator group access

- LEAF_Nexus/api/controllers/SystemController.php
- LEAF_Nexus/sources/System.php
- LEAF_Request_Portal/api/controllers/SystemController.php
- LEAF_Request_Portal/sources/System.php
- test/LEAF_Nexus_Tests/tests/api/controllers/SystemControllerTest.php
- test/LEAF_Request_Portal_Tests/tests/api/SystemControllerTest.php
Added endpoints to Nexus and Request Portal to get the current version of the database.
> Leaf490 db version api

- LEAF_Nexus/js/employeeSelector.js
- LEAF_Nexus/js/nationalEmployeeSelector.js
- LEAF_Nexus/templates/view_group.tpl
- LEAF_Nexus/templates/view_position.tpl
Added additional aria labels for more accurate descriptions.
> 508 compliance changes. 

- LEAF_Request_Portal/form.php
optimize for faster response when the collaborator feature isn't being
used
> fix issue where access was being granted incorrectly

- LEAF_Nexus/login/index.php
- LEAF_Nexus/templates/main.tpl
- LEAF_Nexus/templates/main_iframe.tpl
- LEAF_Request_Portal/admin/modgroups.php
- LEAF_Request_Portal/login/index.php
- LEAF_Request_Portal/sources/System.php
These are changes made after my review of fortify scan with MG.
> Leaf500 fortify changes

- LEAF_Request_Portal/form.php
for multi-checkbox options, provide selected options as an array
fix invalid parameters
> form query update

- LEAF_Nexus/sources/Data.php
- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/sources/System.php
Updating all file extension whitelists to include support for .ai and
.eps files.
> Update file extension whitelists

- LEAF_Request_Portal/api/controllers/FormController.php
- LEAF_Request_Portal/form.php
- test/LEAF_Request_Portal_Tests/tests/api/FormControllerTest.php
Updated `LEAF_Request_Portal/form.php` to sanitize data where necessary
in order to comply with ATO.
Added new Form Controller tests.
> ATO remediations for LEAF_Request_Portal/form.php

- app.env
the values in app.env are needed for the build automation code
> Added app.env

- LEAF_Nexus/ajaxPosition.php
- LEAF_Nexus/enforceHTTPS.php
- LEAF_Nexus/file.php
- LEAF_Nexus/index.php
- LEAF_Nexus/report.php
- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/ajaxIframe.php
- LEAF_Request_Portal/ajaxIndex.php
- LEAF_Request_Portal/ajaxJSON.php
- LEAF_Request_Portal/auth_token/index.php
- LEAF_Request_Portal/enforceHTTPS.php
- LEAF_Request_Portal/file.php
- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/image.php
- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/mailer/mailer.php
- LEAF_Request_Portal/report.php
- libs/php-commons/XSSHelpers.php
I didn't realize there were more tickets when I titled this branch. I didn't want to call it ato_remediations, in case it caused any kind of confusion with the old branch.
> ATO Remediations

- LEAF_Request_Portal/templates/print_form.tpl
- LEAF_Request_Portal/templates/print_form_ajax.tpl
Fixes for buttons on `LEAF_Request_Portal/index.php?a=printview&recordID=(integer)` so that they can be read by a screen reader
> Leaf571 508compliance printview fixes

- LEAF_Nexus/scripts/VAMC_directory_maintenance2_AD.php
- LEAF_Request_Portal/scripts/VAMC_directory_maintenance2_AD.php
reran with correct config for php-cs-fixer
> Leaf589 vamc directory maintenance2 ad fix

- LEAF_Request_Portal/scripts/updateServicesFromOrgChart.php
reran php-cs-fixer with correct config
> LEAF584 UpdateServicesFromOrgchart

- test/LEAF_Request_Portal_Tests/tests/api/SystemControllerTest.php
- test/shared/src/LEAFClient.php
Also fixes bug in SystemControllerTest
> Phpunit fix verifyAdminReferrer

- LEAF_Nexus/css/style.css
- LEAF_Nexus/js/groupSelector.js
- LEAF_Nexus/js/nationalEmployeeSelector.js
- LEAF_Nexus/js/positionSelector.js
- LEAF_Nexus/templates/permission_iframe.tpl
- LEAF_Nexus/templates/print_subindicators.tpl
- LEAF_Nexus/templates/subindicators.tpl
- LEAF_Nexus/templates/view_group.tpl
- LEAF_Request_Portal/admin/templates/mod_groups.tpl
> LEAF601 remediations for admin mod group page

- LEAF_Nexus/css/style.css
- LEAF_Nexus/js/groupSelector.js
- LEAF_Nexus/js/nationalEmployeeSelector.js
- LEAF_Nexus/js/positionSelector.js
- LEAF_Nexus/templates/permission_iframe.tpl
- LEAF_Nexus/templates/print_subindicators.tpl
- LEAF_Nexus/templates/subindicators.tpl
- LEAF_Nexus/templates/view_group.tpl
- LEAF_Request_Portal/admin/templates/mod_groups.tpl
Reverts VHAINNOVATIONS/LEAF#295
> Revert "LEAF601 remediations for admin mod group page"

- docker/mysql/Dockerfile
Changed MySQL to MariaDB due some issues
> Changed MySQL to MariaDB

- LEAF_Request_Portal/admin/index.php
in debug mode leaf breaks due to incorrect path for XSShelper
> Fixed incorrect path for XSSHelper

- LEAF_Request_Portal/js/form.js
- LEAF_Request_Portal/js/workflow.js
- LEAF_Request_Portal/templates/print_form_signature.tpl
Made stamp hide/show upon signing/invalidation without needing to reload.  Clear cache before testing.
> Made stamps show/hide upon signing/invalidation

- LEAF_Request_Portal/admin/templates/import_data.tpl
- LEAF_Request_Portal/sources/System.php
Added handling of indicators with child indicators when importing data.
> Indicator children support in import_data

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Made workflow page 508 compliant except JsPlumb library
> Made workflow page 508 compliant

- libs/js/LEAF/formGrid.js
> hotfix for formgrid,js

- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/js/formGrid.js
- LEAF_Request_Portal/templates/view_inbox.tpl
Cherry picked commits from previous branch
> Leaf581 view inbox page

- LEAF_Request_Portal/FormWorkflow.php
Give users a better hint if a duplicate action is attempted.
> add error message

- LEAF_Nexus/css/style.css
- LEAF_Nexus/js/groupSelector.js
- LEAF_Nexus/js/nationalEmployeeSelector.js
- LEAF_Nexus/js/positionSelector.js
- LEAF_Nexus/templates/permission_iframe.tpl
- LEAF_Nexus/templates/print_subindicators.tpl
- LEAF_Nexus/templates/subindicators.tpl
- LEAF_Nexus/templates/view_group.tpl
- LEAF_Request_Portal/admin/templates/mod_groups.tpl
Clear cache before testing.  Cherrypicked commits from previous branch.
> Leaf601 admin mod groups

- LEAF_Nexus/auth_domain/index.php
- LEAF_Nexus/auth_token/index.php
- LEAF_Request_Portal/auth_domain/index.php
- LEAF_Request_Portal/auth_token/index.php
Redirect user to PIV login screen on error e.g. when domain is down
> LEAF697 Redirect To PIV Login

- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/templates/subindicators.tpl
Enabled secure entry for PII/PHI and made sensitive forms need to know
> LEAF 384 Secure Entry for PII/PHI

- LEAF_Nexus/sources/Data.php
breaks OrgChart Navigator -> can't move position boxes or hide/show
subordinates
> need to revert

- LEAF_Nexus/utils/jsonExport_PDL.php
remediation for XSS and JSON injection
> Leaf755 xss persistent

- LEAF_Nexus/auth_token/index.php
> LEAF752 ATO Remediation

- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
- LEAF_Request_Portal/templates/subindicators.tpl
- libs/js/LEAF/sensitiveIndicator.js
Addressed Michael's feedback from sprint planning secure entry for PII/PHI demo.
-made printview sensitive data change on hover
-filtered sensitive toggler on textareas
> LEAF-384_addressedFeedback

- libs/php-commons/XSSHelpers.php
all ints are numeric, but not all numerics are ints
> is_numeric is good enough

- LEAF_Request_Portal/templates/print_form.tpl
> show all step options if a request's workflow state was forcibly

- libs/js/LEAF/sensitiveIndicator.js
changed tag specific class selection to make it search only for the class.
> Fixed sensitive table from not display in printview page

- LEAF_Request_Portal/js/form.js
Specified `hasTable` to be if `.tableinput` is found
> Hotfix fixed selector error

- LEAF_Request_Portal/sources/FormEditor.php
fixes import of old FormPacket(s)
> set default

- LEAF_Request_Portal/templates/reports/LEAF_import_data.tpl
- libs/jsapi/portal/LEAFPortalAPI.js
Added ability to make new a form and requests from an uploaded sheet.
Also added:
* activity/import progress indicator
* error checking: 
* prevents columns with blank entries from being selected as required or in a required indicator
* generates report of requests made
> LEAF839 Import Data Into New Form

- LEAF_Request_Portal/templates/reports/LEAF_import_data.tpl
- libs/jsapi/nexus/LEAFNexusAPI.js
- libs/jsapi/portal/LEAFPortalAPI.js
* Add confirmation dialog before Importing data ("Are you sure you want to import N requests?")
* Fixed importing data for orgchart_employee
* Show a warning if the data field for orgchart_employee does not look like a VA email, username (starts with "VACO", "VHA"), or first/last name
* Filter out Section Headings when showing Indicators 
* Support orgchart_group input
> Leaf872 Data Importer Enhancements

- LEAF_Request_Portal/templates/reports/LEAF_import_data.tpl
- libs/jsapi/portal/LEAFPortalAPI.js
Added progress indicators to form creation and allowed unassigned workflows
> LEAF888 Data Importer

- LEAF_Request_Portal/templates/reports/LEAF_mass_action.tpl
The `Show Only` filter was redundant and was removed.
> LEAF872 remove `Show Only` filter

- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/admin/templates/print_subindicators.tpl
- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/js/gridInput.js
- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
- LEAF_Request_Portal/templates/subindicators.tpl
Updated gridInput to reveling module pattern, made at least one blank row in `subindicators.tpl` show when editting a blank grid, and added option "date" to `addColumn()` in `mod_forms.tpl`
> LEAF910 Grid Input Update

- LEAF_Request_Portal/templates/reports/LEAF_import_data.tpl
- libs/jsapi/nexus/LEAFNexusAPI.js
Updated JS API module to be asynchronous and changed importer accordingly.
> Leaf909 data importer callbacks

- docker/php/Dockerfile
Added missing library that prevented QR codes from generating in Dockerized LEAF
> Added missing library to Dockerfile

- LEAF_Request_Portal/index.php
Fixed missing file preventing grids from working as intended
> included missing gridInput file

- LEAF_Nexus/sources/Employee.php
- LEAF_Request_Portal/templates/subindicators.tpl
Reverts VHAINNOVATIONS/LEAF#566
> Emergency Revert "LEAF964 orgchart employee fix"

- servlets/digital-signing/src/main/java/leaf/Application.java
- servlets/digital-signing/src/main/java/leaf/JsonSerializer.java
- servlets/digital-signing/src/main/java/leaf/SignEngine.java
Json Contract:
Request from LEAF:
{
"key": "my_key",
"dataToSign": "{ "json": "string", "to": "sign" }"
}
Response from websocket:
{
"key": "my_key",
"message": "signed_data_as_hexadecimal",
"status": "SUCCESS",
"publicKey": "signing_certificate_as_string"
}
> Return public key in json payload from ws

- LEAF_Request_Portal/js/formGrid.js
fixed default encoding of csv for Excel
> LEAF966 Comment and Approval Bugfix

- LEAF_Nexus/sources/Employee.php
- LEAF_Request_Portal/templates/subindicators.tpl
Fixed search bug caused by original fix by preventing the ajax `POST` from firing unless the selected username string is not empty.
> Hotfix orgchart employee indicator

- LEAF_Nexus/admin/index.php
- LEAF_Nexus/admin/templates/main.tpl
- LEAF_Nexus/config-example.php
- LEAF_Nexus/index.php
- LEAF_Nexus/templates/main.tpl
- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/admin/templates/main.tpl
- LEAF_Request_Portal/db_config-example.php
- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/templates/main.tpl
Banner message for on-prem sites.  To use, add `public static $onPrem = true;` to `LEAF_Request_Portal/db_config.php` and `LEAF_Nexus/config.php`.  To turn it off, set the value to false.
> LEAF1008 On-Prem Banner Message

- .gitignore
- LEAF_Request_Portal/templates/view_reports.tpl
Added IDE and npm modules to .gitignore
> Fixes Shareable Report URL not decoding in cloud

- LEAF_Request_Portal/js/formPrint.js
Addressed wrapping feedback with subquestion checkboxes
> Hotfix for checkbox wrapping

- LEAF_Request_Portal/Login.php
- LEAF_Request_Portal/form.php
fix for backups not having the same permissions as backupFor
> LEAF-1071 Backups Not Inheriting Access

- LEAF_Request_Portal/form.php
Resolves issue where "Date Resolved" wasn't being identified correctly
> fix comparator

- LEAF_Request_Portal/Email.php
> LEAF 1092 Cherrypicked

- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/templates/print_form.tpl
logs activity of checkReadAccess() and hasWriteAccess() in printview
> LEAF 1092 Access Privileges Logging

- LEAF_Request_Portal/sources/System.php
Cherrypicked version Mohnish's fix
> Leaf945 filename uppercase extensions

- LEAF_Request_Portal/templates/initial_form.tpl
Made it a size of 150px to accomodate bigger words.
> Added width for dropdown menu.

- LEAF_Nexus/ajaxIndex.php
- LEAF_Nexus/db_upgrade/Update_OC_DB_5204-5220.sql
- LEAF_Nexus/db_upgrade/Update_RMC_DB_2019082300-2019110100.sql
- LEAF_Nexus/sources/Data.php
- LEAF_Nexus/sources/Group.php
- LEAF_Nexus/templates/site_elements/generic_dialog.tpl
- LEAF_Nexus/templates/view_group.tpl
- LEAF_Nexus/templates/view_history.tpl
- libs/logger/logFormatter.php
Added Logging to Data Class to allow classes extending Data to write logs in new Data Action Log Table.
> Adding Data Item Log Tables & Logging to Groups

- LEAF_Request_Portal/utils/db_upgrade/Update_RMC_DB_2019082300-2019120500.sql
Bumps smallint to int and char size from 5 to 11
> [LEAF-1219] increases data size for tags.recordID column

- LEAF_Nexus/db_upgrade/Update_OC_DB_5204-2019110100.sql
> syntax fix

- LEAF_Nexus/js/nationalEmployeeSelector.js
- LEAF_Request_Portal/templates/subindicators.tpl
Updating language for Loading to indicate Database not busy
> Leaf-1168 Fix Loading 

- LEAF_Nexus/scripts/refreshOrgchartEmployees.php
limits employee_data update to just phone, email, location, AD title
> [LEAF-1247] limits employee_data update to just phone, email, location, AD title

- LEAF_Request_Portal/templates/reports/LEAF_import_data.tpl
Converts excel date to mm/dd/yyyy through helper function if the incoming value is within an Excel Date column. Otherwise, passes whatever data is in the field. 
Alternatively, if the Excel column is formatted as Text and in the acceptable format mm/dd/yyyy, the date could pass through as well.
Additional info on excel conversion: https://gist.github.com/christopherscott/2782634
> [LEAF-1238] import data date fix

- LEAF_Nexus/scripts/refreshOrgchartEmployees.php
removing echo line marked as xss vuln
> [LEAF-1269] removing echo line marked as xss vuln

- LEAF_Nexus/js/employeeSelector.js
- LEAF_Nexus/js/groupSelector.js
- LEAF_Nexus/js/nationalEmployeeSelector.js
- LEAF_Nexus/js/positionSelector.js
moved txt to a .text() assignment to prevent xss
> [LEAF-1266] Sanitize txt for HTML render

- LEAF_Nexus/scripts/refreshOrgchartEmployees.php
change query to parameterized query
> [LEAF-1274]change query to parameterized query

- LEAF_Request_Portal/admin/ajaxIndex.php
checks for parameter, casts and scrubs data
> [Fortify][Hotfix] Checks incoming parameter and scrubs.

- LEAF_Request_Portal/js/formGrid.js
only check for isIndicatorID for dates
> hotfix mainpage title sort

- LEAF_Nexus/js/nationalEmployeeSelector.js
- LEAF_Nexus/sources/NationalEmployee.php
Fixes middle name search when using comma with Last, First
Adds additional searchDeeper function from Employee.php
> [LEAF-1214] Fixes middle name search when using comma

- LEAF_Nexus/admin/templates/admin_refresh_directory.tpl
- LEAF_Nexus/api/controllers/SystemController.php
- LEAF_Nexus/scripts/refreshOrgchartEmployees.php
- LEAF_Nexus/sources/System.php
Runs php script in background
Updates UI with no loading spinner and basic static text
Fixes parametrized queries for refreshing employee
> [LEAF-1284] Refresh directory UI and process update 

- LEAF_Nexus/sources/Data.php
- libs/php-commons/CommonConfig.php
> bugfix/LEAF-1345-whitelist - disallow html uploads in non-admin contexts

- LEAF_Nexus/admin/index.php
- LEAF_Nexus/index.php
- LEAF_Nexus/report.php
see helpdesk 1173 for details:
Subheading was not being saved in nexus - is now.
> allowing subheadings to be saved

- LEAF_Request_Portal/Inbox.php
- LEAF_Request_Portal/form.php
The fix that Michael set in place needed to be applied two other places
> applying requestor fix everywhere

- LEAF_Request_Portal/sources/Workflow.php
> Fixing dependency privilege logging so modal dismisses appropriately

- LEAF_Request_Portal/ajaxIndex.php
- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
in order to target the request's data to dynamically fill out the custom grid,  we need the request id
> Adding recordID to data

- LEAF_Nexus/templates/view_history.tpl
LEAF-1289: Fixed visibility for history table
> LEAF-1289: Fixed visibility for history table

- LEAF_Nexus/admin/templates/site_elements/generic_xhrDialog.tpl
- LEAF_Nexus/css/style.css
- LEAF_Nexus/templates/site_elements/generic_dialog.tpl
- LEAF_Nexus/templates/site_elements/generic_xhrDialog.tpl
- LEAF_Request_Portal/admin/css/style.css
- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/admin/templates/site_elements/generic_xhrDialog.tpl
- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/templates/site_elements/generic_dialog.tpl
- LEAF_Request_Portal/templates/site_elements/generic_xhrDialog.tpl
Updated width of dialog box used in the history pop up dialogs.
> LEAF-1406: Fixed dialog width

- LEAF_Nexus/api/controllers/NationalEmployeeController.php
- LEAF_Nexus/sources/NationalEmployee.php
- libs/jsapi/nexus/LEAFNexusAPI.js
Adds endpoint to import national employee to local by email
> [LEAF-1412] Adds endpoint to import national employee to local by email

- LEAF_Nexus/sources/Data.php
- LEAF_Request_Portal/admin/templates/mod_groups.tpl
- libs/logger/formatters/groupFormatter.php
- libs/logger/formatters/loggableTypes.php
Adding history logging for tags
> Adding history logging for tags

- docs/InstallationConfiguration.md
- test/README.md
Updated installation file and test read me file.
> Feature/leaf 1310 update GitHub readme

- LEAF_Nexus/admin/templates/site_elements/generic_plainDialogLarge.tpl
- LEAF_Nexus/js/dialogController.js
- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/admin/templates/mod_groups.tpl
- LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/admin/templates/view_form_library.tpl
- LEAF_Request_Portal/js/dialogController.js
- LEAF_Request_Portal/templates/reports/sitemaps_template.tpl
Implemented feedback from Michael. Dialog box cannot be minimized less than the width of the dialog box content.
> LEAF-1462: Added min width to dialog box

- docker/php/Dockerfile
- docker/php/trust_ca_certs.sh
Adds VA certificates to Dockerfile
Adds cerificates to Dockerfile at build time for supporting SSL
connections.
> Adds VA certificates to Dockerfile

- LEAF_Nexus/templates/view_group.tpl
merge feature/LEAF-1529-adjust-verbiage-for-service-removed to dev
> Adjust verbiage when service tag is removed - v1

- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
- LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
- LEAF_Request_Portal/api/controllers/SystemController.php
- LEAF_Request_Portal/sources/System.php
- LEAF_Request_Portal/templates/email/LEAF_notify_complete_body.tpl
- LEAF_Request_Portal/templates/email/LEAF_notify_next_body.tpl
- LEAF_Request_Portal/templates/email/LEAF_send_back_body.tpl
Created new section under Admin called "Email Template Editor" for editing email templates.
> Feature/LEAF-1300: Email Template Editor

- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
LEAF-1615: Addressed feedback on email template editor
> LEAF-1615: Addressed feedback on email template editor

- Jenkinsfile.dev
- docker/php/Dockerfile
- docker/php/trust_ca_certs.sh
- fort_report/FortifyReportGen.sh
- fort_report/fortify.properties
Updates pipeline to generate fortify report
> LEAF-1441 fortify report

- LEAF_Request_Portal/index.php
LEAF-1606: Enhance accuracy of matomo by tracking User ID
Enabling metric to be used in tracking by Matomo User ID.
> LEAF-1606: Enhance accuracy of matomo by tracking User ID

- LEAF_Request_Portal/admin/templates/menu.tpl
- LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
Fixed link for Search Database on global nav and in admin menu button - path error, changed URL to '../?a=search'
> LEAF-1649: Request Portal Search Database URL Fix

- LEAF_Nexus/admin/templates/setup_medical_center.tpl
- LEAF_Nexus/admin/templates/site_elements/generic_plainDialogLarge.tpl
Fixed bug where empty dialog box is displayed on Admin/Setup Wizard page.
> LEAF-1601: Fixed empty dialog box

- Launchpad/CustomEvent_check_orgchart_exists.php
- Launchpad/CustomEvent_create_leaf.php
- Launchpad/CustomEvent_create_orgchart.php
contact me about what values to use
> scripts for stateless launchpad

- LEAF_Nexus/index.php
LEAF-1606: Adding ability to track by userID in LEAF_Nexus
> LEAF-1606: Adding ability to track by userID in LEAF_Nexus

- LEAF_Request_Portal/js/form.js
Made window contents resize when editing a form request in a pop up window.
> LEAF-1715: Fixed width of dialog window

- index.php
> hotfix/ LEAF-1721 avoid adding trailing slash to files

- LEAF_Request_Portal/file.php
- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/sources/System.php
- libs/php-commons/aws/AWSUtil.php
- routing/portal_config.php
Templating Editor, read, write, delete changes
Request Portal custom template read
> [LEAF-1333] templating concept with NFS directories

- .gitignore
- LEAF_Nexus/globals.php
- LEAF_Request_Portal/Email.php
- LEAF_Request_Portal/globals.php
- docker/docker-compose.yml
- routing/routing_config.php
LEAF-1527: Parameterizing configuration for deployment
Configures all runtime information required to be launched by ConfigMaps
This commit brings in previously ignored files under source code.
> LEAF-1527: Parameterizing configMaps for deployment

- LEAF_Request_Portal/admin/templates/mod_groups.tpl
Taking out hard-coded group counts from User Groups page.
> hotfix/LEAF - Remove Hard Code Counts from mod_groups.tpl

- LEAF_Request_Portal/admin/templates/mod_file_manager.tpl
- LEAF_Request_Portal/api/controllers/SystemController.php
- LEAF_Request_Portal/sources/System.php
- index.php
- routing/Handlers.php
- routing/LEAFRoutes.php
Reimplements old functionality with GET-ting one single file from file manager by adding a route for /files/
Removes new API endpoint.
> [LEAF-1815] Portal file manager revision

- docker/nginx/nginx.conf
- docker/php/Dockerfile
Adds new nginx route for icons
Updates nginx conf for new location to /libs/dynicons
> Adds new nginx route for icons

- LEAF_Request_Portal/admin/templates/mod_form.tpl
Removed width limitation and css left from all grid inputs in form editor
> LEAF-1861: Removed width and left css tags from grid input in Form Editor

- routing/Handlers.php
> [Bugfix][LEAF1898] S3 file manager fix

- docker/php/Dockerfile
- docker/php/etc/cli/php.ini
Adds php.ini for CLI invocations and resolves logging issue
- Adds customized php.ini for CLI with tuning
- Creates logging folder in Dockerfile
- Logging should be sent to standard-out in the future
> Adds php.ini for CLI invocations and resolves logging issue

- LEAF_Request_Portal/templates/print_subindicators.tpl
Fixed section 508 bug. Added button tag to edit image icon for accessibility.
> LEAF-1962: Add button tag to edit icon

- LEAF_Nexus/js/nationalEmployeeSelector.js
- LEAF_Request_Portal/templates/subindicators.tpl
Added label tag to labels in printview mode.
Added descriptive text to user selection input box.
> LEAF-1964: Fixed user selection label

- LEAF_Request_Portal/templates/initial_form.tpl
- LEAF_Request_Portal/templates/subindicators.tpl
Added label tags for request page to fix section 508 issues.
> LEAF-1942: Added labels for input fields

- libs/php-commons/CommonConfig.php
Reverts VHAINNOVATIONS/LEAF#1219
> Revert "add common file extensions for 3d printer files"

- LEAF_Request_Portal/templates/print_subindicators.tpl
Converted image from button around an image to just a button itself.
> LEAF-1981 - Fixed edit icon issue in IE

- LEAF_Request_Portal/templates/print_subindicators.tpl
Edit icon changed from an image within the button to just button
> LEAF-1981 - Fixing Edit Icon in IE

- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/admin/templates/site_elements/generic_xhrDialog.tpl
Fix was to remove un-needed floats causing confusion in IE
> LEAF-1937 - Save button float issue for Workflow Add Event popup

- LEAF_Request_Portal/admin/templates/mod_form.tpl
Added the fix to the other dialog box for continuity.
> bugfix/LEAF-1937: Fixed Form Editor Save Button Both Dialogs

- LEAF_Request_Portal/api/controllers/TelemetryController.php
- LEAF_Request_Portal/sources/Telemetry.php
- docker/php/scripts/upload_sizes.sh
Changes in the Telemetry file for this are not included here because they are saved in the Jira task.
> LEAF-1989 - Adding Portal Upload Size Script and API

- LEAF_Request_Portal/api/controllers/TelemetryController.php
- LEAF_Request_Portal/sources/Telemetry.php
- docker/php/scripts/upload_sizes.sh
Reverting this merge as a different method of getting sizes will be used.
> Revert "LEAF-1989 - Adding Portal Upload Size Script and API"

- LEAF_Request_Portal/Email.php
Prevent email template To/CC email addresses from checking for duplicates as they are required
> LEAF-1687 - Email templates addresses always included

- libs/php-commons/CommonConfig.php
> LEAF-2129: Add DWG file upload type (AutoCAD files)

- LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
Just added some more descriptive comments for the Timeline Explorer.
Looking to move into its own JS in the future.
> DEV: LEAF-2254 - Timeline Explorer Comments Added

- LEAF_Request_Portal/admin/templates/mod_groups.tpl
- LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
- LEAF_Request_Portal/scripts/updateServicesFromOrgChart.php
> DEV: LEAF-2216 - User Sync Issues Fixed

- LEAF_Request_Portal/admin/templates/mod_groups.tpl
- LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
- LEAF_Request_Portal/scripts/updateServicesFromOrgChart.php
> QA-TESTING: LEAF-2216 - User Sync Issues Fixed

- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/js/formQuery.js
- LEAF_Request_Portal/js/formSearch.js
- libs/js/LEAF/formQuery.js
- libs/js/LEAF/formSearch.js
- libs/jsapi/portal/model/FormQuery.js
> DEV: LEAF-1585 - OR Operator for Reports and Search

- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/js/formQuery.js
- LEAF_Request_Portal/js/formSearch.js
- libs/js/LEAF/formQuery.js
- libs/js/LEAF/formSearch.js
- libs/jsapi/portal/model/FormQuery.js
> QA-TESTING: LEAF-1585 - Logic for OR Operator Reports and Search

- LEAF_Request_Portal/form.php
> QA-RC: LEAF-1585 - OR Logic

- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/js/formQuery.js
- LEAF_Request_Portal/js/formSearch.js
- LEAF_Request_Portal/templates/view_search.tpl
- libs/js/LEAF/formQuery.js
- libs/js/LEAF/formSearch.js
- libs/jsapi/portal/model/FormQuery.js
> QA-RC: LEAF-1585: - OR Logic Change op to gate

- .gitignore
- LEAF_Request_Portal/Email.php
- LEAF_Request_Portal/FormWorkflow.php
- LEAF_Request_Portal/api/controllers/FormController.php
- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/js/pages/mass_action.js
- LEAF_Request_Portal/templates/email/LEAF_mass_action_remind_body.tpl
- LEAF_Request_Portal/templates/email/LEAF_mass_action_remind_subject.tpl
- LEAF_Request_Portal/templates/reports/LEAF_mass_action.tpl
Should be all good according to Greg and Amanda.
> LEAF-2139 - Mass Action Email Reminder Restore

- .github/workflows/lint_me.yml
This added a github actions file for super-linter.  
Testing should just be automated testing to ensure nothing broke.
> Added super-linter github actions

- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/admin/templates/view_disabled_fields.tpl
- LEAF_Request_Portal/api/controllers/FormEditorController.php
- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/sources/FormEditor.php
new branch for previous req https://github.com/VHAINNOVATIONS/LEAF/pull/1415
> QA: LEAF-2194 - Update of disable and delete options

- CODEOWNERS
> Rc/20210714/leaf 2378/email issues

- LEAF_Request_Portal/templates/subindicators.tpl
> propagate change events

- LEAF_Request_Portal/db_mysql.php
- docker/docker-compose.yml
- docker/env_files/caching.env
- docs/Development.md
Uses environment variable to check to invalidate the cache if modified dates don't match. Works for only GET and HEAD page requests.
> FEATURE: LEAF-2374 - Site Caching

- LEAF_Request_Portal/templates/view_reports.tpl
Discovered that some comparisons had been using conversion (eg '0' == 0).  Changed most comparisons back to double == to avoid potential problems.
> LEAF-883 most comparison changes back to == or !=

- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/db_mysql.php
- LEAF_Request_Portal/js/dialogController.js
- LEAF_Request_Portal/js/form.js
- LEAF_Request_Portal/js/pages/mass_action.js
- LEAF_Request_Portal/js/parallelProcessing.js
- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
- LEAF_Request_Portal/templates/reports/LEAF_mass_action.tpl
- LEAF_Request_Portal/templates/subindicators.tpl
- docker/docker-compose.yml
- docker/env_files/caching.env
- docs/Development.md
- test/js/yarn.lock
> Rc/210813/sprint 13 c1/1987 2374 2428 2431 dependa

- LEAF_Request_Portal/templates/view_reports.tpl
Corrected an unintended change that impacted report sharing.
Also moved url building to a function
> Feature LEAF 883 header color options new

- LEAF_Request_Portal/templates/view_reports.tpl
Addresses the situation of the New Row button not appearing if no rows are returned from the search.
> Bugfix: LEAF-2473 - New Row logic update

- LEAF_Request_Portal/templates/view_reports.tpl
Check LEAF_Request_Portal/templates/view_reports.tpl line 356
> LEAF-2475 - import grid splitter to report builder

- LEAF_Request_Portal/templates/subindicators.tpl
Moved an empty string check prior to regex and Math methods.  
Please see test suggestions in the associated Jira ticket.
> bug: LEAF-2506 fix required currency bug

- LEAF_Request_Portal/Email.php
- LEAF_Request_Portal/FormWorkflow.php
- LEAF_Request_Portal/admin/css/mod_workflow.css
- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/api/controllers/WorkflowController.php
- LEAF_Request_Portal/sources/System.php
- LEAF_Request_Portal/sources/Workflow.php
- LEAF_Request_Portal/templates/email/base_templates/LEAF_template_body.tpl
- LEAF_Request_Portal/templates/email/base_templates/LEAF_template_subject.tpl
- libs/logger/formatters/loggableTypes.php
- libs/logger/formatters/workflowFormatter.php
This Feature requires the DB_Upgrade from https://github.com/VHAINNOVATIONS/LEAF/pull/1465
> Feature: LEAF-2193 - Custom Email Events

- LEAF_Request_Portal/templates/view_reports.tpl
Updated the specificity for the check for a grid format type
> hotfix LEAF-2527 grid hotfix

- LEAF_Nexus/templates/view_employee.tpl
- LEAF_Request_Portal/form.php
This should resolve employee refresh issue in the nexus for users with an apostrophe in their username.
> Bug/leaf 2534: fix employee refresh for users with apostrophe

- LEAF_Nexus/js/employeeSelector.js
- LEAF_Nexus/js/groupSelector.js
- LEAF_Nexus/js/nationalEmployeeSelector.js
- LEAF_Nexus/js/positionSelector.js
Addresses the current inability of users to select orgchart employees from the table dropdowns by tab and enter.
Currently only applies to orgchart employee selection in forms (does not yet apply to report builder)
> LEAF 2599 tabbing and enter for employee selection

- LEAF_Request_Portal/admin/templates/print_subindicators.tpl
- LEAF_Request_Portal/form.php
Adds a property used to conditionally render a folder icon instead of a notepad icon for the 'edit indicator' button if the indicator has Advanced Options in order to more easily identify indicators that have additional code in the Form Editor UI.
> Feature/leaf 2627/advanced option display

- LEAF_Nexus/sources/Employee.php
- LEAF_Nexus/sources/NationalEmployee.php
> LEAF-2698: add condition to distinguish username with space from first last format

- LEAF_Nexus/sources/Employee.php
- LEAF_Nexus/sources/NationalEmployee.php
fixes employee selection table for users with spaces in usernames
> LEAF 2698 add condition to distinguish username with space from first last format

- LEAF_Request_Portal/js/dialogController.js
This resolves an issue where required fields (at least dropdown) are not highlighted correctly.
> trigger required field highlight

- LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
- libs/js/LEAF/intervalQueue.js
This updates the timeline explorer to provide more relevant metrics.
This also includes a new library, intervalQueue, which has been used in various projects on prod. This is a setInterval based queue to help manage concurrent requests or operations.
> Timeline explorer

- LEAF_Request_Portal/templates/reports/LEAF_table_input_report.tpl
- LEAF_Request_Portal/templates/view_reports.tpl
updated grid splitter to account for html in the grid names. had to repeal the start of logic changes since carrie made the logic changes while removing the icheck from report builder in the other branch
> LEAF-2777: Fixed grid splitter edge case

- LEAF_Nexus/admin/templates/main.tpl
- LEAF_Nexus/templates/main.tpl
- LEAF_Request_Portal/admin/templates/main.tpl
- LEAF_Request_Portal/templates/main.tpl
- LEAF_Request_Portal/templates/view_homepage.tpl
Displays an alert if a user accesses the site with Internet Explorer that advises them to use Chrome or Edge.
Also displays a more prominent message on the portal homepage.
> LEAF 2795 alert IE users

- LEAF_Nexus/admin/templates/main.tpl
- LEAF_Nexus/templates/main.tpl
- LEAF_Request_Portal/Inbox.php
- LEAF_Request_Portal/admin/templates/main.tpl
- LEAF_Request_Portal/api/controllers/InboxController.php
- LEAF_Request_Portal/js/dialogController.js
- LEAF_Request_Portal/templates/main.tpl
- LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
- LEAF_Request_Portal/templates/reports/LEAF_inbox_combined.tpl
- LEAF_Request_Portal/templates/reports/LEAF_table_input_report.tpl
- LEAF_Request_Portal/templates/view_homepage.tpl
- LEAF_Request_Portal/templates/view_reports.tpl
- libs/js/LEAF/intervalQueue.js
- test/ComplianceScanner/package-lock.json
> Rc/2022 04 25/sprint 28 c2/trfh clarify api timeline explorer 2777

- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/templates/view_reports.tpl
Adds styling, as well as title and label text, to indicators that are archived to clearly distinguish them during Report Builder question selection.
> Leaf 2999 reportbuilder: visual display of archived fields

- LEAF_Request_Portal/form.php
Add checks to make sure values for in () are actually set before trying to run query. Also updated a few of the select statements to be more inline with coding standards.
> LEAF-2975 Queries WHERE IN  are null/empty

- LEAF_Request_Portal/js/dialogController.js
A different issue lead me to this, and I was confused by what "indicatorID" was in this context. Hopefully this helps someone in the future.
> Clarify this is for a load indicator

- LEAF_Request_Portal/templates/reports/LEAF_National_Distribution.tpl
This saves about 2x time when deploying to many sites by replacing a sequential call with a rate limited async one.
> Update sites in parallel

- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
- LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
Prevents a potential issue where dc.js charts end up in an inconsistent state if there's no data in the initial view.
> Work around issue with blank charts

- LEAF_Request_Portal/js/workflow.js
This will show a loading screen and disable action buttons while workflow extensions are loading (LEAF_workflow_indicator.tpl).
> Prevent required field bypass (workflow indicator)

- LEAF_Request_Portal/admin/css/mod_form.css
- LEAF_Request_Portal/admin/templates/mod_form.tpl
- LEAF_Request_Portal/admin/templates/site_elements/generic_xhrDialog.tpl
re-pr of 3061 from a leaf_2.0 branch
> Bug leaf 3061 form editor fixes v2p0

- LEAF_Request_Portal/js/form.js
- LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.css
- LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
Prevents an error on the form-entry side if a question contains a condition entry based on a controller question that had been archived or deleted.  
Fixes a condition-editor issue that prevented the deletion of conditions based on archived/deleted controller questions.
The conditions editor also provides additional feedback to users if a condition has an archived/deleted controller, or if the base format of the child question had changed after it was last saved.
> leaf 3069 handle parent archive

- LEAF_Request_Portal/api/controllers/UserActivity.php
- LEAF_Request_Portal/api/index.php
- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/templates/main.tpl
- libs/js/LEAF/sessionAnnounce.js
This attempts to synchronize session timeout states between multiple instances of the same session.
LEAF-3096
> LEAF-3096 Feature/session revamp

- LEAF_Nexus/db_mysql.php
- LEAF_Nexus/scripts/refreshOrgchartEmployees.php
make adjustments to the insert to make it a prepared statement.
> LEAF-3128 Batch Insert Data Sanitization

- .gitignore
- LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
Rework let, add back in my checks for when some data is not present, this could possibly be added upon, however adding back what I had previously. I am also adding the temp_leaf_timeline_data.txt to the gitignore.
The issue that prompted this was date changes were not filtering the view.
> LEAF-2907 Rework

- docs/InstallationConfiguration.md
Add in my documentation from when we were working on LEAF 2, now that things appear to have slowed down and documentation can be solidified some what.
> LEAF Installation Documentation for 2-0

- LEAF_Request_Portal/admin/templates/main.tpl
This was mistakenly left out of the admin/main.tpl file.
> LEAF-3129 Add missing script

- LEAF_Request_Portal/db_mysql.php
Adjust how the setattribute is set.
> LEAF-3157 setAttribute

- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/admin/templates/mod_access_matrix.tpl
- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
- LEAF_Request_Portal/api/controllers/WorkflowController.php
- LEAF_Request_Portal/sources/Workflow.php
This builds a list of active Workflow Requirements, tentatively labeled as "Task", and provides a simple interface to add/remove groups.
> LEAF-3118 Simplified interface for (workflow requirement) access management

- LEAF_Request_Portal/sources/System.php
This removes Site Director from being added to the groups
> LEAF-3191 hotfix sync services

- LEAF_Nexus/js/employeeSelector.js
- LEAF_Nexus/js/groupSelector.js
- LEAF_Nexus/js/nationalEmployeeSelector.js
- LEAF_Nexus/js/positionSelector.js
- LEAF_Request_Portal/templates/subindicators.tpl
This simplifies potential customization of orgchart_* widgets.
> LEAF-3170 Add customization hooks in orgchart_* input widgets

- LEAF_Nexus/admin/templates/main.tpl
- LEAF_Nexus/css/printer.css
- LEAF_Nexus/css/style.css
- LEAF_Nexus/js/groupSelector.js
- LEAF_Nexus/js/positionSelector.js
- LEAF_Nexus/templates/main.tpl
- LEAF_Request_Portal/css/printer.css
- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/js/formPrint.js
- LEAF_Request_Portal/js/gridInput.js
- LEAF_Request_Portal/templates/file_form.tpl
- LEAF_Request_Portal/templates/file_image_form.tpl
- LEAF_Request_Portal/templates/form.tpl
- LEAF_Request_Portal/templates/initial_form.tpl
- LEAF_Request_Portal/templates/main.tpl
- LEAF_Request_Portal/templates/subindicators.tpl
Adds specific aria labels for various question formats (grids, org groups, positions, single and multiselect dropdowns, checkbox/es and radio inputs).  Adds additional html landmark elements and tabbing to initial form page and associated style updates.  Adds keyboard input controls for form navtree menu.
> LEAF  3165 - 508 improvements follow-up (new)

- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/templates/subindicators.tpl
Getting an index based on Filename. based on file name I'm getting the data from the db and figuring out which index that filename is. Then proceed the same as before based on this index, which is not necessarily the same as that on the web page.
> LEAF-3197 modified how files get deleted

- LEAF_Request_Portal/FormWorkflow.php
- LEAF_Request_Portal/js/workflow.js
- LEAF_Request_Portal/templates/print_form.tpl
I tried to get every scenario covered with this ticket.
So before a request is submitted                  no comment box            no notes textbox
After submit                                                  shows                              shows
After completion no comments                    no show                          no show
After completion with comments                 show                                no show
All this happens automatically without a page refresh.
> Leaf-3213 modification to notes system

- LEAF_Request_Portal/js/form.js
- LEAF_Request_Portal/sources/FormStack.php
- LEAF_Request_Portal/templates/print_form.tpl
Updates form.js to account for differences between main form, and form field modules so that conditional questions marked as required will correctly account for the conditional display state.
edit: added missing param to FormStack to resolve a form export issue
> LEAF 3246 conditional question requirement handling in form fields

- LEAF_Request_Portal/form.php
This resolves a couple TypeErrors.
> LEAF-3253 Fix array merge error

- LEAF_Nexus/db_mysql.php
- LEAF_Request_Portal/db_mysql.php
In JIRA it is titled: LEAF 3253 - Clean up PHP TypeError  
Branch: Database connection
> LEAF 3253 - Enable persistent database connection

- LEAF_Request_Portal/api/controllers/UserActivity.php
This removes dead code that triggered an undefined property warning.
> LEAF-3297 - Resolve undefined property warning

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Fixes an issue with non-selfclosing textarea tag
> LEAF-3296 - fix input type

- LEAF_Nexus/db_mysql.php
- LEAF_Request_Portal/db_mysql.php
This is reverted back to the original with a couple exceptions. First, db_mysql in the Nexus folder did not have the pdo_options originally but Portal did so I left it in both the way it was on the Portal originally. Second, cleaned up the code to follow PSR12 for the two methods that were changed here.
> Leaf-3289 undoing Leaf-3253

- LEAF_Request_Portal/Email.php
- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/api/controllers/WorkflowController.php
- LEAF_Request_Portal/scripts/automated_email.php
- LEAF_Request_Portal/sources/Workflow.php
- LEAF_Request_Portal/templates/email/LEAF_automated_reminder_body.tpl
- LEAF_Request_Portal/templates/email/LEAF_automated_reminder_subject.tpl
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2022050300-2022110300.sql
- scripts/automatedEmailReminder.php
- scripts/scheduled-task-commands/automatedEmailReminder.php
This will require a database update for storage of data, timestamp for determining when to trigger reminders and a new db entry for the templates required for this reminder. 
Setup:
- Go to the workflow and click on a step. 
- There is a new button on the bottom right called "Email Reminder"
- In this new popup you can enable or disable the reminder using the checkbox.
- This checkbox will give you some options on days/weeks/months
- The users that will be notified will be the same as choosing "notify next approver" in the event triggers
Testing:
/LEAF_Request_Portal/scripts/automated_email.php will run the process as expected, waiting for  the time to expire
/LEAF_Request_Portal/scripts/automated_email.php?current=current will trigger the email process on items that are setup for …
> LEAF 3119 - automated email notifications

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
> LEAF-3119 - disable button

- LEAF_Nexus/ajaxEmployee.php
- LEAF_Nexus/index.php
This is going over possible places where XSS attacks can come through. In the end all of this data I think is sanitized before it is used, but this
> LEAF-3322 Fortify Scan Cross-Site scripting

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/scripts/automated_email.php
- LEAF_Request_Portal/sources/Workflow.php
Add in new text replacing old functionality, this has aria tags and allows for tabbing.
Adjust database to be name spaced so it can be used by others.
Update script to use the name spaced value.
> LEAF-3308 Email Reminder timing text

- LEAF_Request_Portal/admin/templates/print_subindicators.tpl
- LEAF_Request_Portal/form.php
- LEAF_Request_Portal/js/form.js
- LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
- LEAF_Request_Portal/templates/print_form.tpl
File updates associated with condition ('IFTHEN') entry, and form functionality, for radio format questions (both as controlled and controller questions).  
Some reorganization of related formjs code.
> LEAF 3216 IFTHEN radio format

- docker/mysql/db/db_upgrade/orgchart/Update_OC_DB_2020062600-2022122900.sql
- docker/mysql/db/db_upgrade/orgchart/Update_OC_DB_4403-4494.sql
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2022110300-2022122900.sql
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_4344-4346.sql
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_5372-5410.sql
Here are the db updates necessary for the autoloader to work properly.
Also worth mentioning, 3 files were changed in a different step, I'm changing them back to what they were.
> Leaf 3361 update dbs

- LEAF_Request_Portal/templates/subindicators.tpl
Add validation layer checking for zero accounts in employeeSelector.
> LEAF-2551: Zero Account Validation

- LEAF_Request_Portal/FormWorkflow.php
updates queries to the services table to correct behavior for members of multiple ELT groups
other: updates method return type for getLactAction to avoid a php error
> LEAF 3405 remaining ELT group access issues

- LEAF_Nexus/db_mysql.php
- LEAF_Request_Portal/db_mysql.php
Log DB connection issues to server
> Log error on server

- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2022110300-2023012400.sql
db update to change the html and htmlPrint fields in the indicators table
> Leaf 3427 script to update db field

- LEAF_Request_Portal/FormWorkflow.php
Fix undefined variable flagged by IDE.
> Leaf 3430 Fix typo

- LEAF_Request_Portal/Email.php
Add in logic to make sure it does not attempt to send email if there are no recipients set for sending the email. (Line 303)
Additional work was setup with coding standards so more than a single line of change.
> LEAF-2381 - Email No recipient

- LEAF_Request_Portal/Email.php
Email addresses can also come in as null, was only looking for strings since that is all I would see.
> LEAF 2381 - email address can come in as null

- LEAF_Request_Portal/api/controllers/FormStackController.php
- docker/swagger/portal-swagger.json
I noticed an undefined method error via IDE. Removed API endpoint since it wouldn't work and there doesn't seem to be any references to it.
> LEAF-3502 - Remove dead code

- LEAF_Nexus/scripts/refreshOrgchartEmployees.php
This will make sure that if the user hasn't been updated after one week to be marked as disabled by adding the timestamp.
> LEAF-2875 Mark old accounts as disabled

- LEAF_Request_Portal/api/controllers/IconPickerController.php
- LEAF_Request_Portal/api/index.php
- LEAF_Request_Portal/sources/IconPIcker.php
- LEAF_Request_Portal/templates/reports/LEAF_sitemaps_template.tpl
- LEAF_Request_Portal/templates/sitemap.tpl
https://vajira.max.gov/browse/LEAF-3434
> LEAF-3434: Combined Inbox Part 1: Update sitemap editor

- LEAF_Request_Portal/admin/templates/mod_system.tpl
This fixes an issue where the LEAF-S status (Admin Panel -> Site Settings) of new sites is stuck on "Loading...".
This issue is visible in Chromium based browsers (Edge/Chrome) starting around version 108.
> LEAF-3513 - Fix length check

- LEAF_Request_Portal/admin/templates/mod_access_matrix.tpl
- libs/js/LEAF/intervalQueue.js
This updates the Access Matrix feature found in Nationally Standardized Subordinate sites.
This new version includes steps such a "Read Only Access" (or steps that are not connected to any other steps) as configurable options.
> LEAF-3554: Update Access Matrix

- docker/nginx/leaf_nginx.conf.template
This is for the local development update for libs/dynicons. To test this you will need to rebuild your local dev for changes to take effect.
> LEAF-3751 - dynicons backward compatibility

- LEAF_Request_Portal/admin/templates/mod_form.tpl
This looks like it should do it.  Hopefully there are no other surprises.
> LEAF 3515 update order for default value display

- LEAF_Request_Portal/scripts/automated_email.php
Test criteria is in the JIRA ticket
> LEAF-3572 - When the addl days not set the email will not get the the information

- LEAF_Request_Portal/templates/reports/LEAF_inbox_combined.tpl
Addresses font and margin adjustments mentioned during demo of combined inbox.
> LEAF-3672 font size and margin adjustments

- LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
Adjusts logic so that the appropriate input area will still display if loading a dropdown is the chosen outcome for a question and that question is the only question on the page.  Also simplifies some template logic by using computed values.
> LEAF 3660 option load edgecase fix

- libs/js/codemirror/addon/merge/merge.js
The call on() in merge.js sets a callback that could lead to a race condition (Time and State, Structural). In line 123-139 is the updated version for this issue.
> LEAF-3507 Merge.js Race Condition Issue

- LEAF_Nexus/api/controllers/NationalEmployeeController.php
- LEAF_Nexus/scripts/VAMC_directory_maintenance2_AD.php
- LEAF_Nexus/scripts/syncSVNrevision.php
- LEAF_Nexus/sources/Config.php
- LEAF_Request_Portal/index.php
- LEAF_Request_Portal/scripts/VAMC_directory_maintenance2_AD.php
- LEAF_Request_Portal/sources/Config.php
- LEAF_Request_Portal/sources/Group.php
- LEAF_Request_Portal/templates/sitemap.tpl
- libs/loaders/Leaf_autoloader.php
This updates the config classes to accept to parameters so prevent the instantiation of db's and extra calls to the db when the data is already available. Please pay close attention to the VAMC_directory_maintenance2_AD, is this going to be ok?
> Hotfix config reconfig

- LEAF_Request_Portal/sources/TemplateFileHistory.php
- LEAF_Request_Portal/sources/TemplateReports.php
I replaced the rand() function with the uniqid() function due to users hitting a file cap, which required a change in function.
> LEAF-3714 - File History Limit

- LEAF_Request_Portal/sources/Config.php
- LEAF_Request_Portal/sources/Email.php
- LEAF_Request_Portal/utils/LEAF_importStandardConfig.php
This removes the DbConfig from the app. The only thing used in this file was the dbName and that was moved to Config.
> Leaf 3760/remove db config

- LEAF_Request_Portal/admin/templates/menu.tpl
This just changes the drop down menu in the admin to what was being asked for in the Developer Chat. It more closely resembles the admin homepage now.
> Leaf 3748 menu changed

- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
Previously, users encountered an issue with the email template saving feature. The system would only allow them to save a section if they made a change to the body of the email. However, the problem is now resolved. Users can save a section without needing to make any changes in the body of the email.
> LEAF-3696 Email Template Update

- .gitignore
- LEAF_Request_Portal/admin/templates/mod_templates.tpl
- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
- LEAF_Request_Portal/api/controllers/EmailTemplateController.php
- LEAF_Request_Portal/api/controllers/TemplateController.php
- LEAF_Request_Portal/api/controllers/TemplateEditorController.php
- LEAF_Request_Portal/sources/EmailTemplate.php
- LEAF_Request_Portal/sources/TemplateEditor.php
This resolves the conflict with the RC
> Leaf 3749 - identify custom templates resolve

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Added more information about backwards actions for users in the action editing modal to clarify that they not for saving data.
General Cleanup
Adjusted the contrast of Action and Event buttons to meet accessibility requirements.
Added missing error callback options to ajax setup calls and updated those that were setup with fail instead of error. 
Added some interpolation and fixed a variety of spacing issues that made mod_workflow hard to read.
> LEAF 3772 action info and general mod_workflow cleanup

- libs/js/LEAF/formSearch.js
- libs/js/LEAF/intervalQueue.js
This should help simplify error handling for people using intervalQueue by wrapping the worker function in a try/catch.
> LEAF-3781: Add error handling

- LEAF_Request_Portal/templates/initial_form.tpl
This widens a few fields on the New Request page, which minimizes word-wrapping long service names.
> Leaf 3855 - widen fields

- LEAF_Nexus/admin/templates/orgChart_import.tpl
- libs/jsapi/nexus/LEAFNexusAPI.js
LEAF_Nexus -> DATABASE_DB_DIRECTORY should be setup to have a local "NATIONAL" database.
Excel doc will need to be created with employee email, supervisor email and position title
The employee email should not exist in the local orgchart but has to exist in the national db that you created. The supervisor and position title must exist, the position title must exist and have the supervisor assigned to that position.
> LEAF-3561 - Upload employee data to orgchart

- LEAF_Request_Portal/sources/System.php
addresses issue found by Shane when testing preprod.
> Quick fix to rc

- LEAF_Request_Portal/api/controllers/WorkflowController.php
- LEAF_Request_Portal/sources/Workflow.php
- LEAF_Request_Portal/templates/print_form.tpl
In the 2 situations where an admin can click on "Change Current Step" on the record review page (a=printview):
1. When the record has been submitted, but not resolved: The dropdown list of steps only shows the steps relevant to the current workflow
2. When the record has been resolved: The dropdown list of steps only shows the steps relevant to the workflow aligned with the previous action
> Leaf 3888 - Change Current Step: implementation using existing APIs

- LEAF_Request_Portal/templates/view_reports.tpl
Parse int since there's a strict type check on line ~1262.
> LEAF-3881 - Incorrect error messge in Report Builder

- LEAF_Request_Portal/js/workflow.js
While reviewing an active record, this change will automatically expand the comment field when more than two new-lines have been entered.
> Leaf 3866 - auto expand comment field

- LEAF_Request_Portal/dynicons/index.php
- LEAF_Request_Portal/sources/Config.php
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/sources/Group.php
- libs/loaders/Leaf_autoloader.php
This covers several minor php error logs
> Leaf 3908 - minor php errors

- LEAF_Request_Portal/admin/templates/menu.tpl
- LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
- LEAF_Request_Portal/js/formSearchMultisite.js
- LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
- Remove duplicate variable declaration -- already declared from function's signature
- Add sitemap search button/links
> Leaf 3867 - remove duplicate declaration

- docker/mysql/db/boilerplate/resource_database_boilerplate.sql
This needs to go before updating the dbs foreign keys.
> Boiler plate change

- LEAF_Nexus/scripts/updateDatabase.php
- LEAF_Request_Portal/api/controllers/TemplateFileHistoryController.php
- LEAF_Request_Portal/dynicons/index.php
- LEAF_Request_Portal/scripts/automated_email.php
- LEAF_Request_Portal/scripts/updateDatabase.php
- LEAF_Request_Portal/sources/Email.php
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/sources/FormWorkflow.php
- LEAF_Request_Portal/sources/Group.php
- LEAF_Request_Portal/sources/System.php
Vast majority of these are php error logs. There are some bug fix in here as well.
Bug fix 1: Employees added to nexus import into portal as inactive
Bug fix 2: In the Config file EmailBCC needed to be an empty array if there wasn't one coming from the db
Bug fix 3: Need to delete employees that are no longer assigned in Nexus and are not locally managed.
Testing is mainly regression testing. Emphasis on Forms and sending emails.
> Leaf 3932 - more error logs

- LEAF_Request_Portal/sources/FormWorkflow.php
Remove the json stuff and swap back with the unserialize, add some checks to make sure data is set before trying to unserialize
> LEAF-3951 - Grid in email not formatting

- LEAF_Request_Portal/admin/templates/mod_groups.tpl
- LEAF_Request_Portal/sources/System.php
This deals with a error Amanda was getting and the ELT from HD
> Leaf 3902 update

- LEAF_Request_Portal/admin/templates/mod_templates.tpl
This will exclude the import_from_webHR.tpl from the template list.
> LEAF-3910 Remove import form

- LEAF_Request_Portal/admin/templates/mod_groups.tpl
- LEAF_Request_Portal/api/controllers/GroupController.php
- LEAF_Request_Portal/sources/Group.php
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023072000-2023082400.sql
Real simple, added a new query to remove the dependency_privs
> Leaf 3556 - update dependency privs

- scripts/scheduled-task-commands/refreshOrgchartEmployees.php
This is to simplify how we run the script now that we have a good source of truth we no longer need to search every directory for this information.
> LEAF-3945 - refreshOrgchartEmployees not run on all orgcharts

- libs/php-commons/Db.php
This updates the database error message.
No impact to other code.
> LEAF-3996 - Update error message

- docker/env_files/globals_swarm.env
> removing ip addresses

- docker/env_files/globals_swarm_prod.env
Can't have ip addresses showing at all.
> Remove IP addresses

- docker/mysql/db/boilerplate/resource_database_boilerplate.sql
This corrects foreign key names.
> Leaf 4014 - foreign key correction

- libs/smarty/plugins/modifier.sanitize.php
- libs/smarty/plugins/modifier.sanitizeRichtext.php
Didn't realize these were there
> Leaf 4002.3 - more bad references

- app/libs/loaders/Leaf_autoloader.php
Fixes Amanda's errors on staging
> Leaf 4002.4 - autoloader uncomment

- app/libs/globals.php
- docker/env_files/globals_local.env
Local environment was setup differently tran staging and prod. Made the change to the local env file so a docker compose down and then up will need to be accomplished in order for this change to be affective.
> Leaf 4002.5 - globals different

- LEAF_Request_Portal/index.php
- app/libs/js/LEAF/formSearch.js
js app path needed to be provided to the leaf search on the homepage.
> Leaf 4002.7 - access granted

- app/libs/globals.php
- app/libs/loaders/Leaf_autoloader.php
This fixes some abnormal formatting taking place.
> Leaf 4002.8 - abnormal formatting

- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/admin/templates/view_form_library.tpl
- app/libs/globals.php
Sorry, It was the wrong reference.
> Leaf 4002.9/need a domain const

- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/sources/FormEditor.php
Updates the path variable for libs used by the site designer and form editor vue apps.
Updates the destructionAge post to use the newer pdo_insert_query method.
> Updates for rc61 c1 - libs path fix, pdo insert query for post

- LEAF_Request_Portal/sources/FormWorkflow.php
Fixes a typo. This function is meant to amend srcRecords, but this line wasn't assigning the correct variable.
Fixes access issue!
Non-admins can approve requests
> hotfix LEAF 4056 - Fix typo

- LEAF_Request_Portal/sources/Form.php
Similar to PR#2155, this simplifies and removes redundant queries to reduce DB roundtrips. The same logic in PR#2155 used to check employee backups was also implemented here.
Features that depend on requestor follow-up and employee backups
Preconditions:
- Form is configured with "need to know" mode enabled
- Form's workflow has a requestor followup step
- A record has been created with the above preconditions, and is on the requestor followup step
> LEAF 4060 - Optimize requestor followup (1 of 3)

- LEAF_Request_Portal/js/combined_inbox_editor/src/combined_inbox_editor.vue.js
- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
- LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
Description
-Adds URL checks to the Inbox Editor app and the Sitemap Search report to prevent breaking errors caused by potential sitemap reports.
-Adds a check for unique sites for the Sitemap Search report and adds preprod and local domains to facilitate testing of this report.
Potential Impact
Admin area Combined Inbox Editor and Sitemap Search features
> LEAF 4055 Combined Inbox Editor and Sitemap Search updates

- LEAF_Request_Portal/admin/css/mod_templates.css
- LEAF_Request_Portal/admin/css/mod_templates_reports.css
- LEAF_Request_Portal/admin/templates/mod_templates.tpl
- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
- LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
Minor usability improvements:
- Removed incorrect occurrences of a "changes not saved" message that only seems to occur on Windows filesystems
- Increase viewable code area
Presentation layer changes within LEAF Programmer, Template Editor, and Email Template Editor
1. Open "Admin Panel -> LEAF Programmer"
2. Click "Home". There should not be any error messages.
> LEAF-4122: Programmer UX

- LEAF_Request_Portal/admin/css/mod_templates.css
- LEAF_Request_Portal/admin/css/mod_templates_reports.css
- LEAF_Request_Portal/admin/templates/mod_templates.tpl
- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
- LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
- LEAF_Request_Portal/file.php
- LEAF_Request_Portal/js/formQuery.js
- LEAF_Request_Portal/js/formSearch.js
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/sources/FormWorkflow.php
- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This has:
LEAF-4121
LEAF-4122
LEAF-4120
LEAF-4123
LEAF-4119
Enable easy file embeds #2228
> Rc/2023 11 14/sprint 65 c1

- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
- LEAF_Request_Portal/sources/Workflow.php
Adds some additional information to the email template editor, under the file/header name, to inform users which parties the selected custom email event notifies (Requestor, Next Approver, or specific group).
Email Template Editor
Ensure that correct notification information is displayed and that unexpected errors do not occur.
> LEAF 2747 Email Template Editor notification info

- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
Adds some requested style updates for jira 2747 (email template notification information).
> LEAF 2747 email template event info style updates

- scripts/time_to_evolve.php
Summary:
This is a script to supply a string to search for. That string will be searched in all portals. and a json result will be saved for later use.
None, it only searches and saves a files to a directory.
Testing:
None.
> Leaf 4116 - Find a string

- LEAF_Nexus/js/employeeSelector.js
- LEAF_Nexus/js/nationalEmployeeSelector.js
- LEAF_Request_Portal/admin/templates/mod_templates.tpl
- LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
- LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
- LEAF_Request_Portal/js/formQuery.js
- LEAF_Request_Portal/js/formSearch.js
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/sources/FormWorkflow.php
- LEAF_Request_Portal/sources/Group.php
- LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
- LEAF_Request_Portal/templates/view_reports.tpl
- LEAF_Request_Portal/utils/LEAF_exportStandardConfig.php
- LEAF_Request_Portal/utils/LEAF_importStandardConfig.php
- app/Leaf/Logger/Formatters/DataActions.php
- app/Leaf/Logger/Formatters/PortalGroupFormatter.php
LEAF-2569
LEAF-4107
LEAF-4155
LEAF-4165
LEAF-4166
LEAF-4171
LEAF-4172
LEAF-4173
LEAF-4186
> Rc/2023 12 5/sprint 65 c3

- LEAF_Request_Portal/templates/subindicators.tpl
Fixes eye icon link in form entry label.
> LEAF 4190 fix eye icon url

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/api/controllers/WorkflowController.php
- LEAF_Request_Portal/sources/Workflow.php
- app/Leaf/Logger/DataActionLogger.php
- app/Leaf/Logger/Formatters/DependencyFormatter.php
- app/Leaf/Logger/Formatters/WorkflowFormatter.php
- app/Leaf/Logger/LogFormatter.php
Adds requirement(dependency) related information to the workflow history.
Addition or removal of a requirement will be reflected in the workflow history modal.
If a requirement is associated with a step in the workflow, additional information about requirement group privileges and requirement description changes will also be listed.
Impact/Testing
Workflow Editor - confirm that logging occurs as expected and that other behavior remains as expected.
> LEAF 4194 - workflow requirement related logging

- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/api/controllers/WorkflowController.php
- LEAF_Request_Portal/js/workflow.js
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/sources/Workflow.php
- LEAF_Request_Portal/templates/subindicators.tpl
- app/Leaf/Logger/DataActionLogger.php
- app/Leaf/Logger/Formatters/DependencyFormatter.php
- app/Leaf/Logger/Formatters/WorkflowFormatter.php
- app/Leaf/Logger/LogFormatter.php
-	LEAF-3190 – Prevent modification of built-in workflows
-	LEAF-4190 – Remediate broken image link
-	LEAF-4191 – Prevent deleted internal forms from appearing on PDF exports
-	LEAF-4193 – Prevent date picker element within an inline field from shifting when opened within the Inbox “Take action” dialog
-	LEAF-4194 – Update the Workflow History to show changes to Workflow Step Requirements
> Rc/2024 01 16/sprint 66 c1

- LEAF_Request_Portal/js/dialogController.js
- LEAF_Request_Portal/js/gridInput.js
This resolves minor issues identified by CodeQL.
Areas that depend on dialogs and gridInput
> LEAF-4198 - CodeQL remediation

- LEAF_Request_Portal/js/form.js
Fixes logic that could incorrectly filter out crosswalk / loaded dropdown conditions.
> LEAF 4169 fix crosswalk issue

- LEAF_Request_Portal/js/combined_inbox_editor/src/combined_inbox_editor.vue.js
Combined Inbox Editor update to handle errors associated with incorrect URLS
> Rc69c1 handle form fetch related errors from casing or typos

- LEAF_Request_Portal/templates/email/LEAF_automated_reminder_subject.tpl
- LEAF_Request_Portal/templates/email/LEAF_mass_action_remind_subject.tpl
- LEAF_Request_Portal/templates/email/LEAF_notify_next_subject.tpl
- LEAF_Request_Portal/templates/email/LEAF_send_back_subject.tpl
Minor update for email subject.
- People who potentially have email rules set up based on subjects might need to update their rules (Mitigate impact via CoP announcement)
N/A
> Leaf 4251 - Update email subject text

- LEAF_Nexus/scripts/refreshOrgchartEmployees.php
Issue:
Error log is overrun by this error, need to add in checks to make sure this goes away. 
[23-Feb-2024 00:00:01 UTC] PHP Warning:  Undefined array key "xxxxxxx" in /var/www/html/VISNx/xxx/orgchart/scripts/refreshOrgchartEmployees.php on line 250
Testing:
To do testing you will need an active user in the local orgchart that does not exist in the national orgchart. (deleted user at a national level)
You will also need to have a user that is not locally added at time of script (new user) and verify data for that user is pulled in.
> LEAF-4256 - PHP Warning Undefined array key

- x-test/API-tests/service.go
- x-test/API-tests/service_test.go
Testing that all Service Heading are as they should be.
> Leaf 4264 - service headings test only

- docker/docker-compose.yml
- x-test/API-tests/formStack.go
- x-test/API-tests/formStack_test.go
- x-test/API-tests/form_test.go
Adds struct and types for testing Form Editor related category records and testing for new form property values.
Adds read data access check for request records to existing form_test
> LEAF-4266 (API-tests) New Form Property checking

- LEAF_Request_Portal/scripts/automated_email.php
- LEAF_Request_Portal/sources/Email.php
- LEAF_Request_Portal/sources/Login.php
- docker/docker-compose.yml
- docker/php/leaf_monlith.dockerfile
- scripts/automatedEmailReminder.php
- scripts/timebracketcmd.php
**Issue:**
Automated emails were not coming through, this is an error that we saw in our logs and did not have a case study to figure out what is going on since there were no paths shown around the error in the main log. 
What I found to be the issue, the query is not returning a userid, further inspection using directive in the sql query is not joining as one would expect. When I adjusted the query to specifically use specific columns it returns the data that I would have expected.
**Replication:**
Setup a site with need to know, put the step into a state where it will send an automated email to a user that is not part of the administrators group. Need to also make sure no other users will admin access will be getting emails as well since if the first user is an admin everything will …
> LEAF-4241 - INC31179685 - mail error no recipients

- LEAF_Request_Portal/js/formGrid.js
- app/libs/js/LEAF/formGrid.js
This will replace the rc formGrid (js and app version) with the version on the current master branch.
> LEAF 4308 new - use current master formGrid for now

- LEAF_Request_Portal/templates/subindicators.tpl
Portals that have custom sub indicators would not get this change. The issue is not wide and grand but something to consider.
Testing:
Regression testing
Make sure the end user cannot get around the requirements by just entering a space.
Acceptance Criteria:
Users not being able to enter a space for text or currency to get around requirements.
> LEAF-4294 - site admin clear required field

- LEAF_Nexus/templates/view_position.tpl
- LEAF_Request_Portal/admin/templates/menu.tpl
- LEAF_Request_Portal/admin/templates/mod_workflow.tpl
- LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
- LEAF_Request_Portal/sources/System.php
- LEAF_Request_Portal/templates/reports/LEAF_Data_Visualizer.tpl
- LEAF_Request_Portal/templates/subindicators.tpl
LEAF tickets:
4291
4271
4294
4298
4307
> Rc/2024 04 16/sprint 72 c2

- LEAF_Request_Portal/js/formGrid.js
Adds a formGrid specific update that had also been part of RC 72
> LEAF 4325 add missing formGrid update from prev RC (4267)

- docker/docker-compose.yml
- docker/mysql/dev_db/dev_national_leaf_launchpad.sql
- x-test/api-test-helper/main.go
This includes a change I supposed in the LEAF-4170 PR, this also includes the missing db entry and removes an un needed duplicate line. This allows for tests to fully run.
> rc cleanup s73 c2

- docs/InstallationConfiguration.md
Provide additional guidance when standing up a dev environment.
- No dependencies
> Dev installation guidance

- LEAF_Nexus/templates/print_subindicators.tpl
- LEAF_Nexus/templates/view_employee.tpl
- LEAF_Request_Portal/api/controllers/FormWorkflowController.php
- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/js/formSearch.js
- LEAF_Request_Portal/js/workflow.js
- LEAF_Request_Portal/sources/FormWorkflow.php
- LEAF_Request_Portal/templates/reports/LEAF_Data_Visualizer.tpl
- LEAF_Request_Portal/templates/view_reports.tpl
- x-test/API-tests/database/portal_test_db.sql
- x-test/API-tests/dbsetup_test.go
- x-test/API-tests/employee_test.go
- x-test/API-tests/formQuery_test.go
- x-test/API-tests/formStack_test.go
- x-test/API-tests/formWorkflow_test.go
- x-test/API-tests/form_test.go
- x-test/API-tests/hotspot_benchmarks_test.go
- x-test/API-tests/main_test.go
- x-test/API-tests/service_test.go
LEAF tickets:
4327
4315
4341
4342
4343
4346
> Rc/2024 05 14/sprint 74 c2

- LEAF_Request_Portal/admin/templates/mod_account_updater.tpl
- LEAF_Request_Portal/admin/templates/mod_system.tpl
- LEAF_Request_Portal/css/style.css
- LEAF_Request_Portal/js/formGrid.js
- LEAF_Request_Portal/js/formPrint.js
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
- LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
- LEAF_Request_Portal/templates/view_reports.tpl
- app/libs/js/LEAF/formGrid.js
- docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024022901-2024052000.sql
- docker/vue-app/src/site_designer/LEAF_Designer.scss
- libs/js/LEAF/formGrid.js
LEAF tickets:
4238
4359
4361
4351
4350
4232
4360
> Rc/2024 05 21/sprint 75 c1

- LEAF_Nexus/scripts/refreshOrgchartEmployees.php
- LEAF_Request_Portal/scripts/automated_email.php
- app/Leaf/ErrorNotify.php
- docker/php/leaf_monlith.dockerfile
- libs/php-commons/ErrorNotify.php
- scripts/scheduled-task-commands/automatedEmailReminder.php
- scripts/scheduled-task-commands/globals.php
- scripts/scheduled-task-commands/refreshOrgchartEmployees.php
Description
Update existing automated scripts to return status codes on success/failure
code value
message describing nature of the issue
suggestion to fix
Update CRON class to redirect failure codes to an email forwarded to the dev team
Provide each piece of the status message for devs to read
Testing:
regression testing will be needed, since this is a script this may not be as testable for the testing team. Will need to discuss with testing team on how to hand these items off.
Additional Notes:
Mailer was not installed on the master branch I pulled.
> LEAF-3895 - Automated Scripts Error Handling

- LEAF_Request_Portal/sources/Form.php
Fixes a warning associated with potentially undefined key
> LEAF 4405 fix warning associated with undefined array key

- LEAF_Request_Portal/sources/System.php
> LEAF-4414 getfiles - update param type

- test/Test-Automation/src/main/java/pages/BasePage.java
- test/Test-Automation/src/main/java/pages/FormEditorPageActions.java
- test/Test-Automation/src/main/java/pages/SiteSettingsPageActions.java
- test/Test-Automation/src/main/java/pages/UserAccessGroupsPageActions.java
- test/Test-Automation/src/main/java/pages/WorkflowEditorPageActions.java
- test/Test-Automation/src/main/java/pages/adminPage_Actions.java
- test/Test-Automation/src/main/resources/suites/testng.xml
- test/Test-Automation/src/test/java/FormEditorTests.java
- test/Test-Automation/src/test/java/WorkflowEditorTests.java
- test/Test-Automation/testng.xml
Added Test for User Access Group, Site Settings, Form Editor and WorkFlow Editor.
>   added test for Site settings, user access groups and workflow editor

- LEAF_Request_Portal/templates/view_reports.tpl
This includes the x-filterData parameter as an example for developers.
> Leaf-4445 Promote x-filterData in the dev example

- LEAF_Nexus/admin/templates/admin_update_database.tpl
- LEAF_Nexus/sources/Employee.php
- LEAF_Request_Portal/admin/templates/admin_update_database.tpl
- LEAF_Request_Portal/admin/templates/mod_account_updater.tpl
- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/sources/Workflow.php
- app/Leaf/DbUpdate.php
- scripts/leaf-scripts/update_AH_userMetadata.php
- x-test/API-tests/dbsetup_test.go
- x-test/API-tests/formQuery_test.go
LEAF tickets:
4461
4443
4460
4462
4467
> Rc/2024 08 07/sprint 79 c1 t2

- LEAF_Request_Portal/admin/index.php
- LEAF_Request_Portal/scripts/automated_email.php
- LEAF_Request_Portal/sources/Email.php
- LEAF_Request_Portal/sources/FormWorkflow.php
> Rc/2024 08 14/sprint 79 c2

- LEAF_Request_Portal/mailer/mailer.php
- app/Leaf/ErrorNotify.php
- scripts/scheduled-task-commands/automatedEmailReminder.php
- scripts/scheduled-task-commands/automatedEmailReminderVAPO.php
This adds error logging on the server, we will connect with Dynatrace to setup monitoring of these files next.
> Leaf 4106 - monitor log failures

- .gitmodules
- docker/docker-compose.yml
- docker/nginx/src/index.html
> adding in the automated test submodule

- LEAF_Nexus/templates/main.tpl
- LEAF_Request_Portal/templates/main.tpl
- No Impact to LEAF
- Add's banner for Non-Production VAPO sites already migrated
> VAPO: Update Testing Banner for Non-Production

- LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
- LEAF_Request_Portal/admin/templates/view_form_library.tpl
- LEAF_Request_Portal/templates/reports/LEAF_Start_Request.tpl
Changes:
- Adds a pathway to contribute forms into the LEAF Library
- Adds a "Setup Quicklink" tool
- Changed icon for the New Account Updater
1. Admin Panel -> LEAF Library -> Contribute my Form
2. You should be prompted with "What's the name of my form?"
1. Navigate to Admin Panel -> Setup Quickstart Link
2. Create a Quickstart Link
3. Navigating to the new link starts a new request for the form that was selected
> LEAF-4545 Form Library UX and Quicklinks

- go.work
This removes a couple unused files.
None, the files are not used.
N/A
> Remove unused files

- docker/nginx/src/index.html
- docker/playwright/playwright.dockerfile
This improves guidance for Testing within the development environment.
No dependencies in production.
> LEAF-4579 - Improve Testing UX

- LEAF_Nexus/index.php
- LEAF_Nexus/js/employeeSelector.js
- LEAF_Nexus/js/nationalEmployeeSelector.js
- LEAF_Nexus/sources/Employee.php
- LEAF_Nexus/sources/Position.php
- LEAF_Nexus/templates/view_group_permissions.tpl
- LEAF_Nexus/templates/view_permissions.tpl
- LEAF_Nexus/templates/view_position_permissions.tpl
- LEAF_Request_Portal/admin/templates/mod_account_updater.tpl
- LEAF_Request_Portal/js/formGrid.js
- LEAF_Request_Portal/templates/view_reports.tpl
- health_checks/index.php
LEAF tickets:
4549
4564
4559
4482
4572
API tests:
[sprint84c1_api.txt](https://github.com/user-attachments/files/17578815/sprint84c1_api.txt)
E2E tests:
[sprint84c1_e2e.txt](https://github.com/user-attachments/files/17577479/sprint84c1_e2e.txt)
> Rc/2024 10 30/sprint 84 c1

- LEAF_Request_Portal/sources/Form.php
- LEAF_Request_Portal/sources/FormWorkflow.php
- LEAF_Request_Portal/sources/View.php
- LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
- LEAF_Request_Portal/templates/view_reports.tpl
- LEAF_Request_Portal/templates/view_status.tpl
revert for enhance/LEAF-4455/metadata_read_all
This reverts commit ab2d96e8bc16a352eecf0fd61f5a7f02b7f4a425, reversing changes made to 9f6733fb97f0fcf678a9551393b4cadf19c30e24.
> Revert - Merge pull request #2615 (leaf-4455)

- LEAF_Nexus/sources/Employee.php
> Rc/2025 01 06/sprint 87 c1

- LEAF_Nexus/sources/Employee.php
Errors were found in testing on staging after the cron job was enabled. Reverting to address these errors and have more testing on staging before moving to prod.
> Leaf 4486 - back off user disabled

- app/Leaf/VAMCActiveDirectory.php
- scripts/scheduled-task-commands/updateExistingDisabledEmployees.php
- scripts/updateExistingDisabledNationalOrgchart.php
This is a script to update existing disabled users in the national orgchart.
> Leaf 4630 - update existing disabled user names

- LEAF_Request_Portal/js/workflow.js
**Description:**
- Add a async false to ajax call for workflow step modules to fix error of loading modules
**Acceptance Criteria:**
- Modules load without any errors
> LEAF-4657: Change Async to False on WorkflowStepModules

- docker/mysql/db/db_upgrade/orgchart/Update_OC_DB_2024092100-2025021600.sql
A task to add M and T1 to indicator 2 format in the nexus was requested. This is that requested being completed.
Testing:
Run the update db script for the nexus.
Verify that the format now has T1 and M in the list.
> Leaf 4670 - nexus indicator update

- LEAF_Nexus/index.php
- LEAF_Nexus/sources/Platform.php
- LEAF_Nexus/templates/view_group.tpl
Because local global variables are slightly different than the same variables on staging and prod I had to make an adjustment to the code so it would work there.
> Leaf 4571 - fix orgchart path

- .github/pull_request_template.md
This introduces a GitHub template. It helps improve Pull Request (PR) consistency by providing built-in guidance when opening a PR. Consistently readable PRs improve the quality of the platform's release notes.
This modifies the development process. Providing advance developer notification can help streamline the change.
N/A
> Leaf 4695 - Pull request template

- app/Leaf/VAMCActiveDirectory.php
The employee update script was not including valid userNames in the import. The condition was changed to allow those updates to happen.
> Leaf 4693 - HOTFIX - change condition

- LEAF_Request_Portal/sources/Form.php
This resolves a potential issue where records can be left in an inconsistent state, identified by our team.
The inconsistent state can result in a situations where the record is marked as deleted, but still retains a reference to its workflow state. This combination prevents the related workflow step from being deleted, and in the event that the step needs to be deleted, creates confusion as people don't normally look for cancelled records to move them off the step.
Minor cleanup: Remove unused variables.
This can potentially impact features that involve cancelling records such as Print Form -> Cancel Record and Mass Action -> Cancel Records.
Existing "Cancel Request" automated test coverage: https://github.com/department-of-veterans-affairs/LEAF-Automated-Tests/blob/6a0cbb171d7b12f3bb3cf0 …
> LEAF-4706 Wrap cancel-request queries in a transaction

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This change sets up allowing mass action in the inbox
The user will potentially have more sections to look through depending on current status of each request. The offset is in an upcoming release mass action will be added to the inbox.
Set up an inbox that has multiple requests in different statuses
Navigate to the inbox and observe that each status has it's own section heading 
open each section and make sure that only the requests in that status show up
> Leaf 4701 - refactor inbox sections by role (currentstatus)

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Reverts department-of-veterans-affairs/LEAF#2700
> Revert "Leaf 4701 - fix organize by form view"

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Reverts department-of-veterans-affairs/LEAF#2696
> Revert "Leaf 4701 - refactor inbox sections by role (currentstatus)"

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This resolves a deployment process issue where https://github.com/department-of-veterans-affairs/LEAF/pull/2715 was not merged.
Same as https://github.com/department-of-veterans-affairs/LEAF/pull/2715
Same as https://github.com/department-of-veterans-affairs/LEAF/pull/2715
> HOTFIX: LEAF-4756 - Fix incomplete merge: PR#2715

- LEAF_Request_Portal/templates/reports/LEAF_Start_Request.tpl
This explains a more advanced feature within `records.php?a=LEAF_Start_Request`, primarily to inform advanced users of this feature's existence.
No functional changes.
> LEAF-4769 - Add tip in LEAF_Start_Request

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
This improves interface reliability by resolving a page [hydration](https://playwright.dev/docs/navigations#hydration) issue.
This issue was discovered by the automated test suite: https://github.com/department-of-veterans-affairs/LEAF-Automated-Tests/issues/82
Covered by existing test: https://github.com/department-of-veterans-affairs/LEAF-Automated-Tests/blob/af0f82f48927c164fe66b71baab28987210bcfa0/end2end/tests/lifecycleSimpleTravel.spec.ts#L233
> LEAF-4772 - Resolve page hydration issue

- LEAF_Request_Portal/sources/Form.php
This works toward improving error feedback for customers.
Instead of returning HTTP 200 (Success) and a "0" even when there is an error, this returns a more appropriate HTTP code and a short explanation.
Code that depends on a `== "0"` condition to detect an error could be impacted, however no such code exists in the standard codebase. If a customization depends on a `== "0"`, it should instead be changed to `!= "1"`.
- All existing automated tests must pass.
- This test has been updated to reflect the new error response behavior: https://github.com/department-of-veterans-affairs/LEAF-Automated-Tests/pull/87
> LEAF-4810 Form.php: Update error response behavior in doModify()

- docs/InstallationConfiguration.md
Update the documentation to include the exact string. this appears to have changed slightly
This only exists to update the documentation for installation.
Documentation Update
This is a document update, please run through your local setup to see if we need more info.
> Documentation Update

- LEAF_Request_Portal/api/controllers/WorkflowController.php
- LEAF_Request_Portal/sources/Workflow.php
This expands support for more customizations via a new API endpoint: `./api/workflow/step/[digit]/actions`
This returns an array of the actions available for a given stepID.
This is a new endpoint, and thus has no dependencies.
Automated test added: https://github.com/department-of-veterans-affairs/LEAF-Automated-Tests/pull/105
> Leaf 4849 - New endpoint: ./api/workflow/step/[digit]/actions

- LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
It was uncovered through INC38928512 that the presence of stapled forms causes inconsistent display of column customizations.  Form-specific custom columns are missing from the Form View when a form in the inbox section has a staple, and the main form has an ID that sorts higher than the stapled ID.  This update is to ensure that form specific inbox customizations display as expected when appropriate.
Inbox processing and presentation is dependent on multiple variables.  This will make test development more challenging.  Variables include:
The current inbox view (Form View, Role View, Combined Role View, Admin View)
The number of form types represented in each section
The presence of stapled forms
Whether a site card exists
Whether there are base column customizations
Whether there are …
> LEAF 4823 - inbox column inconsistencies

- docker/mysql/dev_db/dev_national_leaf_launchpad.sql
1. Add platform/agent Portal to the sites table to be accessible in development environment
> Agent: Add agent portal to sites

- LEAF_Request_Portal/sources/Email.php
Email Reminders are currently sent to all requirements of a workflow step, even if they have already taken action.
This update will result in only requirements that are still pending action receive emails.
The approach involves a modification to the Email.php method 'attachApproversAndEmail'.
If the template for the email is a reminder type, additional logic will determine how many requirements exist on the step.
If there is more than 1 requirement, an additional query will be made to retrieve information about approver 'filled' status.
For each approver, emailing will only proceed if this status does not exist or is not filled.
Email.php, method attachApproversAndEmail.  
General Testing
The behavior change is intended to be specific to automated Email Reminders and Mass Action Email …
> LEAF-4891 Email Reminders for steps with multiple requirements
